### ISSUE TITLE
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', '{\n  "error": "invalid_grant",\n  "error_description": "Invalid JWT Signature."\n}')

### ISSUE THREAD

**Issue by gauravshimpi** [googleapis/google-cloud-python#10004]
I am facing same issue in python3.
===================================================================
from dags.util.GCloudStorage import GCloudStorage

client = GCloudStorage(
    "/home/gaurav/airflow/dags/script/gcp_credentials/my_gcs_credentials.json", ""project_name)

client.create_bucket("test_bucket")

===============================================================
Here's the GCloudStorage.py looks like:
from google.cloud import storage
from google.oauth2 import service_account
from google.api_core import exceptions

class GCloudStorage:

    def __init__(self, credential_file_path, project_id):
        """
        :param credential_file_path: credential File for Authentication.
        :param project_id: project ID
        """
        self.CREDENTIAL_FILE_PATH = credential_file_path
        self.PROJECT_ID = project_id
        self.DATASET_ID = None

    def create_connection(self):
        """
        Creates Connection with Google Cloud Storage and returns client.
        :return client: Google Cloud Storage Client
        """
        google_credentials = service_account.Credentials.from_service_account_file(self.CREDENTIAL_FILE_PATH)
        # Construct a BigQuery client object.
        client = storage.Client(project=self.PROJECT_ID, credentials=google_credentials)
        return client

    def create_bucket(self, bucket_name):
        """
        Creates a new empty bucket.
        :param bucket_name: name of the bucket.
        :return responseMsg: success or other message.
        """
        # Instantiates a client
        storage_client = self.create_connection()
        response = None
        try:
            bucket = storage_client.create_bucket(bucket_name)
            print(bucket)
            response = "Bucket {} created".format(bucket.name)
        except exceptions.Conflict as error:
            response = "Bucket Already Exist: {}".format(error.code)
        return {"response": response}

    def upload_blob(self, bucket_name, source_file_name, destination_blob_name):
        """
        Uploads a file to the bucket.
        :param bucket_name: bucketName
        :param source_file_name: Source File Name
        :param destination_blob_name: Destination Blob Name.
        :return responseMsg: Success or failed response message.
        """
        storage_client = self.create_connection()
        bucket = storage_client.get_bucket(bucket_name)
        blob = bucket.blob(destination_blob_name)
        print("BlobName ---> ", blob)
        blob.upload_from_filename(source_file_name)
        response = "File {} uploaded to {}".format(source_file_name, destination_blob_name)
        print(response)
        return {"response": response}

    def delete_bucket(self, bucket_name):
        """
        Deletes a bucket. The bucket must be empty.
        :param bucket_name: bucket Name.
        :return responseMsg: success or failed response message.
        """
        # Instantiates a client
        storage_client = self.create_connection()
        bucket = storage_client.get_bucket(bucket_name)
        bucket.delete()
        response = "Bucket {} deleted".format(bucket.name)
        return {"response": response}
=============================================================
when i run the above create bucket code it gives me below error:
===========================================================
Traceback (most recent call last):
  File "/home/gaurav/airflow/dags/util/test cloud.py", line 7, in <module>
    client.create_bucket("test_bucket")
  File "/home/gaurav/airflow/dags/util/GCloudStorage.py", line 37, in create_bucket
    bucket = storage_client.create_bucket(bucket_name)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/google/cloud/storage/client.py", line 436, in create_bucket
    _target_object=bucket,
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/google/cloud/_http.py", line 417, in api_request
    timeout=timeout,
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/google/cloud/_http.py", line 275, in _make_request
    method, url, headers, data, target_object, timeout=timeout
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/google/cloud/_http.py", line 313, in _do_request
    url=url, method=method, headers=headers, data=data, timeout=timeout
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/google/auth/transport/requests.py", line 277, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/google/auth/credentials.py", line 124, in before_request
    self.refresh(request)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/google/oauth2/service_account.py", line 334, in refresh
    access_token, expiry, _ = _client.jwt_grant(request, self._token_uri, assertion)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/google/oauth2/_client.py", line 153, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/gaurav/airflow/venv/lib/python3.6/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', '{\n  "error": "invalid_grant",\n  "error_description": "Invalid JWT Signature."\n}')

Process finished with exit code 1

I am newbie to GCP, so any silly mistakes will be helpful to me.
Thank you in advance.

**Comment by IlyaFaer** [comment]
Most likely, it's not the Python client issue. Probably, your token expired, and you just need to generate another one. Also check project ID and service account ID (email).
See [this issue](https://github.com/googleapis/google-cloud-python/issues/8736) as well, it covers second common problem which causes `invalid_grant`
