### ISSUE TITLE
Spanner: IndexError: pop from empty list in _merge_struct

### ISSUE THREAD

**Issue by maxpz** [googleapis/google-cloud-python#10020]
#### Environment details

. OS type and version: Debian 9
. Python version: 3.7
. google-cloud-spanner version:  1.13.0

#### Steps to reproduce

  1. Do any query that brings thousands of results (Issue happens more often after 15k rows). I'm getting this  error inconsistently, sometimes everything works as expected, but some others we get the error. It seems that the chances of getting the error increases if do a query just after executing another one.  

#### Code example

To illustrate take a look at the following code: 

```python
res = []
with db.snapshot(read_timestamp=true_time) as snapshot:
    results = await ioloop.IOLoop.current().run_in_executor(executor, snapshot.execute_sql, sql_f)
                    
    for row in results:
        message = dict(zip(["column1","column2", "column3"], row)) 
        res.append(message) ```

#### Stack trace
```
    Traceback (most recent call last):
      File "/opt/venv/prunes/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/prunes/prunes/handlers/queries.py", line 61, in get
        message = await self.get_one(uuid, true_time, page, db, export, cache, org, None, None, None)
      File "/opt/prunes/prunes/system/queries.py", line 380, in get_one
        page, db, cache, export)
      File "/opt/prunes/prunes/system/queries.py", line 1345, in queries_search
        for row in results:
      File "/opt/venv/prunes/lib/python3.7/site-packages/google/cloud/spanner_v1/streamed.py", line 143, in __iter__
        self._consume_next()
      File "/opt/venv/prunes/lib/python3.7/site-packages/google/cloud/spanner_v1/streamed.py", line 131, in _consume_next
        values[0] = self._merge_chunk(values[0])
      File "/opt/venv/prunes/lib/python3.7/site-packages/google/cloud/spanner_v1/streamed.py", line 92, in _merge_chunk
        merged = _merge_by_type(self._pending_chunk, value, field.type)
      File "/opt/venv/prunes/lib/python3.7/site-packages/google/cloud/spanner_v1/streamed.py", line 305, in _merge_by_type
        return merger(lhs, rhs, type_)
      File "/opt/venv/prunes/lib/python3.7/site-packages/google/cloud/spanner_v1/streamed.py", line 266, in _merge_array
        merged = _merge_by_type(last, first, element_type)
      File "/opt/venv/prunes/lib/python3.7/site-packages/google/cloud/spanner_v1/streamed.py", line 305, in _merge_by_type
        return merger(lhs, rhs, type_)
      File "/opt/venv/prunes/lib/python3.7/site-packages/google/cloud/spanner_v1/streamed.py", line 280, in _merge_struct
        first = rhs.pop(0)
    IndexError: pop from empty list```

**Comment by larkee** [comment]
Same problem as seen [here](https://github.com/googleapis/google-cloud-python/issues/4164).
