### ISSUE TITLE
Speech to Text example code breaks on `from google.cloud.speech import enums`

### ISSUE THREAD

**Issue by cainejette** [googleapis/google-cloud-python#10173]
Pasting the example code of how to use the Python client library for speech to text from [here](https://cloud.google.com/speech-to-text/docs/reference/libraries) fails with an import error:

```
$ python google.py 
Traceback (most recent call last):
  File "google.py", line 3, in <module>
    from google.cloud import speech
  File "/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/google/cloud/speech.py", line 20, in <module>
    from google.cloud.speech_v1 import SpeechClient
  File "/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/google/cloud/speech_v1/__init__.py", line 17, in <module>
    from google.cloud.speech_v1.gapic import speech_client
  File "/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/google/cloud/speech_v1/gapic/speech_client.py", line 19, in <module>
    import pkg_resources
  File "/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3219, in _initialize_master_working_set
    for dist in working_set
  File "/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3219, in <genexpr>
    for dist in working_set
  File "/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2726, in activate
    declare_namespace(pkg)
  File "/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2252, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2185, in _handle_ns
    loader.load_module(packageName)
  File "/home/cainejette/src/whatsapp-bot/google.py", line 4, in <module>
    from google.cloud.speech import enums
ImportError: cannot import name 'enums' from 'google.cloud.speech' (/home/cainejette/src/whatsapp-bot/whatsapp-bot-venv/lib/python3.7/site-packages/google/cloud/speech.py)
```

### Environment details
Running Pop!_OS, python 3.7.3, google-cloud-speech 1.3.1

**Comment by busunkim96** [comment]
@cainejette I'm not able to reproduce the error. Could you provide a code snippet?
