### ISSUE TITLE
Storage: Failure to download gzip files

### ISSUE THREAD

**Issue by mcsimps2** [googleapis/google-cloud-python#10207]
Python Version: 3.7.3
OS: OSX 10.14 and Windows 7 (tested on multiple machines)
Google Cloud Storage Version: 1.25.0

**Description of Problem**:  The command `blob.download_to_filename` fails for several gz files I have.  For most files it succeeds, but once in a while, I get a decoding error when `raw_download=False` (the default setting).  Note these are valid gzip files, and the storage object has the `content-encoding: gzip` attribute set.  I can verify these are valid gzip files and the content encoding header is set because

**1.** Downloading them directly from the Storage Viewer website succeeds (and it decompresses them using [decompressive transcoding](https://cloud.google.com/storage/docs/transcoding)).  I can diff the contents to verify they are correct.
<img width="1098" alt="Screen Shot 2020-01-24 at 7 23 28 PM" src="https://user-images.githubusercontent.com/26491362/73112931-08884980-3edf-11ea-93a6-8b9d611a8ef9.png">
Screenshot of the metadata:
<img width="511" alt="Screen Shot 2020-01-24 at 7 21 05 PM" src="https://user-images.githubusercontent.com/26491362/73112940-1211b180-3edf-11ea-9cb7-5a1a00e35115.png">

**(2)** I can also download them with the `gsutil cp` command
<img width="1175" alt="Screen Shot 2020-01-24 at 7 21 31 PM" src="https://user-images.githubusercontent.com/26491362/73112905-e989b780-3ede-11ea-8c50-92734d115e16.png">
**(3)** I can download the raw gz file with `raw_download=True` and then decompress it myself with the Python `gzip` library.

However, the following error scenario happens when I call `blob.download_to_filename` with `raw_download=False` (the default setting):
**Error:** If I call `blob.download_to_filename(filename)`, I get the following error: 
```
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
```

This issue occurs on about 1 in every 500 GZ files I upload to / download from Google Cloud Storage using the google-cloud-storage library for Python.  I have 5-6 files that I can test on, but only a few I can distribute to other engineers to allow them to test with since they contain sensitive information.

**Another problem with gzipped files:** I've also had a lot of files with "content-encoding: gzip" stall during downloading, whether or not I was using `raw_download`.  At first, I thought it was hung, so I set network timeouts on the download (I can verify the timeouts were 61, 60) - but I never got a timeout exception.  I used a tool called "cports" to monitor my TCP connection, and it turns out data is coming in **extremely slow.**  In one instance, I had only received 5 MB over 30 minutes.  In comparison, when I download the file with `gsutil` or through the browser, it takes mere seconds.
![Screen Shot 2020-01-24 at 12 53 33 AM](https://user-images.githubusercontent.com/26491362/73113482-3458fe80-3ee2-11ea-9914-a97804f894e6.png)
![Screen Shot 2020-01-23 at 10 04 50 PM](https://user-images.githubusercontent.com/26491362/73113491-3e7afd00-3ee2-11ea-8124-efebce6a1fd8.png)
Above are screenshots that document that this file only downloaded 5 MB over the course of 41 minutes. (Notice the timedelta between the system clock and the mtime of the file, which is stuck at 0B of data written because no chunks have even been written as the default chunk size for streaming is 8 MB in this library.  Also note that this library does not modify the mtime of the file until after it has been fully written, so the mtime displayed is the time the file was also created.)  The IP address 64.233.185.128 is that of a Google Cloud Storage server, and 5,606,096 is the Bytes that the server has sent.  What's funny is that I ran the `gsutil cp` command alongside the hung `blob.download_to_filename` statement and the `gsutil` download finished almost instantly, while the `blob.download_to_filename` remained stalled (the irony being that `gsutil` is also written in Python, I believe).

For the content decode error, here's a full stack trace on my Mac (where I was debugging with really simple code):
```
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 757, in download_to_filename
    raw_download=raw_download,
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 717, in download_to_file
    transport, file_obj, download_url, headers, start, end, raw_download
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 660, in _do_download
    download.consume_next_chunk(transport)
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/google/resumable_media/requests/download.py", line 322, in consume_next_chunk
    retry_strategy=self._retry_strategy,
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/google/resumable_media/requests/_helpers.py", line 136, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/google/resumable_media/_helpers.py", line 150, in wait_and_retry
    response = func()
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/google/auth/transport/requests.py", line 287, in request
    **kwargs
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/mattsimpson/Documents/enso_helper/venv/lib/python3.7/site-packages/requests/models.py", line 755, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
```

Here's another stack trace on Windows (where I have a production app running):
```
INFO Executing request with timeout (60, 61) to GET https://storage.googleapis.com/download/storage/v1/b/enso-raw-studies-dev/o/ensodata%2F9F8CB009-E5FC-0D42-B24A-10EE5735F107%2F5e2a4889286826482a37ef22%2F00000142.EDF.gz?generation=1579831449004572&alt=media
ERROR: Failed to download file C:\Users\mattsimpson\Documents\Scored\CA_24569\a0000142

Traceback (most recent call last):
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\response.py", line 362, in _decode
    data = self._decoder.decompress(data)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\response.py", line 82, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\response.py", line 527, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\response.py", line 709, in read_chunked
    flush_decoder=False)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\response.py", line 367, in _decode
    "failed to decode it." % content_encoding, e)
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\enso_app\services\file_service\download\download_worker.py", line 84, in attempt_job
    self.process_job(*args, **kwargs)
  File "E:\enso_app\services\file_service\download\download_worker.py", line 231, in process_job
    raise e
  File "E:\enso_app\services\file_service\download\download_worker.py", line 214, in process_job
    pat, dn_dest, zipping=zipping
  File "E:\enso_app\services\file_service\download\download_worker.py", line 240, in download_study_from_cloud
    ignore_pattern="**/enso_backup/**",
  File "E:\enso_app\modules\remote_storage.py", line 354, in download_folder
    for blob in blobs
  File "E:\enso_app\modules\remote_storage.py", line 354, in <listcomp>
    for blob in blobs
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tenacity\__init__.py", line 311, in wrapped_f
    return self.call(f, *args, **kw)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tenacity\__init__.py", line 391, in call
    do = self.iter(retry_state=retry_state)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tenacity\__init__.py", line 350, in iter
    raise retry_exc.reraise()
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tenacity\__init__.py", line 168, in reraise
    raise self.last_attempt.result()
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tenacity\__init__.py", line 394, in call
    result = fn(*args, **kwargs)
  File "E:\enso_app\modules\remote_storage.py", line 269, in download_file
    blob.download_to_filename(abs_local_path)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\cloud\storage\blob.py", line 757, in download_to_filename
    raw_download=raw_download,
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\cloud\storage\blob.py", line 717, in download_to_file
    transport, file_obj, download_url, headers, start, end, raw_download
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\cloud\storage\blob.py", line 660, in _do_download
    download.consume_next_chunk(transport)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\resumable_media\requests\download.py", line 326, in consume_next_chunk
    retry_strategy=self._retry_strategy,
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\resumable_media\requests\_helpers.py", line 140, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\resumable_media\_helpers.py", line 153, in wait_and_retry
    response = func()
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\auth\transport\requests.py", line 301, in request
    **kwargs
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 686, in send
    r.content
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 755, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
Could not download study due to the current network conditions
Traceback (most recent call last):
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\response.py", line 362, in _decode
    data = self._decoder.decompress(data)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\response.py", line 82, in decompress
    ret += self._obj.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\response.py", line 527, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\response.py", line 709, in read_chunked
    flush_decoder=False)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\response.py", line 367, in _decode
    "failed to decode it." % content_encoding, e)
urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\enso_app\services\file_service\download\download_worker.py", line 55, in run
    self.attempt_job(pat, num_retries=1)
  File "E:\enso_app\services\file_service\download\download_worker.py", line 90, in attempt_job
    raise e
  File "E:\enso_app\services\file_service\download\download_worker.py", line 84, in attempt_job
    self.process_job(*args, **kwargs)
  File "E:\enso_app\services\file_service\download\download_worker.py", line 231, in process_job
    raise e
  File "E:\enso_app\services\file_service\download\download_worker.py", line 214, in process_job
    pat, dn_dest, zipping=zipping
  File "E:\enso_app\services\file_service\download\download_worker.py", line 240, in download_study_from_cloud
    ignore_pattern="**/enso_backup/**",
  File "E:\enso_app\modules\remote_storage.py", line 354, in download_folder
    for blob in blobs
  File "E:\enso_app\modules\remote_storage.py", line 354, in <listcomp>
    for blob in blobs
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tenacity\__init__.py", line 311, in wrapped_f
    return self.call(f, *args, **kw)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tenacity\__init__.py", line 391, in call
    do = self.iter(retry_state=retry_state)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tenacity\__init__.py", line 350, in iter
    raise retry_exc.reraise()
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tenacity\__init__.py", line 168, in reraise
    raise self.last_attempt.result()
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tenacity\__init__.py", line 394, in call
    result = fn(*args, **kwargs)
  File "E:\enso_app\modules\remote_storage.py", line 269, in download_file
    blob.download_to_filename(abs_local_path)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\cloud\storage\blob.py", line 757, in download_to_filename
    raw_download=raw_download,
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\cloud\storage\blob.py", line 717, in download_to_file
    transport, file_obj, download_url, headers, start, end, raw_download
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\cloud\storage\blob.py", line 660, in _do_download
    download.consume_next_chunk(transport)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\resumable_media\requests\download.py", line 326, in consume_next_chunk
    retry_strategy=self._retry_strategy,
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\resumable_media\requests\_helpers.py", line 140, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\resumable_media\_helpers.py", line 153, in wait_and_retry
    response = func()
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\auth\transport\requests.py", line 301, in request
    **kwargs
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 686, in send
    r.content
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\mattsimpson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 755, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
```

I can give the file above `00000142.EDF` to any contributor that wants to use it to test/debug. This file is consistently running into this problem, but I cannot post it here publicly.  I can send it to you directly though, if you want access, or see if I can get you access to my bucket.  Let me know how I can be of help to resolve this as quickly as possible.  This issue is currently affecting my production applications.

**Update:** I'm working around the DecodeError by using `raw_download=True` and decompressing locally with the Python gzip library, but the stalled downloads are still causing problems on many of the computers my application is running on - I haven't been able to find a good workaround for that.

**Comment by mcsimps2** [comment]
**Update:** I tried again this morning, and it looks like the problem is no longer occurring.  It must have been an issue on the API side of things - perhaps the response was incorrect somehow.  I'll close this issue for now and re-open it if it shows up again.
