### ISSUE TITLE
Forcekill Dev Server - Taskqueue - IndexError: list index out of range

### ISSUE THREAD

**Issue by speedplane** [googleapis/google-cloud-python#10370]
When you forcekill the google app engine dev server, you sometimes get the following stack trace.  A pretty low priority, but may indicate some other issues. This hasn't had any practical effect.

#### Steps to reproduce

  1. Run the google development server
  2. CTRL-C kill it

#### Stack trace
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\taskqueue\taskqueue_stub.py", line 2182, in MainLoop
    self._ProcessQueues()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\taskqueue\taskqueue_stub.py", line 2153, in _ProcessQueues
    queue.PostponeTask(task, _SecToUsec(now) + retry_usec)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\taskqueue\taskqueue_stub.py", line 1244, in _Inner
    ret = f(self, *args, **kwargs)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\taskqueue\taskqueue_stub.py", line 1678, in PostponeTask
    self._PostponeTaskNoAcquireLock(task, new_eta_usec)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\taskqueue\taskqueue_stub.py", line 1688, in _PostponeTaskNoAcquireLock
    self._sorted_by_eta, (eta, name, None), task)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\taskqueue\taskqueue_stub.py", line 1896, in _RemoveTaskFromIndex
    if index[pos][-1] is not task:
IndexError: list index out of range
```

Version information:
```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                   Components                                                  │
├──────────────────┬──────────────────────────────────────────────────────┬──────────────────────────┬──────────┤
│      Status      │                         Name                         │            ID            │   Size   │
├──────────────────┼──────────────────────────────────────────────────────┼──────────────────────────┼──────────┤
│ Update Available │ BigQuery Command Line Tool                           │ bq                       │  < 1 MiB │
│ Update Available │ Cloud SDK Core Libraries                             │ core                     │ 13.3 MiB │
│ Not Installed    │ App Engine Go Extensions                             │ app-engine-go            │  4.8 MiB │
│ Not Installed    │ Cloud Bigtable Command Line Tool                     │ cbt                      │  7.3 MiB │
│ Not Installed    │ Cloud Bigtable Emulator                              │ bigtable                 │  6.4 MiB │
│ Not Installed    │ Cloud Datalab Command Line Tool                      │ datalab                  │  < 1 MiB │
│ Not Installed    │ Cloud Firestore Emulator                             │ cloud-firestore-emulator │ 40.2 MiB │
│ Not Installed    │ Cloud Pub/Sub Emulator                               │ pubsub-emulator          │ 34.9 MiB │
│ Not Installed    │ Cloud SQL Proxy                                      │ cloud_sql_proxy          │  3.5 MiB │
│ Not Installed    │ Emulator Reverse Proxy                               │ emulator-reverse-proxy   │ 14.5 MiB │
│ Not Installed    │ Google Container Registry's Docker credential helper │ docker-credential-gcr    │  1.8 MiB │
│ Not Installed    │ Kind                                                 │ kind                     │  4.5 MiB │
│ Not Installed    │ Minikube                                             │ minikube                 │ 20.2 MiB │
│ Not Installed    │ Skaffold                                             │ skaffold                 │ 12.0 MiB │
│ Not Installed    │ gcloud Alpha Commands                                │ alpha                    │  < 1 MiB │
│ Not Installed    │ gcloud app Java Extensions                           │ app-engine-java          │ 62.2 MiB │
│ Not Installed    │ gcloud app PHP Extensions                            │ app-engine-php           │ 19.1 MiB │
│ Not Installed    │ kpt                                                  │ kpt                      │  9.9 MiB │
│ Not Installed    │ kubectl                                              │ kubectl                  │  < 1 MiB │
│ Installed        │ Cloud Datastore Emulator                             │ cloud-datastore-emulator │ 18.4 MiB │
│ Installed        │ Cloud Storage Command Line Tool                      │ gsutil                   │  3.6 MiB │
│ Installed        │ gcloud Beta Commands                                 │ beta                     │  < 1 MiB │
│ Installed        │ gcloud app Python Extensions                         │ app-engine-python        │  6.1 MiB │
│ Installed        │ gcloud app Python Extensions (Extra Libraries)       │ app-engine-python-extras │ 27.1 MiB │
└──────────────────┴──────────────────────────────────────────────────────┴──────────────────────────┴──────────┘
```

**Comment by busunkim96** [comment]
@speedplane Thanks for filing an issue! It looks like this is related to the gcloud SDK, which has a public issue tracker [here](https://issuetracker.google.com/issues?q=componentid:187143%20status:open&s=modified_time:desc). Would you mind filing an issue over there? I can also open one if you'd prefer that.

**Comment by speedplane** [comment]
Done: https://issuetracker.google.com/issues/149515817

Closing.
