### ISSUE TITLE
GCP Dataflow - DataflowRunner breaks down in serialization of application objects

### ISSUE THREAD

**Issue by sraktale** [googleapis/google-cloud-python#10473]
Hi,

My code works well with DirectRunner but with DataflowRunner I land up into issues on pickling application objects.

I tried with the fix

    import os
    os.environ['GOOGLE_CLOUD_DISABLE_GRPC'] = 'true'

but it does not work still.

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
  --> Dataflow

2. OS type and version
  --> MacOS Mojave 10.14.6

3. Python version and virtual environment information: `python --version`
Python 3.7.7

4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`

(gcp) 11217CTHLT-4:dataflow adminsraktale$ pip show apache-beam
Name: apache-beam
Version: 2.23.0
Summary: Apache Beam SDK for Python
Home-page: https://beam.apache.org
Author: Apache Software Foundation
Author-email: dev@beam.apache.org
License: Apache License, Version 2.0
Location: /Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages
Requires: numpy, typing-extensions, pymongo, python-dateutil, pytz, grpcio, pyarrow, protobuf, avro-python3, future, httplib2, fastavro, hdfs, mock, crcmod, dill, pydot, oauth2client
Required-by: 
(gcp) 11217CTHLT-4:dataflow adminsraktale$ 

Logs as under.

----------------------------------------------------------------------------------------------------------------

(gcp) 11217CTHLT-4:dataflow adminsraktale$ cat run_dataflow_runner 
export GOOGLE_APPLICATION_CREDENTIALS='/Users/adminsraktale/Projects/lgcp/cloudrisk-285916-3815e4fbe245.json'
python3 pricing_pipeline.py \
        --runner DataflowRunner  \
        --positions positions.csv \
        --scenarios scenarios.csv \
        --output prices.csv \
        --project cloudrisk-285916 \
        --region europe-west2 \
        --temp_location gs://cloudrisk-285916/tmp \
    --staging_location gs://cloudrisk-285916/staging \
    --save_main_session True
----------------------------------------------------------------------------------------------------------------

(gcp) 11217CTHLT-4:dataflow adminsraktale$ ./run_dataflow_runner 
Generated pricables : 819 
INFO:apache_beam.runners.portability.stager:Downloading source distribution of the SDK from PyPi
INFO:apache_beam.runners.portability.stager:Executing command: ['/Users/adminsraktale/anaconda3/envs/gcp/bin/python3', '-m', 'pip', 'download', '--dest', '/var/folders/kp/pyb94n8n7m131pv83bj8tzrh0000gt/T/tmpdxg2_ijp', 'apache-beam==2.23.0', '--no-deps', '--no-binary', ':all:']
INFO:apache_beam.runners.portability.stager:Staging SDK sources from PyPI: dataflow_python_sdk.tar
INFO:apache_beam.runners.portability.stager:Downloading binary distribution of the SDK from PyPi
INFO:apache_beam.runners.portability.stager:Executing command: ['/Users/adminsraktale/anaconda3/envs/gcp/bin/python3', '-m', 'pip', 'download', '--dest', '/var/folders/kp/pyb94n8n7m131pv83bj8tzrh0000gt/T/tmpdxg2_ijp', 'apache-beam==2.23.0', '--no-deps', '--only-binary', ':all:', '--python-version', '37', '--implementation', 'cp', '--abi', 'cp37m', '--platform', 'manylinux1_x86_64']
INFO:apache_beam.runners.portability.stager:Staging binary distribution of the SDK from PyPI: apache_beam-2.23.0-cp37-cp37m-manylinux1_x86_64.whl
WARNING:root:Make sure that locally built Python SDK docker image has Python 3.7 interpreter.
INFO:root:Using Python SDK docker image: apache/beam_python3.7_sdk:2.23.0. If the image is not available at local, we will try to pull from hub.docker.com
Traceback (most recent call last):
  File "pricing_pipeline.py", line 202, in <module>
    run_new()
  File "pricing_pipeline.py", line 158, in run_new
    result = p.run()
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/pipeline.py", line 521, in run
    allow_proto_holders=True).run(False)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/pipeline.py", line 534, in run
    return self.runner.run_pipeline(self, self._options)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 509, in run_pipeline
    pipeline.replace_all(DataflowRunner._NON_PORTABLE_PTRANSFORM_OVERRIDES)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/pipeline.py", line 492, in replace_all
    self._replace(override)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/pipeline.py", line 387, in _replace
    self.visit(TransformUpdater(self))
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/pipeline.py", line 580, in visit
    self._root_transform().visit(visitor, self, visited)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/pipeline.py", line 1084, in visit
    part.visit(visitor, pipeline, visited)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/pipeline.py", line 1082, in visit
    visitor.enter_composite_transform(self)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/pipeline.py", line 381, in enter_composite_transform
    self._replace_if_needed(transform_node)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/pipeline.py", line 336, in _replace_if_needed
    new_output = replacement_transform.expand(input_node)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/runners/dataflow/ptransform_overrides.py", line 52, in expand
    return pbegin | ptransform.as_read()
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/transforms/core.py", line 2639, in as_read
    source = self._create_source_from_iterable(self.values, coder)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/transforms/core.py", line 2648, in _create_source_from_iterable
    return Create._create_source(list(map(coder.encode, values)), coder)
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/coders/coders.py", line 463, in encode
    return self.get_impl().encode(value)
  File "apache_beam/coders/coder_impl.py", line 216, in apache_beam.coders.coder_impl.StreamCoderImpl.encode
  File "apache_beam/coders/coder_impl.py", line 219, in apache_beam.coders.coder_impl.StreamCoderImpl.encode
  File "apache_beam/coders/coder_impl.py", line 442, in apache_beam.coders.coder_impl.FastPrimitivesCoderImpl.encode_to_stream
  File "apache_beam/coders/coder_impl.py", line 253, in apache_beam.coders.coder_impl.CallbackCoderImpl.encode_to_stream
  File "/Users/adminsraktale/anaconda3/envs/gcp/lib/python3.7/site-packages/apache_beam/coders/coders.py", line 711, in <lambda>
    lambda x: dumps(x, HIGHEST_PROTOCOL), pickle.loads)
_pickle.PicklingError: Can't pickle <class '__main__.Pricable'>: it's not the same object as __main__.Pricable
(gcp) 11217CTHLT-4:dataflow adminsraktale$ 

----------------------------------------------------------------------------------------------------------------

Hope this is sufficient information or please let me know how I can add more details.

Regards
Swapnil

**Comment by davidcavazos** [comment]
How does the `main.Pricable` type look like? It looks like it can't pickle some of its contents.

**Comment by meredithslota** [comment]
I'm going to close this since we haven't gotten a response after @davidcavazos responded initially. Hopefully that response helped! :)
