### ISSUE TITLE
Error processing line 3 google_cloud_storage-1.30.0-py3.8-nspkg.pth:

### ISSUE THREAD

**Issue by danieldhz** [googleapis/google-cloud-python#10477]
Hi There!

Upon installation of google cloud libs, I got:
```
Error processing line 3 of C:\google_cloud_storage-1.30.0-py3.8-nspkg.pth:
Remainder of file ignored
Error processing line 3 of C:\StartUp\IdeaStage\Tier 1\Alexa smart timer\AlexaLibs\lib\site-packages\google_cloud_storage-1.30.0-py3.8-nspkg.pth:
  Traceback (most recent call last):
    File "c:\python38\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 553, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader
```
I tried deleting googleapis_common_protos per [SO](https://stackoverflow.com/questions/56935698/attributeerror-nonetype-object-has-no-attribute-loader) recommendation. However, it didn't work.

**Comment by HemangChothani** [comment]
Closing this issue as found in 'python-storage' repo.
