### ISSUE TITLE
gcloud beta compute ssh fails with AttributeError

### ISSUE THREAD

**Issue by arindamchoudhury** [googleapis/google-cloud-python#10508]
$ gcloud beta compute --project "xxxxxx-xxx" ssh --zone "europe-west1-d" "monitor-bastion"
Traceback (most recent call last):
  File "/usr/lib64/google-cloud-sdk/lib/gcloud.py", line 104, in <module>
    main()
  File "/usr/lib64/google-cloud-sdk/lib/gcloud.py", line 62, in main
    from googlecloudsdk.core.util import encoding
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/__init__.py", line 23, in <module>
    from googlecloudsdk.core.util import importing
  File "/usr/lib64/google-cloud-sdk/lib/googlecloudsdk/core/util/importing.py", line 23, in <module>
    import imp
  File "/usr/lib64/python3.9/imp.py", line 23, in <module>
    from importlib import util
  File "/usr/lib64/python3.9/importlib/util.py", line 2, in <module>
    from . import abc
  File "/usr/lib64/python3.9/importlib/abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "/usr/lib64/python3.9/typing.py", line 26, in <module>
    import re as stdlib_re  # Avoid confusion with the re we export.
  File "/usr/lib64/python3.9/re.py", line 124, in <module>
    import enum
  File "/usr/lib64/google-cloud-sdk/lib/third_party/enum/__init__.py", line 26, in <module>
    spec = importlib.util.find_spec('enum')
AttributeError: module 'importlib' has no attribute 'util'

**Comment by busunkim96** [comment]
Hi @arindamchoudhury,

This issue tracker is for the google-cloud-* Python libraries published on PyPI. For issues with gcloud, please use one of the support channels listed on this page:

https://cloud.google.com/sdk/docs/getting-support

I believe the issue is that gcloud is not yet compatible with 3.9. Please follow https://b.corp.google.com/issues/170125513 for updates.
