### ISSUE TITLE
bigtable emulator and google-cloud-happybase

### ISSUE THREAD

**Issue by chapmanjacobd** [googleapis/google-cloud-python#10515]
#### Environment details

  - OS type and version: Fedora 33
  - Python version: 3.7
  - pip version: 20.2.2
  - `google-cloud-bigtable` version: 1.6.1

#### Steps to reproduce

  1. Start bigtable emulator
  2. 🌳 env BIGTABLE_EMULATOR_HOST=localhost:8086 python src/tasks/get_pixel.py 

#### Code example

```python
    client = Client(project=PROJECT_ID, admin=True)
    instance = client.instance(INSTANCE_ID, LOCATION_ID)
    instance.reload()
    connection = happytable.Connection(instance=instance)
...
        batch = happytable.Batch(bigtable_table, transaction=True)
...
            batch.put(key, columns)
```

#### Stack trace
```nice
Traceback (most recent call last):
  File "/home/xk/.local/share/virtualenvs/data-pipelines-7qOG6D03/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/xk/.local/share/virtualenvs/data-pipelines-7qOG6D03/lib64/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/xk/.local/share/virtualenvs/data-pipelines-7qOG6D03/lib64/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "unimplemented feature"
        debug_error_string = "{"created":"@1607140695.045540422","description":"Error received from peer ipv4:127.0.0.1:8086","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"unimplemented feature","grpc_status":12}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/tasks/get_pixel.py", line 127, in <module>
    pipePixelsToBigTable(1, 1, "tests/data/wealth_roc_value_raster.tif")
  File "src/tasks/get_pixel.py", line 25, in pipePixelsToBigTable
    instance.reload()
  File "/home/xk/.local/share/virtualenvs/data-pipelines-7qOG6D03/lib/python3.7/site-packages/google/cloud/bigtable/instance.py", line 360, in reload
    instance_pb = self._client.instance_admin_client.get_instance(self.name)
  File "/home/xk/.local/share/virtualenvs/data-pipelines-7qOG6D03/lib/python3.7/site-packages/google/cloud/bigtable_admin_v2/gapic/bigtable_instance_admin_client.py", line 442, in get_instance
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/home/xk/.local/share/virtualenvs/data-pipelines-7qOG6D03/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/xk/.local/share/virtualenvs/data-pipelines-7qOG6D03/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/home/xk/.local/share/virtualenvs/data-pipelines-7qOG6D03/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/home/xk/.local/share/virtualenvs/data-pipelines-7qOG6D03/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/xk/.local/share/virtualenvs/data-pipelines-7qOG6D03/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.MethodNotImplemented: 501 unimplemented feature
```

**Comment by chapmanjacobd** [comment]
oh. it's just instance.reload()

[what](https://www.youtube.com/watch?v=5IsSpAOD6K8) does that even do ???

**Comment by chapmanjacobd** [comment]
But I do have an issue here:


```
Unpacking google-cloud-sdk-bigtable-emulator (319.0.0-0) ...
Setting up google-cloud-sdk-bigtable-emulator (319.0.0-0) ...
Processing triggers for google-cloud-sdk (319.0.0-0) ...
Executing: /usr/lib/google-cloud-sdk/platform/bigtable-emulator/cbtemulator --host=localhost --port=8086
[bigtable] Cloud Bigtable emulator running on 127.0.0.1:8086
Traceback (most recent call last):
  File "src/tasks/get_pixel.py", line 129, in <module>
    pipePixelsToBigTable(1, 1, "tests/data/wealth_roc_value_raster.tif")
  File "src/tasks/get_pixel.py", line 23, in pipePixelsToBigTable
    client = Client(project=PROJECT_ID, admin=True)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/cloud/bigtable/client.py", line 180, in __init__
    client_options=client_options,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/cloud/client.py", line 250, in __init__
    Client.__init__(self, credentials=credentials, client_options=client_options, _http=_http)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/cloud/client.py", line 151, in __init__
    credentials, _ = google.auth.default(scopes=scopes)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/google/auth/_default.py", line 356, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see cloud.google.com/docs/authentication/getting-started
```

related to ? 
https://github.com/googleapis/python-datastore/issues/11#issuecomment-468336989
https://github.com/googleapis/java-bigtable-hbase/issues/1070

**Comment by chapmanjacobd** [comment]
I guess this is probably the wrong repo for the second issue
