### ISSUE TITLE
can't import monitoring_v3 in python 3.9.6

### ISSUE THREAD

**Issue by alexisbenichoux** [googleapis/google-cloud-python#10568]
A nasty error happens with conda-forge channel, the build pulled latest python version (3.9.6) and 

google-api-core               1.31.0             
google-auth                   1.33.0             
google-cloud-bigquery         2.21.0             
google-cloud-bigquery-storage 2.2.1              
google-cloud-bigtable         2.3.1              
google-cloud-core             1.7.1              
google-cloud-monitoring       2.4.0              
google-crc32c                 1.1.2              
google-resumable-media        1.3.1              
googleapis-common-protos      1.53.0             
grpc-google-iam-v1            0.12.3      

Then the import throws

>>from google.cloud import monitoring_v3

Traceback (most recent call last):
    from google.cloud import monitoring_v3
  File "/opt/conda/envs/env/lib/python3.9/site-packages/google/cloud/monitoring_v3/__init__.py", line 17, in <module>
    from .services.alert_policy_service import AlertPolicyServiceClient
  File "/opt/conda/envs/env/lib/python3.9/site-packages/google/cloud/monitoring_v3/services/alert_policy_service/__init__.py", line 16, in <module>
    from .client import AlertPolicyServiceClient
  File "/opt/conda/envs/env/lib/python3.9/site-packages/google/cloud/monitoring_v3/services/alert_policy_service/client.py", line 33, in <module>
    from google.cloud.monitoring_v3.services.alert_policy_service import pagers
  File "/opt/conda/envs/env/lib/python3.9/site-packages/google/cloud/monitoring_v3/services/alert_policy_service/pagers.py", line 27, in <module>
    from google.cloud.monitoring_v3.types import alert
  File "/opt/conda/envs/env/lib/python3.9/site-packages/google/cloud/monitoring_v3/types/__init__.py", line 16, in <module>
    from .alert import AlertPolicy
  File "/opt/conda/envs/env/lib/python3.9/site-packages/google/cloud/monitoring_v3/types/alert.py", line 18, in <module>
    from google.cloud.monitoring_v3.types import common
  File "/opt/conda/envs/env/lib/python3.9/site-packages/google/cloud/monitoring_v3/types/common.py", line 48, in <module>
    class ServiceTier(proto.Enum):
  File "/opt/conda/envs/env/lib/python3.9/site-packages/proto/enums.py", line 72, in __new__
    cls = super().__new__(mcls, name, bases, attrs)
  File "/opt/conda/envs/env/lib/python3.9/enum.py", line 288, in __new__
    enum_member = __new__(enum_class, *args)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

It's easy to fix with python=3.7.10 if anyone wonders.

**Comment by busunkim96** [comment]
Hi,

Could you also share what version of `proto-plus` is installed?
