### ISSUE TITLE
PubSub Stream Pull is waiting idle

### ISSUE THREAD

**Issue by sabuhigr** [googleapis/google-cloud-python#10640]
Hi all, pull streaming after 20 working hour, error occured and no any stream came to us.Thats environment:

google-api-core>=1.29.0
google-cloud-pubsub==2.1.0
google-auth==1.25.0
google-api-python-client==1.12.3

Code is same Google pub/sub bot example in Github:  https://github.com/googleworkspace/hangouts-chat-samples/blob/master/python/pub-sub-bot/bot.py

E2022-04-24 18:17:53,276] Exception in callback <bound method ResumableBidiRpc._on_call_done of <google.api_core.bidi.ResumableBidiRpc object at 0x7f377df72b50>>: AttributeError("'NoneType' object has no attribute 'from_call'")
I2022-04-24 18:17:53,277] Observed non-terminating stream error 'NoneType' object has no attribute 'from_call'
I2022-04-24 18:17:53,277] Observed non-recoverable stream error 'NoneType' object has no attribute 'from_call'
I2022-04-24 18:17:53,277] RPC termination has signaled streaming pull manager shutdown.
E2022-04-24 18:17:53,278] Thread-ConsumeBidirectionalStream caught unexpected exception 'NoneType' object has no attribute 'from_call' and will exit.
Traceback (most recent call last):
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 97, in __next__
    return next(self._wrapped)
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Received RST_STREAM with error code 2"
        debug_error_string = "{"created":"@1650813473.276210904","description":"Error received from peer ipv4:216.58.206.170:443","file":"src/core/lib/surface/call.cc","file_line":903,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 655, in _thread_main
    response = self._bidi_rpc.recv()
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 561, in recv
    return self._recoverable(self._recv)
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 520, in _recoverable
    raise exc
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 504, in _recoverable
    return method(*args, **kwargs)
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/google/api_core/bidi.py", line 558, in _recv
    return next(call)
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 100, in __next__
    raise exceptions.from_grpc_error(exc) from exc
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/google/api_core/exceptions.py", line 603, in from_grpc_error
    details, err_info = _parse_grpc_error_details(rpc_exc)
  File "/home/sabuhigurbani/.local/lib/python3.8/site-packages/google/api_core/exceptions.py", line 553, in _parse_grpc_error_details
    status = rpc_status.from_call(rpc_exc)
AttributeError: 'NoneType' object has no attribute 'from_call'
I2022-04-24 18:17:53,281] Thread-ConsumeBidirectionalStream exiting
I2022-04-24 18:17:53,281] Thread-LeaseMaintainer exiting.
I2022-04-24 18:17:53,282] Thread-Heartbeater exiting.

**Comment by acocuzzo** [comment]
HI @sabuhigr 

There was a bug which could result in NoneType errors for streaming pull. Please update to latest version of google-cloud-pubsub (v2.12.0), as well as to the latest version of google-api-core, google-auth, and google-api-python-client.

Please let me know if you are still experiencing these errors after updating.

**Comment by sabuhigr** [comment]
Sorry for late, after upgrade client libraries, its solved.
