### ISSUE TITLE
access_secret_version Getting StatusCode.DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by pfitzsi1** [googleapis/google-cloud-python#11447]
Testing a first generation Pub/Sub triggered Google Cloud Function trying to get a Google Secret.

Within the function code the logging shows the following series of the same Python module DEBUG statements multiple times as it progresses through the function code:

   (1) DEBUG - _get_explicit_environ_credentials @ line 257 - Checking None for explicit credentials as part of auth process...
   (2) DEBUG - _get_gcloud_sdk_credentials @ line 230 - Checking Cloud SDK credentials as part of auth process...
   (3) DEBUG - _get_gcloud_sdk_credentials @ line 236 - Cloud SDK credentials not found on disk; not using them
   (4) DEBUG - __call__ @ line 104 - Making request: GET http://169.254.169.254/
   (5) DEBUG - __call__ @ line 104 - Making request: GET http://metadata.google.internal/computeMetadata/v1/project/project-id

Added in the following statement to see if the default credentials are properly obtained:

   credentials, project = google.auth.default()

Displayed the credentials and project variables afterwards and yes they are OK.
This statement of course also generated the above 5 DEBUG statements in the log.

But, later in the code when it gets to the access_secret_version statement the log shows the above 5 DEBUG statements again and then a 1 minute gap followed by the StatusCode.DEADLINE_EXCEEDED error.

There does not seem to be a way to set a timeout for access_secret_version but it appears to have a 1 minute timeout.
The total time on the function execution to the error is 60109 ms.
The function is deployed with --timeout=540s.

Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.DEADLINE_EXCEEDED

**Comment by pfitzsi1** [comment]
I decided to add more logging and examine the returned DEFAULT CREDENTIALS.
    valid = credentials.valid is returning False
Apparently this does not seem to matter until it gets to the access_secret_version but not sure if that is what is causing the 1 minute delay and then the error, the TRACEBACK log messages doesn't mention anything about credentials and I would expect some permission error if that is the problem.

I have made sure that the SA attached to the Function plus the Functions runtime SA plus the App Engine SA all have all the roles needed.

**Comment by pfitzsi1** [comment]
Since there is a service account (SA) attached to the Function, not sure why it goes through that flow trying to obtain default credentials over and over again (show up multiple times in the log), when it should be using the attached SA as the credentials. I only added in the  **credentials, project = google.auth.default()** so I could examine and log things for debugging. That statement of course issued the 5 DEBUG statements in the log yet again.

**Comment by pfitzsi1** [comment]
May be on the wrong track here looking at the default credentials. The TRACEBACK log messages only refer to RPC issues...

**Comment by pfitzsi1** [comment]
This issue can be closed.

**Comment by pfitzsi1** [comment]
Closed.
