### ISSUE TITLE
Creating audience asks for an Id? 

### ISSUE THREAD

**Issue by benAnthropics** [googleapis/google-cloud-python#11829]
- OS type and version: Windows
  - Python version: 3.9.1
  - pip version: 20.2.3
  - `google-analytics-data` version: 0.17.1

Run the below code.  I've hidden my property Id.

It seems to be asking for an audience Id when trying create one.  As it's not created yet I don't know the Id

#### Code example
```
 client = data_v1alpha.AlphaAnalyticsDataClient()

    dim = data_v1alpha.AudienceDimension()
    dim.dimension_name = "deviceId"

    audience_list = data_v1alpha.AudienceList()
    audience_list.audience = "properties/pId/audiences/2"
    audience_list.dimensions= [dim]

    request = data_v1alpha.CreateAudienceListRequest(
        parent="properties/pId",
        audience_list=audience_list,
    )

    # Make the request
    operation = client.create_audience_list(request=request)

    # Handle the response
    response = operation.result()

    print(response)
```

#### Stack trace
```
Traceback (most recent call last):
  File "D:\Pytesting\newTest.py", line 101, in <module>
    sample_create_audience_list()
  File "D:\Pytesting\newTest.py", line 78, in sample_create_audience_list
    operation = client.create_audience_list(request=request)
  File "D:\Pytesting\venv\lib\site-packages\google\analytics\data_v1alpha\services\alpha_analytics_data\client.py", line 678, in create_audience_list
    response = rpc(
  File "D:\Pytesting\venv\lib\site-packages\google\api_core\gapic_v1\method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "D:\Pytesting\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 77, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Audience ID 247898765 not found. Deleted audiences are not eligible for export. To learn how to determine the Audience IDs for your GA4 property, see https://developers.google.com/analytics/devguides/reporting/data/v1/audience-list-basics#request_the_audience_list_creation

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by benAnthropics** [comment]
Thanks for the response. I didn't realise the difference between Audiences and AudienceLists.  I get it now, and the Python library works as expected.
