### ISSUE TITLE
request argument parsing issue

### ISSUE THREAD

**Issue by slavanorm** [googleapis/google-cloud-python#11830]
hello. 
i request in report a metric, which has name "conversions:click_play". 

#### Steps to reproduce
  1. set up some metric as conversion
  2. request the conversion through api

#### Code example
```
from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import (
    DateRange,
    Dimension,
    Metric,
    RunReportRequest,
)


property = "X"

def abspath(
    f,
    *args):
    return os.path.join(os.path.dirname(f), *args)

client = BetaAnalyticsDataClient.from_service_account_json(
    abspath(__file__, "../tokens/ga.json")
)

def run(
    dimensions,
    metrics,
    start_date='yesterday',
    end_date='yesterday',
):
    kwargs = dict(
        property=f"properties/{property}",
        dimensions=[
            gp.Dimension(name=e)
            for e in dimensions
        ],
        metrics=[
            gp.Metric(name=e)
            for e in metrics
        ],
        date_ranges=[
            gp.DateRange(start_date=start_date, end_date=end_date)],
    )
   r = gp.RunReportRequest(**kwargs)
   r = client.run_report(r)



report_settings = {
        "metrics":[            "conversions:load_lobby",        ],
        "dimensions":[            "date",        ],
    }

run(**report_settings)

```

#### Stack trace
```
/usr/bin/python3 /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 64789 --file /Users/v0/Py/sidus/airflow-dag/main_ga_visitors.py
Unable to load extension pydevd_plugins.extensions.types.pydevd_plugin_pandas_types
Connected to pydev debugger (build 223.8617.48)
Traceback (most recent call last):
File "/Library/Python/3.8/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
return callable_(*args, **kwargs)
File "/Library/Python/3.8/site-packages/grpc/_channel.py", line 1030, in call
return _end_unary_response_blocking(state, call, False, None)
File "/Library/Python/3.8/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
raise _InactiveRpcError(state) # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "Metric names must only contain letters, numbers, or _. Received a metric name = conversions[click_play]"
debug_error_string = "UNKNOWN:Error received from peer ipv4:142.251.36.42:443 {created_time:"2023-08-21T11:50:19.239056+04:00", grpc_status:3, grpc_message:"Metric names must only contain letters, numbers, or _. Received a metric name = conversions[click_play]"}"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/Library/Python/3.8/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Metric names must only contain letters, numbers, or _. Received a metric name = conversions[click_play.sidusheroes.com]
python-BaseException
```

**Comment by parthea** [comment]
I'm going to close this issue as stale due to no recent activity.
