### ISSUE TITLE
Not able to use "us-central1" with Chirp

### ISSUE THREAD

**Issue by sureshpalemoni** [googleapis/google-cloud-python#11867]
Unable to use Chirp model with "us-central1" as the **BatchRecognizeRequest** is giving error. 

#### Environment details

  - OS type and version:
  - Python version: 3.10
  - pip version: gcloud functions pip
  - `google-cloud-speech` version: `pip show google-cloud-speech`

#### Steps to reproduce

  1. Running the code on google cloud functions
  2. Use Chirp Model and location in recognizer as "us-central1"
  3. Name="projects/project-0/locations/us-central1/recognizers/_"

#### Code example

```python

    from google.cloud.speech_v2 import SpeechClient
    from google.cloud.speech_v2.types import cloud_speech
    
    client = SpeechClient() 

    --- other code --- 
    
    name = "projects/project-0/locations/us-central1/recognizers/_"

    request = cloud_speech.BatchRecognizeRequest(
        recognizer=name, config=config, files=files, recognition_output_config=output_config
    )

    operation = client.batch_recognize(request=request)
    response = operation.result()
```

#### Stack trace
```
textPayload: "Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/functions_framework/__init__.py", line 174, in view_func
    function(event)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/functions_framework/__init__.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/workspace/main.py", line 63, in speech2text
    response = speech_to_text(ffname, uid)
  File "/workspace/main.py", line 47, in speech_to_text
    operation = client.batch_recognize(request=request)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/cloud/speech_v2/services/speech/client.py", line 1808, in batch_recognize
    response = rpc(
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Expected resource location to be global, but found us-central1 in resource name."
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by atulyaatul1999** [comment]
@parthea I am getting the same error, is there any solution available?

**Comment by parthea** [comment]
A regional specific endpoint is required for Speech V2. See the migration guide [here](https://cloud.google.com/speech-to-text/v2/docs/migration). See the code sample [here](https://cloud.google.com/speech-to-text/v2/docs/chirp-model#perform_synchronous_speech_recognition_with_chirp). See the comment `Instantiates a client to a regionalized Speech endpoint`

Instead of 

```
    client = SpeechClient() 
```
use the following for a regionalized client such as `us-central1`

```
    client = SpeechClient(
        client_options=ClientOptions(
            api_endpoint="us-central1-speech.googleapis.com",
        )
    )
```

I'm going to close this issue as there is a working code sample in https://cloud.google.com/speech-to-text/v2/docs/chirp-model#perform_synchronous_speech_recognition_with_chirp. Please feel free to open a new issue if you still encounter the issue.

**Comment by Abhishek-cmd13** [comment]
NameError: name 'ClientOptions' is not defined
