### ISSUE TITLE
Cloud Functions: test_iam_permissions returns 501

### ISSUE THREAD

**Issue by WebbinRoot** [googleapis/google-cloud-python#12290]
I've been trying to call test_iam_permissions per the documentation here: https://cloud.google.com/python/docs/reference/cloudfunctions/latest/google.cloud.functions_v2.services.function_service.FunctionServiceClient#google_cloud_functions_v2_services_function_service_FunctionServiceClient_test_iam_permissions . It doesn't seem like the method is getting recognized though and I'm trying to figure out if the function actually exists or the documentation is not up-to-date.

I think I'm doing all the steps correctly, but i keep getting back 
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Operation is not implemented, or supported, or enabled."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:<IP>:443 {created_time:"2024-02-07T00:30:23.421562769-05:00", grpc_status:12, grpc_message:"Operation is not implemented, or supported, or enabled."}"
>
```
I tried a simple example in a python venv to ensure it was no library issues. Commands below
```
└─$ pip3 install google-cloud-functions
Collecting google-cloud-functions
  Obtaining dependency information for google-cloud-functions from https://files.pythonhosted.org/packages/69/81/865a6e47d328bf24be3fad7aa5b1d4307432c7a08073988fc2f93fe01e8a/google_cloud_functions-1.16.0-py2.py3-none-any.whl.metadata
[Condensed]
>>> import google.auth
>>> credentials, project_id = google.auth.default()
>>> from google.cloud import functions_v2
>>> client = functions_v2.FunctionServiceClient()
>>> from google.iam.v1 import iam_policy_pb2 
>>> request = iam_policy_pb2.TestIamPermissionsRequest(resource="projects/[project-name-redacted]/locations/us-central1/functions/[function-name-redacted]",permissions=["cloudfunctions.functions.invoke"])
>>> authenticated_permissions = client.test_iam_permissions(request=request)
Traceback (most recent call last):
  File "/home/kali/Desktop/test/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 79, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/test/lib/python3.11/site-packages/grpc/_channel.py", line 1160, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/test/lib/python3.11/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Operation is not implemented, or supported, or enabled."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:<IP>:443 {created_time:"2024-02-07T00:45:02.02731947-05:00", grpc_status:12, grpc_message:"Operation is not implemented, or supported, or enabled."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kali/Desktop/test/lib/python3.11/site-packages/google/cloud/functions_v2/services/function_service/client.py", line 2237, in test_iam_permissions
    response = rpc(
               ^^^^
  File "/home/kali/Desktop/test/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/test/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 81, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.MethodNotImplemented: 501 Operation is not implemented, or supported, or enabled.
```

**Comment by WebbinRoot** [comment]
Just following up on this item, if there has been any movement on the issue?

**Comment by WebbinRoot** [comment]
It looks like the v1 function client works, but not the v2

```
>>> import google.auth
>>> credentials, project_id = google.auth.default()
>>> from google.cloud import functions_v1
>>> from google.iam.v1 import iam_policy_pb2
>>> request = iam_policy_pb2.TestIamPermissionsRequest(resource="projects/[projrect-name]/locations/us-central1/functions/[function_name]",permissions=["cloudfunctions.functions.invoke"])
>>> client = functions_v1.CloudFunctionsServiceClient()
>>> response = client.test_iam_permissions(request=request)
>>> print(response)
permissions: "cloudfunctions.functions.invoke"
>>> from google.cloud import functions_v2
>>> client = functions_v2.FunctionServiceClient()
>>> response = client.test_iam_permissions(request=request)
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Operation is not implemented, or supported, or enabled."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:<IP>:443 {created_time:"2024-02-26T22:37:08.851340941-05:00", grpc_status:12, grpc_message:"Operation is not implemented, or supported, or enabled."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kali/.local/lib/python3.11/site-packages/google/cloud/functions_v2/services/function_service/client.py", line 1979, in test_iam_permissions
    response = rpc(
               ^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 77, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.MethodNotImplemented: 501 Operation is not implemented, or supported, or enabled.

```

**Comment by parthea** [comment]
Hi @WebbinRoot

Thanks for providing a code sample and for the detailed error report. I was able to re-create the issue with using `test_iam_permissions` with `functions_v2`.

My findings so far:

- The `Try this method` interface on [this page](https://cloud.google.com/functions/docs/reference/rest/v2/projects.locations.functions/testIamPermissions) works, although this is using REST instead of gRPC
-  `test_iam_permissions` works if I set the `transport` argument of `FunctionServiceClient` to `"rest"`.
 
```
from google.cloud import functions_v2
from google.iam.v1 import iam_policy_pb2 

client = functions_v2.FunctionServiceClient(transport="rest")
request = iam_policy_pb2.TestIamPermissionsRequest(resource="projects/<project>/locations/<location>/functions/<function>",permissions=["cloudfunctions.functions.invoke"])
authenticated_permissions = client.test_iam_permissions(request=request)
print(authenticated_permissions)
...
>>permissions: "cloudfunctions.functions.invoke"
```

**Comment by parthea** [comment]
Googlers see b/290325518

**Comment by parthea** [comment]
@WebbinRoot,

The issue appears to be with the API rather than the python client library based on an internal error report (b/290325518). If you'd like to receive updates on the issue directly from the Cloud Functions API team, please file an issue public issue tracker for the Cloud Functions API using the link below.

https://issuetracker.google.com/issues/new?component=187195&template=0

**Comment by parthea** [comment]
Thanks for filing a bug in the public issue tracker, @WebbinRoot. Please follow progress on this issue via https://issuetracker.google.com/issues/327245893. I'm going to close this issue as it is a problem with the API rather than the client library code.
