### ISSUE TITLE
Cannot import client libraries under Python 3.13

### ISSUE THREAD

**Issue by jvstme** [googleapis/google-cloud-python#13187]
### Determine this is the right repository

- [X] I determined this is the correct repository in which to report this bug.

### Summary of the issue

Importing Google Cloud client libraries under Python 3.13 leads to an exception. The example below uses google-cloud-billing, but the same behavior can be seen with google-cloud-compute, google-cloud-tpu, and probably other libraries as well.

### API client name and version

google-cloud-billing v1.13.6

### Reproduction steps: code

```python
import google.cloud.billing_v1
```

### Reproduction steps: actual results

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import google.cloud.billing_v1
  File "/usr/local/lib/python3.13/site-packages/google/cloud/billing_v1/__init__.py", line 21, in <module>
    from .services.cloud_billing import CloudBillingAsyncClient, CloudBillingClient
  File "/usr/local/lib/python3.13/site-packages/google/cloud/billing_v1/services/cloud_billing/__init__.py", line 16, in <module>
    from .async_client import CloudBillingAsyncClient
  File "/usr/local/lib/python3.13/site-packages/google/cloud/billing_v1/services/cloud_billing/async_client.py", line 49, in <module>
    from google.cloud.billing_v1.services.cloud_billing import pagers
  File "/usr/local/lib/python3.13/site-packages/google/cloud/billing_v1/services/cloud_billing/pagers.py", line 41, in <module>
    from google.cloud.billing_v1.types import cloud_billing
  File "/usr/local/lib/python3.13/site-packages/google/cloud/billing_v1/types/__init__.py", line 30, in <module>
    from .cloud_catalog import (
    ...<11 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/google/cloud/billing_v1/types/cloud_catalog.py", line 574, in <module>
    class ListSkusResponse(proto.Message):
    ...<24 lines>...
        )
  File "/usr/local/lib/python3.13/site-packages/proto/message.py", line 279, in __new__
    file_info.generate_file_pb(new_class=cls, fallback_salt=full_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/proto/_file_info.py", line 104, in generate_file_pb
    pool.Add(self.descriptor)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 'google.cloud.billing.v1.AggregationInfo.__firstlineno__'
```

### Reproduction steps: expected results

Successful import

### OS & version + platform

python:3.13 Docker image

### Python environment

Python 3.13

### Python dependencies

```
Package                  Version
------------------------ ---------
cachetools               5.5.0
certifi                  2024.8.30
charset-normalizer       3.4.0
google-api-core          2.21.0
google-auth              2.35.0
google-cloud-billing     1.13.6
googleapis-common-protos 1.65.0
grpc-google-iam-v1       0.13.1
grpcio                   1.67.0
grpcio-status            1.67.0
idna                     3.10
pip                      24.2
proto-plus               1.24.0
protobuf                 5.28.2
pyasn1                   0.6.1
pyasn1_modules           0.4.1
requests                 2.32.3
rsa                      4.9
urllib3                  2.2.3
```

**Comment by parthea** [comment]
Blocked by https://github.com/googleapis/proto-plus-python/issues/495
