### ISSUE TITLE
Cannot retrieve regional secret

### ISSUE THREAD

**Issue by derekjc** [googleapis/google-cloud-python#13389]
### Determine this is the right repository

- [X] I determined this is the correct repository in which to report this bug.

### Summary of the issue

**Context**
I'm using [access_secret_version](https://cloud.google.com/python/docs/reference/secretmanager/latest/google.cloud.secretmanager_v1.services.secret_manager_service.SecretManagerServiceClient#google_cloud_secretmanager_v1_services_secret_manager_service_SecretManagerServiceClient_access_secret_version) to fetch a regional secret. It does not work and I get error 400

**Expected Behavior:**
As per the docs, "projects/*/locations/*/secrets/*/versions/latest" is also supported.

**Actual Behavior:**
```
google.api_core.exceptions.InvalidArgument: 400 The provided Secret ID [projects/6836XXXXXX16/locations/me-central2/secrets/gg-xxxxxxxxx-secrets/versions/latest] does not match the expected format [projects/*/secrets/*/versions/*]
```

Am I doing something wrong or is this broken?

### API client name and version

google-cloud-secret-manager v2.22.0

### Reproduction steps: code

file: main.py
```python
from google.cloud import secretmanager_v1

def get_latest_secret(
    client: secretmanager_v1.SecretManagerServiceClient,
    project_id: str,
    secret_name: str,
    region: str
):
    name = f"projects/{project_id}/locations/{region}/secrets/{secret_name}/versions/latest"
    print(name)
    response = client.access_secret_version(name=name)
    print(response)
    secret_data = json.loads(response.payload.data.decode("UTF-8"))
    print(secret_data)


sm_client = secretmanager_v1.SecretManagerServiceClient()
get_latest_secret(sm_client, project_id="6836XXXXXX16", secret_name="gg-xxxxxxxxx-secrets", region="me-central2")
```

### Reproduction steps: supporting files

Create a regional secret from GCP [secrets console](https://console.cloud.google.com/security/secret-manager;regionalSecret) 

### Reproduction steps: actual results

```
projects/6836XXXXXX16/locations/me-central2/secrets/gg-xxxxxxxxx-secrets/versions/latest
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    get_latest_secret(sm_client, "6836XXXXXX16", "gg-xxxxxxxxx-secrets", "me-central2")
  File "main.py", line 11, in get_latest_secret
    response = client.access_secret_version(name=name)
  File "/tmp/venv/lib64/python3.8/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 1800, in access_secret_version
    response = rpc(
  File "/tmp/venv/lib64/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/tmp/venv/lib64/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/tmp/venv/lib64/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/tmp/venv/lib64/python3.8/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/tmp/venv/lib64/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/tmp/venv/lib64/python3.8/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/tmp/venv/lib64/python3.8/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 The provided Secret ID [projects/6836XXXXXX16/locations/me-central2/secrets/gg-xxxxxxxxx-secrets/versions/latest] does not match the expected format [projects/*/secrets/*/versions/*]
```

### Reproduction steps: expected results

secret data

### OS & version + platform

RHEL8

### Python environment

Python 3.8.12

### Python dependencies

Package                     Version
--------------------------- ----------
cachetools                  5.5.0
certifi                     2024.12.14
charset-normalizer          3.4.0
google-api-core             2.24.0
google-auth                 2.37.0
google-cloud-secret-manager 2.22.0
googleapis-common-protos    1.66.0
grpc-google-iam-v1          0.13.1
grpcio                      1.68.1
grpcio-status               1.68.1
idna                        3.10
pip                         19.3.1
proto-plus                  1.25.0
protobuf                    5.29.2
pyasn1                      0.6.1
pyasn1-modules              0.4.1
requests                    2.32.3
rsa                         4.9
setuptools                  41.6.0
urllib3                     2.2.3

**Comment by derekjc** [comment]
I didn't set the regional endpoint. This can be closed
