### ISSUE TITLE
transcode does not catch exceptions raised by regex logic

### ISSUE THREAD

**Issue by DavidKorczynski** [googleapis/google-cloud-python#15078]
This is an issue found by the fuzzer described here: https://github.com/googleapis/google-cloud-python/issues/15079 -- it would be great to have maintainer emails listed in: https://github.com/google/oss-fuzz/blob/master/projects/g-apis-py-api-core/project.yaml

The issue is that `transcode` may raise more exceptions than those defined in the API specificiation https://github.com/googleapis/python-api-core/blob/5b5e77563229687c901d77b5fdecc18168b535e6/google/api_core/path_template.py#L260-L261 Specifically, it uses the regex logic from Python which raise various exceptions and these are not caught by `transcode`.

when given input that corresponds to a list of dictionaries where `uri` and `body` and `method` are all keys in the dictionary with values of type string.

Am writing here because through my analysis this is a reliability issue, and not a security issue. 

#### Environment details

  - OS type and version: Linux, latest.
  - Python version: `python --version` 3.7.
  - pip version: `pip --version`
  - `google-api-core` version: `pip show google-api-core` this is from the latest repo.

#### Steps to reproduce

  1. Reproduce with OSS-Fuzz, you may have to rerun the last command (`python3 ... run_fuzzer ...`) a few times (less than 10):
  ```
  git clone https://github.com/google/oss-fuzz
  cd oss-fuzz
  python3 infra/helper.py build_fuzzers g-apis-py-api-core
  python3 infra/helper.py run_fuzzer g-apis-py-api-core fuzz_path_template
  ```
  2. The easiet way to reproduce is probably to list emails in the `oss-fuzz` `project.yaml` as described here: https://github.com/googleapis/google-cloud-python/issues/15079

#### Code example
The specific fuzzer that triggered this is https://github.com/google/oss-fuzz/blob/76b4b0422f769db942bce245bfcad018375e023e/projects/g-apis-py-api-core/fuzz_path_template.py

#### Stack trace
```
 === Uncaught Python exception: ===
error: unterminated character set at position 1
Traceback (most recent call last):
  File "fuzz_path_template.py", line 51, in TestOneInput
  File "google/api_core/path_template.py", line 278, in transcode
  File "google/api_core/path_template.py", line 237, in validate
  File "re.py", line 191, in match
  File "re.py", line 304, in _compile
  File "sre_compile.py", line 764, in compile
  File "sre_parse.py", line 948, in parse
  File "sre_parse.py", line 443, in _parse_sub
  File "sre_parse.py", line 549, in _parse

==16== ERROR: libFuzzer: fuzz target exited
    #0 0x7f63d0657cd1 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    googleapis/python-api-core#1 0x7f63d0598f58 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    googleapis/python-api-core#2 0x7f63d057e15c in fuzzer::Fuzzer::ExitCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:250:3
    googleapis/python-api-core#3 0x7f63d03408a6  (/lib/x86_64-linux-gnu/libc.so.6+0x468a6)
    googleapis/python-api-core#4 0x7f63d0340a5f in exit (/lib/x86_64-linux-gnu/libc.so.6+0x46a5f)
    googleapis/python-api-core#5 0x7f63ceff9df8 in Py_Exit /tmp/Python-3.8.3/Python/pylifecycle.c:2299:5
    googleapis/python-api-core#6 0x7f63ceffec0b in handle_system_exit /tmp/Python-3.8.3/Python/pythonrun.c:658:9
    googleapis/python-api-core#7 0x7f63ceffec0b in _PyErr_PrintEx /tmp/Python-3.8.3/Python/pythonrun.c:668:5
    googleapis/python-api-core#8 0x403ac2  (/out/fuzz_path_template.pkg+0x403ac2)
    googleapis/python-api-core#9 0x403e57  (/out/fuzz_path_template.pkg+0x403e57)
    googleapis/python-api-core#10 0x7f63d031e082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
    googleapis/python-api-core#11 0x40249d  (/out/fuzz_path_template.pkg+0x40249d)
```

**Comment by parthea** [comment]
Transferring to google-cloud-python as the code for python-api-core will be migrated there in 1-3 weeks.

**Comment by daniel-sanche** [comment]
This issue is being bulk closed due to inactivity. Please re-open if you think this still requires attention, and we'll take another look. Thanks!
