### ISSUE TITLE
 'encode' error when using secure_authorized_channel with google.auth.transport.requests.Request

### ISSUE THREAD

**Issue by salrashid123** [googleapis/google-cloud-python#15201]
Manually setting an `secure_authorized_channel` with a `google.auth.transport.requests.Request()` object results in the error shown above.

The snippet below attemtps to create a `secure_authorized_channel` as shown in the docs [here](https://google-auth.readthedocs.io/en/master/reference/google.auth.transport.grpc.html#google.auth.transport.grpc.secure_authorized_channel)  but when its actually executed (for pubsub grpc here), you see the encode exception.

  
#### Environment details

  - OS: linux
  - Python version: Python 3.10.5 (virtualenv)
  - pip version: pip 22.0.2
  - `google-auth` version: Version: 2.11.0
  - `google-auth-pubsub` version  Version: 2.13.6

#### Steps to reproduce

```python
import google.auth.credentials
import google.auth.jwt
import google.auth.transport.grpc
import grpc

import google.auth.transport.requests
from google.auth.transport.requests import AuthorizedSession

from google.cloud import pubsub_v1
from google.pubsub_v1.services.publisher import transports

project_id = "project"

credentials, _ = google.auth.default()
request = google.auth.transport.requests.Request()
channel = google.auth.transport.grpc.secure_authorized_channel(
    credentials,  pubsub_v1.PublisherClient.SERVICE_ADDRESS, request,
    ssl_credentials=grpc.ssl_channel_credentials())

transport = transports.PublisherGrpcTransport(channel=channel)
publisher =pubsub_v1.PublisherClient(transport=transport)

topic_name = 'projects/{project_id}/topics/{topic}'.format(
    project_id=project_id,
    topic='topic1', 
)    

topic = publisher.topic_path(project_id, 'topic1')
data = b'The rain in Wales falls mainly on the snails.'

for n in range(1, 2):
    future = publisher.publish(topic, data)
    print(future.result())
print("Published messages.")
```

gives

```
$ python3 main.py 
Traceback (most recent call last):
  File "/home/srashid/Desktop/sdk_custom_header/python/main.py", line 40, in <module>
    channel = google.auth.transport.grpc.secure_authorized_channel(
  File "/home/srashid/Desktop/sdk_custom_header/python/env/lib/python3.10/site-packages/google/auth/transport/grpc.py", line 286, in secure_authorized_channel
    return grpc.secure_channel(target, composite_credentials, **kwargs)
  File "/home/srashid/Desktop/sdk_custom_header/python/env/lib/python3.10/site-packages/grpc/__init__.py", line 2004, in secure_channel
    return _channel.Channel(target, () if options is None else options,
  File "/home/srashid/Desktop/sdk_custom_header/python/env/lib/python3.10/site-packages/grpc/_channel.py", line 1479, in __init__
    _common.encode(target), _augment_options(core_options, compression),
  File "/home/srashid/Desktop/sdk_custom_header/python/env/lib/python3.10/site-packages/grpc/_common.py", line 72, in encode
    return s.encode('utf8')
AttributeError: 'Request' object has no attribute 'encode'
```

---

Note, i'm eventually just trying set a custom metadata header for the pubsub grpc request through an [interceptor](https://github.com/grpc/grpc/tree/master/examples/python/interceptors/headers) and it seems you need to dive into the low level plumbing for this.  If there's a better way to do that, LMK.

**Comment by parthea** [comment]
Transferring to google-cloud-python as the code for google-auth-library-python will be migrated there in 1-3 weeks.

**Comment by daniel-sanche** [comment]
This issue is being bulk closed due to inactivity. Please re-open if you think this still requires attention, and we'll take another look. Thanks!
