### ISSUE TITLE
Thread-ConsumeBidirectionalStream exiting

### ISSUE THREAD

**Issue by lschaupp** [googleapis/google-cloud-python#15391]
#### Environment details

  - OS type and version:
  - Python version: 3.9.16
  - pip version: 22.3.1
  - `google-cloud-firestore` version: 2.11.1

#### Stack trace
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/manager/lib/python3.9/site-packages/google/api_core/bidi.py", line 657, in _thread_main
    self._on_response(response)
  File "/home/xxx/anaconda3/envs/manager/lib/python3.9/site-packages/google/cloud/firestore_v1/watch.py", line 459, in on_snapshot
    meth(self, proto.target_change)
  File "/home/xxx/anaconda3/envs/manager/lib/python3.9/site-packages/google/cloud/firestore_v1/watch.py", line 384, in _on_snapshot_target_ch
ange_no_change
    self.push(target_change.read_time, target_change.resume_token)
  File "/home/xxx/anaconda3/envs/manager/lib/python3.9/site-packages/google/cloud/firestore_v1/watch.py", line 550, in push
    updated_tree, updated_map, appliedChanges = self._compute_snapshot(
  File "/home/xxx/anaconda3/envs/manager/lib/python3.9/site-packages/google/cloud/firestore_v1/watch.py", line 674, in _compute_snapshot
    change, updated_tree, updated_map = delete_doc(
  File "/home/xxx/anaconda3/envs/manager/lib/python3.9/site-packages/google/cloud/firestore_v1/watch.py", line 608, in delete_doc
    existing = updated_tree.find(old_document)
  File "/home/xxx/anaconda3/envs/manager/lib/python3.9/site-packages/google/cloud/firestore_v1/watch.py", line 99, in find
    return self._dict[key]
KeyError: <google.cloud.firestore_v1.base_document.DocumentSnapshot object at 0x7fb67e9cf640>
INFO - Thread-ConsumeBidirectionalStream exiting

I am getting this issue after running firstore > 24 hours. It is very sporadic and inpredictable so far. Recently, it happens more often. Does anyone know more about this exception and what can be done to fix it?

**Comment by parthea** [comment]
Transferring to google-cloud-python as the code for python-firestore will be migrated there in 1-3 weeks.

**Comment by daniel-sanche** [comment]
This issue is being bulk closed due to inactivity. Please re-open if you think this still requires attention, and we'll take another look. Thanks!
