### ISSUE TITLE
ServiceUnavailable exception is not retried automatically

### ISSUE THREAD

**Issue by botsman** [googleapis/google-cloud-python#15394]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-firestore/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Debian GNU/Linux 11
  - Python version: `3.10.4`
  - pip version: `22.0.4`
  - `google-cloud-firestore` version: `2.6.1`

#### Steps to reproduce

Unfortunately, there are no exact steps to reproduce, because error does not occur always.
From time to time I get a `google.api_core.exceptions.ServiceUnavailable: 503 Connection reset by peer` exception.
I would expect such errors to be retried automatically by firestore, but it looks like they are not retried for some reason and raised immediately.
Perhaps I am missing something

#### Code example

I've simplified a code, but it does not do anything special:
```python
from google.cloud import firestore
from async_lru import alru_cache

db = firestore.AsyncClient()
class DbHandler:
    @staticmethod
    @alru_cache(maxsize=25)
    async def get_application():
        application_data = await db().collection("applications").document("app_id_here").get()
        return application_data
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers_async.py", line 73, in wait_for_connection
    await self._call.wait_for_connection()
  File "/usr/local/lib/python3.10/site-packages/grpc/aio/_call.py", line 573, in wait_for_connection
    await self._raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:64.233.167.95:443 {created_time:"2022-11-29T06:22:00.249392755+00:00", grpc_status:14, grpc_message:"Connection reset by peer"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
    application = await DbHandler.get_application(kid, validate=False)
  File "/app/app/cache_utils.py", line 37, in inner_wrapper
    return await wrapped(*args, **kwargs)
  File "/app/app/cache_utils.py", line 14, in inner_wrapper
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/async_lru.py", line 174, in wrapped
    return await asyncio.shield(fut)
  File "/app/app/cache_utils.py", line 25, in wrapper
    return await fn(*args, **kwargs)
  File "/app/app/db.py", line 107, in get_application
    await db()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/firestore_v1/async_document.py", line 367, in get
    response_iter = await self._client._firestore_api.batch_get_documents(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers_async.py", line 179, in error_remapped_callable
    await call.wait_for_connection()
  File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers_async.py", line 75, in wait_for_connection
    raise exceptions.from_grpc_error(rpc_error) from rpc_error
google.api_core.exceptions.ServiceUnavailable: 503 Connection reset by peer
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
Transferring to google-cloud-python as the code for python-firestore will be migrated there in 1-3 weeks.

**Comment by daniel-sanche** [comment]
This issue is being bulk closed due to inactivity. Please re-open if you think this still requires attention, and we'll take another look. Thanks!
