### ISSUE TITLE
wsgi_app.last_request_uri has no attribute 'replace'

### ISSUE THREAD

**Issue by antoscha** [googleapis/google-cloud-python#15450]
Hi,

I have an issue running [Google API Quickstart](https://developers.google.com/drive/api/v3/quickstart/python):
```
Traceback (most recent call last):
  File "quickstart.py", line 49, in <module>
    main() 
  File "quickstart.py", line 29, in main
    creds = flow.run_local_server(port=0)
  File "/usr/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 458, in run_local_server
    authorization_response = wsgi_app.last_request_uri.replace('http', 'https')
AttributeError: 'NoneType' object has no attribute 'replace'
```

Am I doing something wrong?

**Comment by parthea** [comment]
Transferring to google-cloud-python as the code for google-auth-library-python-oauthlib will be migrated there in 1-3 weeks.

**Comment by daniel-sanche** [comment]
Closing due to inactivity. Please re-open if this is still an issue and you want us to look again
