### ISSUE TITLE
Support XML API for Resumable Upload

### ISSUE THREAD

**Issue by anshulpatel25** [googleapis/google-cloud-python#15631]
## Expected Behavior

1. Generate signed URL using `gsutil`.

```
gsutil signurl -d 500m  -c 'text/plain' \
    -m RESUMABLE ~/Downloads/key.json \
    gs://<gcs_bucket>/<file_name>.txt
```

2. Use the signed URL with `ResumableUpload`

```
upload = ResumableUpload(signed_url, 1024*1024)
transport = session = Session()
response = upload.initiate(transport, stream, metadata, "text/plain", total_bytes=total_bytes)  
```

3. Upload should execute initiate method without giving an error and return the response object.

## Actual Behavior

1. Generate signed URL using `gsutil`.

`gsutil signurl -d 600m ~/Downloads/key.json gs://<gcs_bucket>/<file_name>.txt`.

2. Use the signed URL with `ResumableUpload`

```
upload = ResumableUpload(signed_url, 1024*1024)
response = upload.initiate(transport, stream, metadata, "text/plain", total_bytes=total_bytes) # transport = session = Session()
```

3. Getting the following exception

```python
Traceback (most recent call last):
  File "upload_test.py", line 19, in <module>
    response = upload.initiate(transport, stream, metadata, "text/plain", total_bytes=total_bytes)
  File "/Users/anshul.patel/.local/share/virtualenvs/virtualenv-python-domIBOZP/lib/python3.7/site-packages/google/resumable_media/requests/upload.py", line 327, in initiate
    self._process_initiate_response(result)
  File "/Users/anshul.patel/.local/share/virtualenvs/virtualenv-python-domIBOZP/lib/python3.7/site-packages/google/resumable_media/_upload.py", line 451, in _process_initiate_response
    response, u'location', self._get_headers)
  File "/Users/anshul.patel/.local/share/virtualenvs/virtualenv-python-domIBOZP/lib/python3.7/site-packages/google/resumable_media/_helpers.py", line 64, in header_required
    response, u'Response headers must contain header', name)
google.resumable_media.common.InvalidResponse: ('Response headers must contain header', 'location')
```

It seems like the `ResumableUpload` doesn't interpret XML API endpoint.

## Specifications

  - Version: 3.7
  - Platform: macOS Mojave 10.14.2

**Comment by parthea** [comment]
Transferring to google-cloud-python as the code for this repo will be migrated there in 1-2 weeks.
