### ISSUE TITLE
Does this a wheel for web assembly (WASM)

### ISSUE THREAD

**Issue by kiebak3r** [googleapis/google-cloud-python#15671]
I am trying to compile a python web application using Flet, firebase-admin and pyodide
https://github.com/firebase/firebase-admin-python/issues/771

Firebase-admin throws the error: 
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 395, in run_async
    await coroutine
  File "<exec>", line 4, in <module>
  File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 146, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'google-crc32c<2.0dev,>=1.0', 'grpcio<2.0dev,>=1.49.1; python_version >= "3.11" and extra == "grpc"', 'grpcio<2.0dev,>=1.33.2; extra == "grpc"', 'google-crc32c<2.0dev,>=1.0', 'grpcio>=1.60.1', 'grpcio>=1.60.1'
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package

    at new_error (pyodide.asm.js:9:10014)
    at pyodide.asm.wasm:0x158e62
    at pyodide.asm.wasm:0x15ff9e
    at _PyEM_TrampolineCall_JS (pyodide.asm.js:9:120223)
    at pyodide.asm.wasm:0x1a3494
    at pyodide.asm.wasm:0x28a2bd
    at pyodide.asm.wasm:0x1e431e
    at pyodide.asm.wasm:0x1a397d
    at pyodide.asm.wasm:0x1a3c3e
    at pyodide.asm.wasm:0x1a3ce0
    at pyodide.asm.wasm:0x2689a4
    at pyodide.asm.wasm:0x26e800
    at pyodide.asm.wasm:0x1a3e08
    at pyodide.asm.wasm:0x1a3a98
    at pyodide.asm.wasm:0x15f76b
    at Module.callPyObjectKwargs (pyodide.asm.js:9:64297)
    at Module.callPyObject (pyodide.asm.j)

any help would be greatly appreciated!

**Comment by chalmerlowe** [comment]
This issue was moved from the following repo as part of the monorepo migration: googleapis/python-crc32c

**Comment by daniel-sanche** [comment]
This issue is being bulk closed due to inactivity. Please re-open if you think this still requires attention, and we'll take another look. Thanks!

**Comment by agriyakhetarpal** [comment]
This can be marked as partially resolved, as we do have `google-crc32c` in pyodide-recipes: https://github.com/pyodide/pyodide-recipes/tree/d26e3c12ac8cc836d7395c76dc97292d3620e6b9/packages/google-crc32c.

However, please consider uploading a Pyodide wheel to PyPI as [PEP 783](https://discuss.python.org/t/pep-783-emscripten-packaging/86862) has been accepted earlier this year. See https://github.com/pyodide/pyodide-recipes#adding-a-new-package and https://pyodide-build.readthedocs.io/en/latest/ for more.

**Comment by daniel-sanche** [comment]
Thanks, we can keep this as a feature request with the storage team
