### ISSUE TITLE
Flaky test failure for `test_render_literal_bool_false`

### ISSUE THREAD

**Issue by olavloite** [googleapis/google-cloud-python#15681]
```
______ BooleanTest_spanner+spanner+spanner.test_render_literal_bool_false ______
Traceback (most recent call last):
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/tmpfs/src/github/python-spanner-sqlalchemy/test/test_suite_20.py", line 180, in test_render_literal_bool_false
    literal_round_trip(Boolean(), [False], [False])
  File "/tmpfs/src/github/python-spanner-sqlalchemy/.nox/compliance_test_20/lib/python3.8/site-packages/sqlalchemy/testing/suite/test_types.py", line 114, in run
    assert rows, "No rows returned"
AssertionError: No rows returned
assert []
```

**Comment by chalmerlowe** [comment]
This issue was moved from the following repo as part of the monorepo migration: googleapis/python-spanner-sqlalchemy
