### ISSUE TITLE
Is async support available?

### ISSUE THREAD

**Issue by eshwen** [googleapis/google-cloud-python#15783]
## Issue

I have a large codebase with several intensive queries to BigQuery. I'm trying to port these synchronous queries to async to improve performance, but am unable to create an async SQLAlchemy engine. Is there a specific dialect and/or driver I can provide in order to enable async functionality? Or is there an easy workaround?

### MWE

A simple script:

```python
from sqlalchemy.ext.asyncio import create_async_engine

conn_path = "bigquery://"
engine = create_async_engine(conn_path)
```

Resulting in the traceback

```
Traceback (most recent call last):
  File "/Users/eshwen.bhal/Library/Application Support/JetBrains/PyCharm2024.1/scratches/scratch_6.py", line 4, in <module>
    engine = create_async_engine(conn_path)
  File "/Users/eshwen.bhal/Documents/GitHub/mjolnir/.venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 118, in create_async_engine
    return AsyncEngine(sync_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eshwen.bhal/Documents/GitHub/mjolnir/.venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1023, in __init__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: The asyncio extension requires an async driver to be used. The loaded 'bigquery' is not async.
```

## Environment

- Python: 3.11.8
- SQLAlchemy: 2.0.28
- `sqlalchemy-bigquery`: 1.11.0
- Chip: Apple M2 Pro
- OS: macOS 14.4.1

**Comment by chalmerlowe** [comment]
This issue was moved from the following repo as part of the monorepo migration: googleapis/python-bigquery-sqlalchemy

**Comment by daniel-sanche** [comment]
This issue is being bulk closed due to inactivity. Please re-open if you think this still requires attention, and we'll take another look. Thanks!
