### ISSUE TITLE
`unhashable type: 'list'` when using list of boolean in `in_()`

### ISSUE THREAD

**Issue by TeddyCr** [googleapis/google-cloud-python#15796]
#### Environment details
  - OS type and version: Mac M1 (MacOS Monterey)
  - Python version: `python --version` 3.9.9
  - pip version: `pip --version` 22.1.2
  - `sqlalchemy-bigquery` version: `pip show sqlalchemy-bigquery` 1.4.3
  - sqlalchemy 1.4.27

#### Steps to reproduce
1. create a sqlalchemy session 
2. create a sqlalchemy declarative meta table object
3. execute the following query
```
from sqlalchemy import case, column, func

...

sessiom.query(sum(case([(column(<column_name>).in_([True, False]), 1)], else_=0))).select_from(<ORM table object>).first()
```

#### Stack trace
```
SELECT SUM(CAST(CASE WHEN (`tag_based` IN UNNEST(%(tag_based_1:BOOL)s)) THEN %(param_1:INT64)s ELSE %(param_2:INT64)s END AS NUMERIC)) AS `countInSet` 
FROM `stackoverflow`.`badges`
Traceback (most recent call last):
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1702, in _execute_context
    context = constructor(
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1080, in _init_compiled
    param = {
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1081, in <dictcomp>
    key: processors[key](compiled_params[key])
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/sql/sqltypes.py", line 1984, in process
    value = _strict_as_bool(value)
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/sql/sqltypes.py", line 1957, in _strict_as_bool
    if value not in self._strict_bools:
TypeError: unhashable type: 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2810, in first
    return self.limit(1)._iter().first()
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1708, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1702, in _execute_context
    context = constructor(
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1080, in _init_compiled
    param = {
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1081, in <dictcomp>
    key: processors[key](compiled_params[key])
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/sql/sqltypes.py", line 1984, in process
    value = _strict_as_bool(value)
  File "/Users/teddycrepineau/.venv/omd_3_9/lib/python3.9/site-packages/sqlalchemy/sql/sqltypes.py", line 1957, in _strict_as_bool
    if value not in self._strict_bools:
sqlalchemy.exc.StatementError: (builtins.TypeError) unhashable type: 'list'
[SQL: SELECT SUM(CAST(CASE WHEN (`tag_based` IN UNNEST(%(tag_based_1:BOOL)s)) THEN %(param_1:INT64)s ELSE %(param_2:INT64)s END AS NUMERIC)) AS `countInSet` 
FROM `stackoverflow`.`badges`
 LIMIT %(param_3:INT64)s]
```

When comparing with other dialects (i.e. redshift), I can see that bigquery passes a list to the processor function in `sqlalchemy/engine/default.py` (line 1081) which causes an issue in `sqlalchemy/sql/sqltypes.py` (line 1957) where the below check is performed

```python
    _strict_bools = frozenset([None, True, False])

    def _strict_as_bool(self, value):
        if value not in self._strict_bools:
            if not isinstance(value, int):
                raise TypeError("Not a boolean value: %r" % value)
            else:
                raise ValueError(
                    "Value %r is not None, True, or False" % value
                )
        return value
```

Other dialects seem to break down each parameter into a single value. For example, when performing the same query with redshift dialect I can see the following compiled parameters

```
[{'param_1': 1, 'param_2': 0, 'param_3': 1, 'is_customer_1_1': 'True', 'is_customer_1_2': 'False'}]
```

vs bigquery

```
[{'tag_based_1': [True, False], 'param_1': 1, 'param_2': 0, 'param_3': 1}]
```

**Comment by chalmerlowe** [comment]
This issue was moved from the following repo as part of the monorepo migration: googleapis/python-bigquery-sqlalchemy

**Comment by daniel-sanche** [comment]
This issue is being bulk closed due to inactivity. Please re-open if you think this still requires attention, and we'll take another look. Thanks!
