### ISSUE TITLE
`django3.2-tests0` presubmit fails with error `ModuleNotFoundError: No module named 'tests.sessions_tests'`

### ISSUE THREAD

**Issue by parthea** [googleapis/google-cloud-python#15937]
The `django3.2-tests0` presubmit check is failing. See [build log](https://github.com/googleapis/python-spanner-django/actions/runs/6388272233/job/17337834032?pr=835).

The stack trace is below
```
======================================================================
ERROR: test_clearsessions_unsupported (sessions_tests.tests.ClearSessionsCommandTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/python-spanner-django/python-spanner-django/django_tests_dir/django3.2/tests/sessions_tests/tests.py", line 923, in test_clearsessions_unsupported
    management.call_command('clearsessions')
  File "/home/runner/work/python-spanner-django/python-spanner-django/django_tests_dir/django3.2/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/runner/work/python-spanner-django/python-spanner-django/django_tests_dir/django3.2/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/runner/work/python-spanner-django/python-spanner-django/django_tests_dir/django3.2/django/contrib/sessions/management/commands/clearsessions.py", line 14, in handle
    engine = import_module(settings.SESSION_ENGINE)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tests.sessions_tests'
```

**Comment by chalmerlowe** [comment]
This issue was moved from the following repo as part of the monorepo migration: googleapis/python-spanner-django

**Comment by parthea** [comment]
Closing as obsolete. This was removed in https://github.com/googleapis/google-cloud-python/pull/16624
