### ISSUE TITLE
django-test-suite: TIMESTAMP_TRUNC with timezone not working as expected

### ISSUE THREAD

**Issue by timgraham** [googleapis/google-cloud-python#15958]
Failure:
```
======================================================================
FAIL: test_query_datetimes (timezones.tests.NewDatabaseTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/test/testcases.py", line 1229, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/home/tim/code/django/tests/timezones/tests.py", line 396, in test_query_datetimes
    [datetime.datetime(2011, 1, 1, 0, 0, 0, tzinfo=EAT)]
AssertionError: Sequences differ: <QuerySet [datetime.datetime(2010, 12, 31[58 chars]D>)]> != [datetime.datetime(2011, 1, 1, 0, 0, tzin[61 chars]0'))]

First differing element 0:
datetime.datetime(2010, 12, 31, 21, 0, tzinfo=<DstTzInfo 'Afri[24 chars]STD>)
datetime.datetime(2011, 1, 1, 0, 0, tzinfo=datetime.timezone(d[38 chars]00'))

- <QuerySet [datetime.datetime(2010, 12, 31, 21, 0, tzinfo=<DstTzInfo 'Africa/Nairobi' EAT+3:00:00 STD>)]>
+ [datetime.datetime(2011, 1, 1, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(seconds=10800), '+0300'))]

```

**Comment by chalmerlowe** [comment]
This issue was moved from the following repo as part of the monorepo migration: googleapis/python-spanner-django

**Comment by coryan** [comment]
There is no progress in 5 years: is this really a P1? I think we should close (as "fixed" if that is appropriate, as "not planned" if not) as it is not serving any useful purpose.

**Comment by parthea** [comment]
Closing as obsolete
