### ISSUE TITLE
django-test-suite: model_formsets failures

### ISSUE THREAD

**Issue by timgraham** [googleapis/google-cloud-python#15952]
These failure are probably due to patching of AutoField. Need to investigate the implications.
```
======================================================================
FAIL: model_formsets.tests.ModelFormsetTest.test_prevent_change_outer_model_and_create_invalid_data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/model_formsets/tests.py", line 1683, in test_prevent_change_outer_model_and_create_invalid_data
    self.assertQuerysetEqual(Author.objects.all(), ['<Author: Charles>', '<Author: Walt>'])
  File "/home/tim/code/django/django/test/testcases.py", line 1056, in assertQuerysetEqual
    return self.assertEqual(list(items), values, msg=msg)
AssertionError: Lists differ: ['<Author: Changed name>', '<Author: Charles>', '<Author: Walt>'] != ['<Author: Charles>', '<Author: Walt>']

First differing element 0:
'<Author: Changed name>'
'<Author: Charles>'

First list contains 1 additional elements.
First extra element 2:
'<Author: Walt>'

- ['<Author: Changed name>', '<Author: Charles>', '<Author: Walt>']
?            --------------------------

+ ['<Author: Charles>', '<Author: Walt>']
```

```
======================================================================
FAIL: test_no_delete (model_formsets_regress.tests.FormfieldShouldDeleteFormTests)
Verify base formset doesn't modify database
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/model_formsets_regress/tests.py", line 457, in test_no_delete
    self.assertTrue(formset.is_valid())
AssertionError: False is not true
```

```
======================================================================
FAIL: test_extraneous_query_is_not_run (model_formsets_regress.tests.FormsetTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/model_formsets_regress/tests.py", line 307, in test_extraneous_query_is_not_run
    formset.save()
  File "/home/tim/code/django/django/test/testcases.py", line 85, in __exit__
    '%d. %s' % (i, query['sql']) for i, query in enumerate(self.captured_queries, start=1)
AssertionError: 3 != 1 : 3 queries executed, 1 expected
Captured queries were:
1. QUERY = 'SELECT (1) AS a FROM model_formsets_regress_network WHERE model_formsets_regress_network.id = %s  LIMIT 1' - PARAMS = (2714094443186884760,)
2. QUERY = 'UPDATE model_formsets_regress_network SET name = %s WHERE model_formsets_regress_network.id = %s' - PARAMS = ('Random Place', 2714094443186884760)
3. QUERY = 'INSERT INTO model_formsets_regress_network (id, name) VALUES (%s, %s)' - PARAMS = (2714094443186884760, 'Random Place')
```

**Comment by chalmerlowe** [comment]
This issue was moved from the following repo as part of the monorepo migration: googleapis/python-spanner-django

**Comment by parthea** [comment]
Closing due to inactivity
