### ISSUE TITLE
SphinxWarning in docs build for generated client for `google-cloud-kms`

### ISSUE THREAD

**Issue by parthea** [googleapis/google-cloud-python#16363]
The following SphinxWarnings appears in the docs build for `google-cloud-kms`

```
Traceback (most recent call last):
  File "/usr/local/google/home/partheniou/git/google-cloud-python/packages/google-cloud-kms/.nox/docs/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/google/home/partheniou/git/google-cloud-python/packages/google-cloud-kms/.nox/docs/lib/python3.9/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/usr/local/google/home/partheniou/git/google-cloud-python/packages/google-cloud-kms/.nox/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 292, in build_update
    self.build(to_build,
  File "/usr/local/google/home/partheniou/git/google-cloud-python/packages/google-cloud-kms/.nox/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 306, in build
    updated_docnames = set(self.read())
  File "/usr/local/google/home/partheniou/.pyenv/versions/3.9.16/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/local/google/home/partheniou/git/google-cloud-python/packages/google-cloud-kms/.nox/docs/lib/python3.9/site-packages/sphinx/util/logging.py", line 213, in pending_warnings
    memhandler.flushTo(logger)
  File "/usr/local/google/home/partheniou/git/google-cloud-python/packages/google-cloud-kms/.nox/docs/lib/python3.9/site-packages/sphinx/util/logging.py", line 178, in flushTo
    logger.handle(record)
  File "/usr/local/google/home/partheniou/.pyenv/versions/3.9.16/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/google/home/partheniou/.pyenv/versions/3.9.16/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/google/home/partheniou/.pyenv/versions/3.9.16/lib/python3.9/logging/__init__.py", line 948, in handle
    rv = self.filter(record)
  File "/usr/local/google/home/partheniou/.pyenv/versions/3.9.16/lib/python3.9/logging/__init__.py", line 806, in filter
    result = f.filter(record)
  File "/usr/local/google/home/partheniou/git/google-cloud-python/packages/google-cloud-kms/.nox/docs/lib/python3.9/site-packages/sphinx/util/logging.py", line 423, in filter
    raise exc
sphinx.errors.SphinxWarning: /usr/local/google/home/partheniou/git/google-cloud-python/packages/google-cloud-kms/google/cloud/kms_v1/services/ekm_service/async_client.py:docstring of google.cloud.kms_v1.services.ekm_service.async_client.EkmServiceAsyncClient.set_iam_policy:39:Unexpected indentation.

Warning, treated as error:
/usr/local/google/home/partheniou/git/google-cloud-python/packages/google-cloud-kms/google/cloud/kms_v1/services/ekm_service/async_client.py:docstring of google.cloud.kms_v1.services.ekm_service.async_client.EkmServiceAsyncClient.set_iam_policy:39:Unexpected indentation.
```

The issue is that sphinx expects a new line after the code block directive `::` but there is no new line in the generated output.

See the generated code here: https://github.com/googleapis/googleapis-gen/blob/2015275a7dda2ad3d1609f06c4208125c7de8a9d/google/cloud/kms/v1/kms-v1-py/google/cloud/kms_v1/services/ekm_service/async_client.py#L1196-L1219

```
                ::
                    {
                      "bindings": [
                        {
                          "role": "roles/resourcemanager.organizationAdmin",
                          "members": [
                            "user:mike@example.com",
                            "group:admins@example.com",
                            "domain:google.com",
                            "serviceAccount:my-project-id@appspot.gserviceaccount.com"
                          ]
                        },
                        {
                          "role": "roles/resourcemanager.organizationViewer",
                          "members": ["user:eve@example.com"],
                          "condition": {
                            "title": "expirable access",
                            "description": "Does not grant access after Sep 2020",
                            "expression": "request.time <
                            timestamp('2020-10-01T00:00:00.000Z')",
                          }
                        }
                      ]
                    }
```

**Comment by parthea** [comment]
Transferring to google-cloud-python as the code for gapic-generator will be migrated there.

**Comment by parthea** [comment]
Closing as obsolete as we're no longer treating docs warnings as errors as of https://github.com/googleapis/google-cloud-python/pull/16627
