### ISSUE TITLE
Improve autogenerated code snippets for google-cloud-datacatalog to use regional endpoint

### ISSUE THREAD

**Issue by farmanp** [googleapis/google-cloud-python#16407]
I am trying to use the `google-cloud-datacatalog` Python client library to access the Data Catalog API. However, when trying to run the sample code provided in the documentation, I am getting a:

```
google.api_core.exceptions.MethodNotImplemented: 501 Received http2 header with status: 404 error.
```

After investigating further, it seems that the `google-cloud-datacatalog` library does not support all the features of the Data Catalog API. Specifically, I am unable to use the `list_entries()` and `list_tags()` methods.

#### Environment details

- Python version: 3.9.9
- Operating System: macOS Monterey
- pip 22.0.4
- google-cloud-datacatalog version: 3.11.1

#### Code example
Run the following code snippet:

```
from google.cloud.datacatalog_v1 import DataCatalogClient, ListTagsRequest

key_path = 'data_catalog_service_account.json'
client = DataCatalogClient.from_service_account_json(key_path)

project_id = PROJECT_ID
location = LOCATION 

client.list_tags()
```

#### Stack trace

```
E0302 12:09:28.450903000 140704570279552 hpack_parser.cc:1242]         Error parsing metadata: error=invalid value key=content-type value=text/html; charset=UTF-8
Traceback (most recent call last):
  File "/env/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/env/lib/python3.9/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/env/lib/python3.9/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "Received http2 header with status: 404"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:172.217.10.106:443 {created_time:"2023-03-02T12:09:28.451089-07:00", grpc_status:12, grpc_message:"Received http2 header with status: 404"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data_catalog.py", line 11, in <module>
    response = client.get_tag_template(request=request)
  File "/env/lib/python3.9/site-packages/google/cloud/datacatalog_v1/services/data_catalog/client.py", line 2489, in get_tag_template
    response = rpc(
  File "/env/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/env/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.MethodNotImplemented: 501 Received http2 header with status: 404
```

**Comment by parthea** [comment]
Transferring to google-cloud-python as the code for gapic-generator will be migrated there.

**Comment by daniel-sanche** [comment]
This issue is being bulk closed due to inactivity. Please re-open if you think this still requires attention, and we'll take another look. Thanks!
