### ISSUE TITLE
Add support for remapping `ndb` module paths when unpickling

### ISSUE THREAD

**Issue by dhermes** [googleapis/google-cloud-python#6254]
An example pickled output from legacy GAE for testing:

```python
>>> import main
>>> m = main.M(a=10, b=11, c=12, d=13)
>>> key = m.put()
>>> m
M(key=Key('M', 5910974510923776), a=10, b=11, c=12, d=13)
>>> pickle.dumps(m)
b"ccopy_reg\n_reconstructor\np0\n(cmain\nM\np1\nc__builtin__\nobject\np2\nNtp3\nRp4\nS'j\\x1aj\\x08dev~Noner\\x0e\\x0b\\x12\\x01M\\x18\\x80\\x80\\x80\\x80\\x80\\x80\\xc0\\n\\x0cr\\t\\x1a\\x01a \\x00*\\x02\\x08\\nr\\t\\x1a\\x01b\\x00*\\x02\\x08\\x0br\\t\\x1a\\x01c \\x00*\\x02\\x08\\x0cr\\t\\x1a\\x01d \\x00*\\x02\\x08\\r\\x82\\x01\\x0e\\x0b\\x12\\x01M\\x18\\x80\\x80\\x80\\x80\\x80\\x80\\xc0\\n\\x0c'\np5\nb."
```

where

```python
class M(ndb.Model):
    a = ndb.IntegerProperty()
    b = ndb.IntegerProperty()
    c = ndb.IntegerProperty()
    d = ndb.IntegerProperty()
```

**Comment by dhermes** [comment]
I did some detective work on how to do this: https://github.com/dhermes/pickle-rename

As long as we are in control of calls to `pickle.load()` and `pickle.loads()`, we can intercept the process and remap the module names. If not, then there is nothing that can be done.

**Comment by dhermes** [comment]
Moar updates. `Model` is particularly no fun because it returns the raw bytes in the serailized protobuf from [`__getstate__()`][1]. In Python 3, `state` is required to be a dictionary:

```python
>>> import sys
>>> sys.version
'3.7.1 (default, Oct 21 2018, 22:21:13) \n[GCC 7.3.0]'
>>> import pickle
>>> class B:
...     def __init__(self, x):
...         self.x = x
...     def __getstate__(self):
...         return self.x
...
>>> b = B(11.5)
>>> d = pickle.dumps(b)
>>> d
b"\x80\x03c__main__\nB\nq\x00)\x81q\x01G@'\x00\x00\x00\x00\x00\x00b."
>>> pickle.loads(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.UnpicklingError: state is not a dictionary
```

So, when trying to unpickle the example snippet, I get similar results:

```python
>>> pickled_m
b"ccopy_reg\n_reconstructor\np0\n(cmain\nM\np1\nc__builtin__\nobject\np2\nNtp3\nRp4\nS'j\\x1aj\\x08dev~Noner\\x0e\\x0b\\x12\\x01M\\x18\\x80\\x80\\x80\\x80\\x80\\x80\\xc0\\n\\x0cr\\t\\x1a\\x01a \\x00*\\x02\\x08\\nr\\t\\x1a\\x01b\\x00*\\x02\\x08\\x0br\\t\\x1a\\x01c \\x00*\\x02\\x08\\x0cr\\t\\x1a\\x01d \\x00*\\x02\\x08\\r\\x82\\x01\\x0e\\x0b\\x12\\x01M\\x18\\x80\\x80\\x80\\x80\\x80\\x80\\xc0\\n\\x0c'\np5\nb."
>>> pickle.loads(pickled_m)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 19: ordinal not in range(128)
>>> pickle.loads(pickled_m, encoding="bytes")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.UnpicklingError: state is not a dictionary
```

[1]: https://github.com/GoogleCloudPlatform/datastore-ndb-python/blob/cf4cab3f1f69cd04e1a9229871be466b53729f3f/ndb/model.py#L2964-L2965

**Comment by dhermes** [comment]
Relevant places where the `pickle` protocol "matters" in `datastore-ndb-python`

```
$ git log -1 --pretty=%H
cf4cab3f1f69cd04e1a9229871be466b53729f3f
$ git grep -n '\(etstate__\|__reduce\|__getnewargs\)'
ndb/key.py:432:  def __getstate__(self):
ndb/key.py:440:  def __setstate__(self, state):
ndb/key.py:454:  def __getnewargs__(self):
ndb/key_test.py:506:    # When making changes to key.Key.__getstate__, add an additional list with
ndb/model.py:2964:  def __getstate__(self):
ndb/model.py:2967:  def __setstate__(self, serialized_pb):
ndb/query.py:461:  def __getnewargs__(self):
ndb/query.py:512:  def __getnewargs__(self):
ndb/query.py:552:  def __getnewargs__(self):
ndb/query.py:610:  def __getnewargs__(self):
ndb/query.py:674:  def __getnewargs__(self):
```

In addition, all `__new__` call sites matter because `pickle.load()` (and `loads()`) use `__new__` and bypass `__init__`.

```
$ git grep -n __new__ -- ndb/
ndb/key.py:208:  def __new__(cls, *_args, **kwargs):
ndb/key.py:222:    self = super(Key, cls).__new__(cls)
ndb/model.py:510:  def __new__(cls, name, direction):
ndb/model.py:512:    obj = object.__new__(cls)
ndb/model.py:547:  def __new__(cls, kind, properties, ancestor):
ndb/model.py:549:    obj = object.__new__(cls)
ndb/model.py:594:  def __new__(cls, definition, state, id):
ndb/model.py:596:    obj = object.__new__(cls)
ndb/query.py:389:  def __new__(cls):
ndb/query.py:392:    return super(Node, cls).__new__(cls)
ndb/query.py:448:  def __new__(cls, prop, op, param):
ndb/query.py:455:    obj = super(ParameterNode, cls).__new__(cls)
ndb/query.py:489:  def __new__(cls, name, opsymbol, value):
ndb/query.py:506:    self = super(FilterNode, cls).__new__(cls)
ndb/query.py:547:  def __new__(cls, predicate):
ndb/query.py:548:    self = super(PostFilterNode, cls).__new__(cls)
ndb/query.py:573:  def __new__(cls, *nodes):
ndb/query.py:606:    self = super(ConjunctionNode, cls).__new__(cls)
ndb/query.py:656:  def __new__(cls, *nodes):
ndb/query.py:661:    self = super(DisjunctionNode, cls).__new__(cls)
```
