### ISSUE TITLE
Datastore: protobuf dependency requirements incorrect

### ISSUE THREAD

**Issue by aarontp** [googleapis/google-cloud-python#6390]
I believe that the indirect dependency requirements for the `protobuf` package  is not correct.  This is similar to https://github.com/googleapis/google-cloud-python/issues/6128 .  Maybe the minimum version of `google-api-core` needs to be updated?  This seems to work with google-cloud-datastore==1.7.0, but then breaks with version 1.7.1.

The breaking changes appear to be in this commit:
https://github.com/googleapis/google-cloud-python/commit/6a6f1e1db5f4212cf9dc554b2a0778a2e98b7455#diff-677d93da9ffc63ac9fceae97c454bc55

OS type and version: `Linux/Ubuntu 14.04.5 LTS`
Python version and virtual environment information: 
```$ python --version
Python 2.7.6
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages (python 2.7)```

4. google-cloud-<service> version:  `google-cloud-datastore==1.7.1`. 

5. Stacktrace if available
```Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/log2timeline/dftimewolf/tests/lib/processors/turbinia.py", line 10, in <module>
    from dftimewolf.lib.processors import turbinia
  File "./dftimewolf/lib/processors/turbinia.py", line 10, in <module>
    from turbinia import client as turbinia_client
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/turbinia/client.py", line 29, in <module>
    from turbinia import task_manager
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/turbinia/task_manager.py", line 25, in <module>
    from turbinia import state_manager
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/turbinia/state_manager.py", line 38, in <module>
    from google.cloud import datastore
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/google/cloud/datastore/__init__.py", line 61, in <module>
    from google.cloud.datastore.batch import Batch
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/google/cloud/datastore/batch.py", line 24, in <module>
    from google.cloud.datastore import helpers
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/google/cloud/datastore/helpers.py", line 29, in <module>
    from google.cloud.datastore_v1.proto import datastore_pb2
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/google/cloud/datastore_v1/__init__.py", line 17, in <module>
    from google.cloud.datastore_v1 import types
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/google/cloud/datastore_v1/types.py", line 26, in <module>
    from google.cloud.datastore_v1.proto import datastore_pb2
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/google/cloud/datastore_v1/proto/datastore_pb2.py", line 17, in <module>
    from google.cloud.datastore_v1.proto import entity_pb2 as google_dot_cloud_dot_datastore__v1_dot_proto_dot_entity__pb2
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/google/cloud/datastore_v1/proto/entity_pb2.py", line 46, in <module>
    options=None, file=DESCRIPTOR)
TypeError: __new__() got an unexpected keyword argument 'file'
```

6. Steps to reproduce: 
`from google.cloud import datastore`

7. Code example
`from google.cloud import datastore`

**Comment by tseaver** [comment]
Thanks for the follow-up.  #6391 fixes that first for datastore, and then adds normalization for dependencies in all our `setup.py` files to prevent similar issues.  I also added an [issue](https://github.com/googleapis/gapic-generator/issues/2404) and a [pull request](https://github.com/googleapis/gapic-generator/pull/2405) for the `gapic-generator` to ensure that it emits correct minimum dependency in a synth-cycle.

**Comment by aarontp** [comment]
Thanks much for the fast fix.  The longer term fixes are appreciated as well, thanks!
