### ISSUE TITLE
ImportError: cannot import name 'SpeechClient'

### ISSUE THREAD

**Issue by RawStewage** [googleapis/google-cloud-python#6541]
Hi so I've been trying to follow along with the speech API example

```
from google.cloud import speech_v1
from google.cloud.speech_v1 import enums

client = speech_v1.SpeechClient()

encoding = enums.RecognitionConfig.AudioEncoding.FLAC
sample_rate_hertz = 44100
language_code = 'en-US'
config = {'encoding': encoding, 'sample_rate_hertz': sample_rate_hertz, 'language_code': language_code}
uri = 'gs://bucket_name/file_name.flac'
audio = {'uri': uri}

response = client.recognize(config, audio)
```

But when running the script with appropriate values the following error ensues. 
```
ImportError: cannot import name 'SpeechClient'
```
This is on a clean python 3.6 virtual env 

pip freeze output:
```
cachetools==3.0.0
certifi==2018.10.15
chardet==3.0.4
google-api-core==1.5.2
google-auth==1.6.1
google-cloud-speech==0.36.0
googleapis-common-protos==1.5.5
grpcio==1.16.1
idna==2.7
pkg-resources==0.0.0
protobuf==3.6.1
pyasn1==0.4.4
pyasn1-modules==0.2.2
pytz==2018.7
requests==2.20.1
rsa==4.0
six==1.11.0
urllib3==1.24.1
```

**Comment by tseaver** [comment]
That `ImportError` can't be raised by the example as posted.  Can you post the full traceback, and double check that the script you are running matches?

**Comment by tseaver** [comment]
@RawStewage Please feel free to reopen with the additional information.

**Comment by linhnvhicts** [comment]
I'm also encounter the same problem when following the API example here the full traceback:

```
Traceback (most recent call last):
  File "google.py", line 11, in <module>
    from google.cloud import speech_v1 as speech
  File "/home/hoanglinh/Documents/practice_speech/.venv/lib/python3.6/site-packages/google/cloud/speech_v1/__init__.py", line 17, in <module>
    from google.cloud.speech_v1.gapic import speech_client
  File "/home/hoanglinh/Documents/practice_speech/.venv/lib/python3.6/site-packages/google/cloud/speech_v1/gapic/speech_client.py", line 18, in <module>
    import pkg_resources
  File "/home/hoanglinh/Documents/practice_speech/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/hoanglinh/Documents/practice_speech/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/hoanglinh/Documents/practice_speech/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
    for dist in working_set
  File "/home/hoanglinh/Documents/practice_speech/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3269, in <genexpr>
    for dist in working_set
  File "/home/hoanglinh/Documents/practice_speech/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2776, in activate
    declare_namespace(pkg)
  File "/home/hoanglinh/Documents/practice_speech/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2275, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/hoanglinh/Documents/practice_speech/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2208, in _handle_ns
    loader.load_module(packageName)
  File "/home/hoanglinh/Documents/practice_speech/google.py", line 12, in <module>
    from google.cloud.speech import enums
  File "/home/hoanglinh/Documents/practice_speech/.venv/lib/python3.6/site-packages/google/cloud/speech.py", line 19, in <module>
    from google.cloud.speech_v1 import SpeechClient
ImportError: cannot import name 'SpeechClient'
```

it lead to the speech.py file in the package which is this 

```
from __future__ import absolute_import

from google.cloud.speech_v1 import SpeechClient
from google.cloud.speech_v1 import enums
from google.cloud.speech_v1 import types

__all__ = ("enums", "types", "SpeechClient")
```

**Comment by Ria312** [comment]
from google.cloud.speech_v1 import enums
ImportError: cannot import name 'enums'

I cannot import enums by having this in my code. Any suggestions will be helpful.

**Comment by tseaver** [comment]
@Ria312 `google-cloud-speech` is now maintained in its [own repository](https://github.com/googleapis/python-speech/).  Please see the [`UPGRADING.md` file there](https://github.com/googleapis/python-speech/blob/master/UPGRADING.md#enums-and-types) for info on how to update your code to match its current API.
