### ISSUE TITLE
Logging: Cannot handle failed logging attempts

### ISSUE THREAD

**Issue by brunoais** [googleapis/google-cloud-python#6645]
Possibly related: https://github.com/googleapis/google-cloud-python/issues/5410
I'm getting intermittent status code 503 responses from the service, when the logging client tries to log logs. When that happens, the problem is logged into the logger (of same name as the module) and I can't do anything about it not even, programmatically, resend it to stackdriver.

Additionally, I have no intentions of using the sync API due to how much it slows down the whole system.

#### Environment details

2. Linux (default OS used in google cloud flexible)
3. google cloud flexible python 3.6.x
4. google-cloud-logging==1.7.0

#### Steps to reproduce

  1. Generate a large amount of logs and it intermittently happens

#### Stack trace
```
ERROR:google.cloud.logging.handlers.transports.background_thread:Failed to submit 1 logs.
Traceback (most recent call last): File "/env/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable return callable_(*args, **kwargs) File "/env/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__ return _end_unary_response_blocking(state, call, False, None) File "/env/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking raise _Rendezvous(state, None, None, deadline) grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "Socket closed"
debug_error_string = "{"created":"@1542965282.988857618","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"Socket closed","grpc_status":14}"
>
The above exception was the direct cause of the following exception:
Traceback (most recent call last): File "/env/lib/python3.6/site-packages/google/cloud/logging/handlers/transports/background_thread.py", line 118, in _safely_commit_batch batch.commit() File "/env/lib/python3.6/site-packages/google/cloud/logging/logger.py", line 612, in commit client.logging_api.write_entries(entries, **kwargs) File "/env/lib/python3.6/site-packages/google/cloud/logging/_gapic.py", line 124, in write_entries partial_success=partial_success) File "/env/lib/python3.6/site-packages/google/cloud/logging_v2/gapic/logging_service_v2_client.py", line 341, in write_log_entries request, retry=retry, timeout=timeout, metadata=metadata) File "/env/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__ return wrapped_func(*args, **kwargs) File "/env/lib/python3.6/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func on_error=on_error, File "/env/lib/python3.6/site-packages/google/api_core/retry.py", line 177, in retry_target return target() File "/env/lib/python3.6/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout return func(*args, **kwargs) File "/env/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 61, in error_remapped_callable six.raise_from(exceptions.from_grpc_error(exc), exc) File "<string>", line 3, in raise_from google.api_core.exceptions.ServiceUnavailable: 503 Socket closed

```

**Comment by tdszyman** [comment]
I'm also getting this with google-cloud-logging==1.8.0 and it's intermittently killing my GKE workloads

**Comment by FloraSaysGoodmorning** [comment]
Having the same issue with `google-cloud-logging==1.6.0`, was trying to submit json logs to stackdrvier via the client.
```
Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable return callable_(*args, **kwargs) File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__ return _end_unary_response_blocking(state, call, False, None) File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking raise _Rendezvous(state, None, None, deadline) grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "OS Error"
debug_error_string = "{"created":"@1546559356.563894211","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"OS Error","grpc_status":14}"
```
which led to :
```
File "/usr/local/lib/python3.6/site-packages/google/cloud/logging/logger.py", line 259, in log_struct client.logging_api.write_entries([entry_resource]) File "/usr/local/lib/python3.6/site-packages/google/cloud/logging/_gapic.py", line 124, in write_entries partial_success=partial_success) File "/usr/local/lib/python3.6/site-packages/google/cloud/logging_v2/gapic/logging_service_v2_client.py", line 341, in write_log_entries request, retry=retry, timeout=timeout, metadata=metadata) File "/usr/local/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__ return wrapped_func(*args, **kwargs) File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func on_error=on_error, File "/usr/local/lib/python3.6/site-packages/google/api_core/retry.py", line 179, in retry_target return target() File "/usr/local/lib/python3.6/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout return func(*args, **kwargs) File "/usr/local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable six.raise_from(exceptions.from_grpc_error(exc), exc) File "<string>", line 3, in raise_from google.api_core.exceptions.ServiceUnavailable: 503 OS Error
```

**Comment by toddpi314** [comment]
Seeing loads of this one in the last 48 hours on 1.8.0 of `google-cloud-logging`

**Comment by colincadams** [comment]
Also seeing this with `google-cloud-logging=1.9.1`

**Comment by brunoais** [comment]
@tseaver Any way of changing that, at our own responsibility so, for example, 1 retry is done for such errors?

**Comment by tseaver** [comment]
@brunoais You'd need to poke at some internals.  Something like (untested):

```python
from google.api_core.exceptions import ServiceUnavailable
from google.api_core.gapic_v1.method import wrap_method
from google.api_core import retry 
from google.cloud.logging_v2 import LoggingServiceV2Client

client = LoggingServiceV2Client()
predicate = retry.if_exception(ServiceUnavailable)
wle_retry = retry.Retry(predicate, inital=5, deadline=5)
client._inner_api_calls['write_log_entries'] = wrap_method(
    client.transport.write_log_entries,
    default_retry=wle_retry,
    default_timeout=client._method_configs["WriteLogEntries"].timeout,
    client_info=client._client_info,
)
```

Note that the retry mechanism isn't really built around a maximum number of tries, but rather a maximum time (along with initial delay and multiplier).  See its [docs](https://googleapis.github.io/google-cloud-python/latest/core/retry.html).

**Comment by tseaver** [comment]
> How much future proof would your example code be? Would it be equivalent to the main API?

The `_inner_api_stubs` mapping is lazily initialized on first use:  the example I posted is taken from [there](https://github.com/googleapis/google-cloud-python/blob/3fc8616b98b855fcf86ca4cafe8c23ba6aa3dfad/logging/google/cloud/logging_v2/gapic/logging_service_v2_client.py#L380-L387).

As long as the GAPIC code generation strategy doesn't change, that example should still work.

**Comment by brunoais** [comment]
> As long as the GAPIC code generation strategy doesn't change, that example should still work.
Thank you. I'll try that when I can.

**Comment by guillem-sopra** [comment]
Any news on this? We are seeing the same error with the exact same confguration :worried:

**Comment by tseaver** [comment]
@guillem-sopra As of `google-cloud-logging 1.10.0` (released 2019-01-17), the `WriteLogEntries` API is marked as `idempotent` for retries, which allows retries on `DEADLINE_EXCEEDED`, `INTERNAL`, and `UNAVAILABLE` status codes.  Can you try upgrading?

**Comment by tseaver** [comment]
I'm closing this issue because of that fix, but please feel free to follow up with more information.
