### ISSUE TITLE
[Firestore] cannot order by document id and use start_after/start_at/etc.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6652]
Likely will be related #6555.

`documents = collection.order_by('__name__').get()` works fine. 

However, if you try `documents = collection.order_by('__name__').start_after(last_read_row).get()` this will error with 

```
Traceback (most recent call last):
  File "/Users/crwilcox/.pyenv/versions/3.7.0/lib/python3.7/site-packages/google/cloud/firestore_v1beta1/query.py", line 736, in _cursor_pb
    value = _helpers.get_nested_value(field_path, data)
  File "/Users/crwilcox/.pyenv/versions/3.7.0/lib/python3.7/site-packages/google/cloud/firestore_v1beta1/_helpers.py", line 754, in get_nested_value
    raise KeyError(msg)
KeyError: "'__name__' is not contained in the data"
```

**Comment by tseaver** [comment]
Actual semantics are documented in #6665, including links to the conformance tests.  Closing this one in its favor.
