### ISSUE TITLE
ImportError : module 'main' has no attribute app

### ISSUE THREAD

**Issue by dfossa** [googleapis/google-cloud-python#7118]
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/350d926c06a7e859/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/350d926c06a7e859/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 302, in _LoadHandler
    raise err
ImportError: <module 'main' from '/base/data/home/apps/s~python-tchat/20190111t090500.415321704346602689/main.py'> has no attribute app

**Comment by dfossa** [comment]
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/350d926c06a7e859/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/350d926c06a7e859/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 302, in _LoadHandler
    raise err
ImportError: <module 'main' from '/base/data/home/apps/s~python-tchat/20190111t090500.415321704346602689/main.py'> has no attribute app

**Comment by tseaver** [comment]
This repository is about the Python client libraries for the Google Cloud APIs, not Google AppEngine.  Please use one of the [GAE support resources](https://cloud.google.com/appengine/community) to resolve your issue.
