### ISSUE TITLE
Can't use with Storage

### ISSUE THREAD

**Issue by odscjames** [googleapis/google-cloud-python#7209]
#### Environment details

  - OS: ubuntu-bionic 
  - Python version: 3.6.7
  - pip version: 19.0.1

* google-api-core==1.7.0
* google-api-python-client==1.7.7
* google-auth==1.6.2
* google-auth-httplib2==0.0.3
* google-cloud-core==0.29.1
* google-cloud-storage==1.13.2
* google-resumable-media==0.3.2
* googleapis-common-protos==1.5.6

#### Steps to reproduce

```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.oauth2 import service_account
>>> from google.cloud import storage
>>> credentials = service_account.Credentials.from_service_account_file('credentials.json')
>>> client = storage.Client(credentials=credentials)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vagrant-scrape/.ve/lib/python3.6/site-packages/google/cloud/storage/client.py", line 73, in __init__
    project=project, credentials=credentials, _http=_http
  File "/vagrant-scrape/.ve/lib/python3.6/site-packages/google/cloud/client.py", line 223, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/vagrant-scrape/.ve/lib/python3.6/site-packages/google/cloud/client.py", line 175, in __init__
    project = self._determine_default(project)
  File "/vagrant-scrape/.ve/lib/python3.6/site-packages/google/cloud/client.py", line 190, in _determine_default
    return _determine_default_project(project)
  File "/vagrant-scrape/.ve/lib/python3.6/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/vagrant-scrape/.ve/lib/python3.6/site-packages/google/auth/_default.py", line 294, in default
    credentials, project_id = checker()
  File "/vagrant-scrape/.ve/lib/python3.6/site-packages/google/auth/_default.py", line 165, in _get_explicit_environ_credentials
    os.environ[environment_vars.CREDENTIALS])
  File "/vagrant-scrape/.ve/lib/python3.6/site-packages/google/auth/_default.py", line 89, in _load_credentials_from_file
    'File {} was not found.'.format(filename))
google.auth.exceptions.DefaultCredentialsError: File {"type": "service_account",  ......... the entire contents of my credentials.json file that I obviously won't list here ...... "} was not found.

```

**Comment by tseaver** [comment]
`google.cloud.client.ClientProject` is passing along the `project` to `google.cloud.client._ClientProjectMixin` without  using / checking the project from the explicitly-passed credentials.

@odscjames As a workaround, you can set the environment variable, `GOOGLE_CLOUD_PROJECT`, to the project ID in your credentials.  Or you can pass the project from the credentials, e.g.:

```python
client = storage.Client(credentials=credentials, project=credentials.project_id)
```

**Comment by tseaver** [comment]
Actually, the straightforward / intended way to address this goal is to use `storage.Client.from_service_account_json`, e.g.:

```python
>>> from google.cloud import storage
>>> client = storage.Client.from_service_account_json('credentials.json')
```
