### ISSUE TITLE
Logging: Crash if using non default log level names with CloudLoggingHandler

### ISSUE THREAD

**Issue by josteinl** [googleapis/google-cloud-python#7213]
#### Environment details

1. OS: Ubuntu 18.04.1 LTS (ubuntu-bionic)
2. Python version: 3.6.7
3. google-cloud-logging version: 1.10.0

#### Steps to reproduce

Use GCP logging with non default log level name. Crashes every time. See code below using the non default log level name 'ERR'.

#### Code example

```python
import logging

from google.cloud import logging as cloud_logging
from google.cloud.logging.handlers import CloudLoggingHandler

client = cloud_logging.Client()

handler = CloudLoggingHandler(client)
cloud_logger = logging.getLogger("cloudLogger")
cloud_logger.setLevel(logging.INFO)
cloud_logger.addHandler(handler)

cloud_logger.error("First bad news")  # See this in GCP console if the two lines below is not run

logging.addLevelName(logging.ERROR, "ERR")
cloud_logger.error("More bad news")  # <- Crash if this and the line above is run

```

#### Output
```
Program shutting down, attempting to send 2 queued log entries to Stackdriver Logging...
Waiting up to 5 seconds.
Failed to submit 2 logs.
Traceback (most recent call last):
  File "<my virtualenv>/lib/python3.6/site-packages/google/protobuf/json_format.py", line 691, in _ConvertScalarFieldValue
    number = int(value)
ValueError: invalid literal for int() with base 10: 'ERR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<my virtualenv>/lib/python3.6/site-packages/google/protobuf/json_format.py", line 549, in _ConvertFieldValuePair
    setattr(message, field.name, _ConvertScalarFieldValue(value, field))
  File "<my virtualenv>/lib/python3.6/site-packages/google/protobuf/json_format.py", line 695, in _ConvertScalarFieldValue
    value, field.enum_type.full_name))
google.protobuf.json_format.ParseError: Invalid enum value ERR for enum type google.logging.type.LogSeverity.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<my virtualenv>/lib/python3.6/site-packages/google/cloud/logging/handlers/transports/background_thread.py", line 122, in _safely_commit_batch
    batch.commit()
  File "<my virtualenv>/lib/python3.6/site-packages/google/cloud/logging/logger.py", line 383, in commit
    client.logging_api.write_entries(entries, **kwargs)
  File "<my virtualenv>/lib/python3.6/site-packages/google/cloud/logging/_gapic.py", line 125, in write_entries
    entry_pbs = [_log_entry_mapping_to_pb(entry) for entry in entries]
  File "<my virtualenv>/lib/python3.6/site-packages/google/cloud/logging/_gapic.py", line 125, in <listcomp>
    entry_pbs = [_log_entry_mapping_to_pb(entry) for entry in entries]
  File "<my virtualenv>/lib/python3.6/site-packages/google/cloud/logging/_gapic.py", line 464, in _log_entry_mapping_to_pb
    ParseDict(mapping, entry_pb)
  File "<my virtualenv>/lib/python3.6/site-packages/google/protobuf/json_format.py", line 421, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "<my virtualenv>/lib/python3.6/site-packages/google/protobuf/json_format.py", line 452, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "<my virtualenv>/lib/python3.6/site-packages/google/protobuf/json_format.py", line 552, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse severity field: Invalid enum value ERR for enum type google.logging.type.LogSeverity.
Sent all pending logs.

Process finished with exit code 0

```

**Comment by tseaver** [comment]
@josteinl Thanks for the report:  I was able to reproduce the failure using your script.  With the patch in #8837, the script succeeds, and both log entries are sent.
