### ISSUE TITLE
Google Ads: Failure to print FieldMask to Json string

### ISSUE THREAD

**Issue by bobhancock** [googleapis/google-cloud-python#7288]
OS: gLinux
Python 3.5

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version
3. Python version and virtual environment information: `python --version`
4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`

#### Steps to reproduce

  In the Python client library we serialize response messages to JSON for the purposes of logging. We're currently using the "google.protobuf.json_format.MessageToJson" helper to do this. When serializing a FieldMask this function calls the message's ToJsonString method (https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/json_format.py#L335). If the value of a field in the message contains a number, (i.e. "metrics.video_quartile_25_rate") this serialization will fail because it attempts to convert the value from snake_case to camelCase (https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/well_known_types.py#L412).

1. I'm not sure why it's attempting to convert the value to camelCase here. It makes sense for the keys, but not values.
2. Is there a way to tell the MessageToJson function to ignore such values?

#### Code example

```python
# example is forthcoming
```

#### Stack trace
Traceback (most recent call last):
  File "check_for_video_quartile_25_rate.py", line 72, in <module>
    campaign_id=args.campaign_id)
  File "check_for_video_quartile_25_rate.py", line 38, in main
    for row in results:
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 204, in _items_iter
    for page in self._page_iter(increment=False):
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 235, in _page_iter
    page = self._next_page()
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 526, in _next_page
    response = self._method(self._request)
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/grpc/_interceptor.py", line 215, in __call__
    wait_for_ready=wait_for_ready)
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/grpc/_interceptor.py", line 245, in _with_call
    return call.result(), call
  File "/usr/local/google/home/benkarl/venvs/simply-local/local/lib/python2.7/site-packages/grpc/_interceptor.py", line 121, in result
    raise self._exception
google.protobuf.internal.well_known_types.Error: Fail to print FieldMask to Json string: The character after a "_" must be a lowercase letter in path name metrics.video_quartile_25_rate.

Thanks!

**Comment by tseaver** [comment]
@bobhancock I'm having trouble tying the problem in your description to the traceback you post.  Can you show the code in `check_for_video_quartile_25_rate.py`?  In particular, what `google-cloud-*` library is returning that iterator?

**Comment by tseaver** [comment]
FWIW, we have no API-invoking method in this repository which takes a `campaign_id` argument.  Please reopen if you can provide more information about how to provoke this issue (which library you are using in the top-level script, for instance).
