### ISSUE TITLE
BigQuery: table partition expiration cannot be unset

### ISSUE THREAD

**Issue by igor47** [googleapis/google-cloud-python#7340]
Using: python 3.7.1 on OSX
Version: google-cloud-bigquery==1.8.0

There seems to be no way to unset `partition_expiration` once it's set.

Trying by updating `partition_expiration` to 0:
```
>>> w = BQWriter('dovetail_v4')
>>> t = w.table
>>> t.partition_expiration
604800005
>>> t.partition_expiration = 0
>>> w.bq_client.update_table(t, ['partition_expiration'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/igor.serebryany/.virtualenvs/datapipes/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 505, in update_table
    retry, method="PATCH", path=table.path, data=partial, headers=headers
  File "/Users/igor.serebryany/.virtualenvs/datapipes/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 382, in _call_api
    return call()
  File "/Users/igor.serebryany/.virtualenvs/datapipes/lib/python3.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/Users/igor.serebryany/.virtualenvs/datapipes/lib/python3.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/Users/igor.serebryany/.virtualenvs/datapipes/lib/python3.7/site-packages/google/cloud/_http.py", line 319, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 PATCH https://www.googleapis.com/bigquery/v2/projects/aclima-test/datasets/datapipes/tables/dovetail_v4: TTL for interval partition must be a positive number.
```

trying with `partition_expiration = None`:

```

>>> t.partition_expiration = None
>>> w.bq_client.update(t, ['partition_expiration'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Client' object has no attribute 'update'
>>> w.bq_client.update_table(t, ['partition_expiration'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/igor.serebryany/.virtualenvs/datapipes/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 505, in update_table
    retry, method="PATCH", path=table.path, data=partial, headers=headers
  File "/Users/igor.serebryany/.virtualenvs/datapipes/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 382, in _call_api
    return call()
  File "/Users/igor.serebryany/.virtualenvs/datapipes/lib/python3.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/Users/igor.serebryany/.virtualenvs/datapipes/lib/python3.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/Users/igor.serebryany/.virtualenvs/datapipes/lib/python3.7/site-packages/google/cloud/_http.py", line 319, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 PATCH https://www.googleapis.com/bigquery/v2/projects/aclima-test/datasets/datapipes/tables/dovetail_v4: Invalid value at 'table.time_partitioning.expiration_ms.value' (TYPE_INT64), "None"
```

I'm working around this for now by setting my expiration to `2 ^ 63 - 1` but it would be nice to be able to unset the expiration once it's set

**Comment by tseaver** [comment]
The setter for `Table.partition_expiration` does not, indeed, support clearing the expiration.  However, that property is deprecated in favor of `Table.time_partitioning`, whose setter expects an instance of `google.cloud.bigquery.table.TimePartitioning`.  The supported way to do what you want is thus:

```python
time_partitioning = table.time_partitioning
time_partitioning.expiration_ms = None
table.time_partitioning = time_partitioning
```
