### ISSUE TITLE
RetryError outputs too large message.

### ISSUE THREAD

**Issue by tokibito** [googleapis/google-cloud-python#7375]
We are using Dialogflow v2 Python client.
When an RPC RetryError occurs, it output the Traceback log.
And we are forwarding logs to Google Cloud Logging.
If the RPC argument data is long, the output size is too large.
Google Cloud Logging has a limit of 100 kb in entry size, we encountered a problem that traceback can not be recorded.
I think that it is better to shorten the cause which is too long.

This Traceback occurs "`google.api_core.exceptions.InvalidArgument: 400 Log entry with size 9.89M exceeds maximum size of 110.0K`".

```
Traceback (most recent call last):
  File "/home/vmagent/app/synchronize/main.py", line 42, in export_to_dialogflow
    exporter.restore()
  File "/home/vmagent/app/export/main.py", line 21, in restore
    result = self._restore_to_dialogflow(zip_binary)
  File "/home/vmagent/app/export/main.py", line 53, in _restore_to_dialogflow
    response = client.restore_agent(parent, agent_content=zip_binary)
  File "/env/lib/python3.7/site-packages/dialogflow_v2/gapic/agents_client.py", line 700, in restore_agent
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/env/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/env/lib/python3.7/site-packages/google/api_core/retry.py", line 199, in retry_target
    last_exc, File "<string>", line 3, in raise_from google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling functools.partial(<function _wrap_unary_errors.<locals>.error_remapped_callable at 0x7f0053600d90>, parent: "projects/mariana-grand-service" agent_content: "PK\003\004\024\000\000\000\000\000\000\000!\000\2437\256x\030\000\000\000\030\000\000\000\014\000\000\000package.json{\n \"version\": \"1.0.0\"\n}PK\003\004\024\000\000\000\000\000\000\000!\000\206yQr\017
    (This output lasts about 10MB)
```

**Comment by tseaver** [comment]
@tokibito The library really can't shorten the traceback arbitrarily:  it might cause important debugging information to be lost.  That kind of policy can only be applied at the application level.  In your case, you probably need to configure your log format / handler to trim the output.
