### ISSUE TITLE
Can't install google-cloud-bigtable 0.32.1 in setup.py

### ISSUE THREAD

**Issue by smacpher-myst** [googleapis/google-cloud-python#7435]
Hi! I'm seeing the following error when trying to install `google-cloud-bigtable==0.32.1` through `setup.py`: `pkg_resources.UnknownExtra: googleapis-common-protos 1.6.0b8 has no such extra feature 'grpc'`. 

I did find a couple of workarounds from looking at previous related issues:
- installing through `pip`
- pinning `googleapis-common-protos==1.5.8`

It's strange that setuptools is grabbing a "pre-release" version of `googleapis-common-protos` from PyPi (1.6.0b8) but `pip` grabs the "current" version (1.5.8)...or is this the expected behavior?

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
**Bigtable**

2. OS type and version
**macOS High Sierra 10.13.5**

3. Python version and virtual environment information: `python --version`
**Python 2.7.15** running in a new virtualenv

4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`
**google-cloud-bigtable==0.32.1**

#### Steps to reproduce
Here's my `setup.py`:

```python

from setuptools import setup

setup(
	name='foo',
	version='0.0.1',
	install_requires=[
		'google-cloud-bigtable==0.32.1',
	],
	packages=['foo'],
)

```

1. pip install virtaulenv
2. virtualenv venv && source venv/bin/activate
3. python setup.py install

#### Stack trace
Here's the full stack trace:

```
$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to foo.egg-info/requires.txt
writing foo.egg-info/PKG-INFO
writing top-level names to foo.egg-info/top_level.txt
writing dependency_links to foo.egg-info/dependency_links.txt
reading manifest file 'foo.egg-info/SOURCES.txt'
writing manifest file 'foo.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.13-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.13-x86_64/egg
creating build/bdist.macosx-10.13-x86_64/egg/foo
copying build/lib/foo/__init__.py -> build/bdist.macosx-10.13-x86_64/egg/foo
byte-compiling build/bdist.macosx-10.13-x86_64/egg/foo/__init__.py to __init__.pyc
creating build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying foo.egg-info/PKG-INFO -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying foo.egg-info/SOURCES.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying foo.egg-info/dependency_links.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying foo.egg-info/requires.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying foo.egg-info/top_level.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/foo-0.0.1-py2.7.egg' and adding 'build/bdist.macosx-10.13-x86_64/egg' to it
removing 'build/bdist.macosx-10.13-x86_64/egg' (and everything under it)
Processing foo-0.0.1-py2.7.egg
Copying foo-0.0.1-py2.7.egg to /Users/smacpher/venv/lib/python2.7/site-packages
Adding foo 0.0.1 to easy-install.pth file

Installed /Users/smacpher/venv/lib/python2.7/site-packages/foo-0.0.1-py2.7.egg
Processing dependencies for foo==0.0.1
Searching for google-cloud-bigtable==0.32.1
Reading https://pypi.org/simple/google-cloud-bigtable/
Downloading https://files.pythonhosted.org/packages/15/81/df8ec275ea39885744ec058f2bbcf393669a423eac18cc6a7707dc4b77d9/google_cloud_bigtable-0.32.1-py2.py3-none-any.whl#sha256=ac148f37370e0ff1581eb0c836f6133d4384a9d89e6c7d47531f09e87060cb27
Best match: google-cloud-bigtable 0.32.1
Processing google_cloud_bigtable-0.32.1-py2.py3-none-any.whl
Installing google_cloud_bigtable-0.32.1-py2.py3-none-any.whl to /Users/smacpher/venv/lib/python2.7/site-packages
writing requirements to /Users/smacpher/venv/lib/python2.7/site-packages/google_cloud_bigtable-0.32.1-py2.7.egg/EGG-INFO/requires.txt
Adding google-cloud-bigtable 0.32.1 to easy-install.pth file

Installed /Users/smacpher/venv/lib/python2.7/site-packages/google_cloud_bigtable-0.32.1-py2.7.egg
Searching for grpc-google-iam-v1<0.12dev,>=0.11.4
Reading https://pypi.org/simple/grpc-google-iam-v1/
Downloading https://files.pythonhosted.org/packages/9b/28/f26f67381cb23e81271b8d66c00a846ad9d25a909ae1ae1df8222fad2744/grpc-google-iam-v1-0.11.4.tar.gz#sha256=5009e831dcec22f3ff00e89405249d6a838d1449a46ac8224907aa5b0e0b1aec
Best match: grpc-google-iam-v1 0.11.4
Processing grpc-google-iam-v1-0.11.4.tar.gz
Writing /var/folders/8z/tgcz3s3d4775nxgfhfcpzjdm0000gn/T/easy_install-51c1_B/grpc-google-iam-v1-0.11.4/setup.cfg
Running grpc-google-iam-v1-0.11.4/setup.py -q bdist_egg --dist-dir /var/folders/8z/tgcz3s3d4775nxgfhfcpzjdm0000gn/T/easy_install-51c1_B/grpc-google-iam-v1-0.11.4/egg-dist-tmp-38j_DZ
zip_safe flag not set; analyzing archive contents...
Copying grpc_google_iam_v1-0.11.4-py2.7.egg to /Users/smacpher/venv/lib/python2.7/site-packages
Adding grpc-google-iam-v1 0.11.4 to easy-install.pth file

Installed /Users/smacpher/venv/lib/python2.7/site-packages/grpc_google_iam_v1-0.11.4-py2.7.egg
Searching for google-cloud-core<0.30dev,>=0.29.0
Reading https://pypi.org/simple/google-cloud-core/
Downloading https://files.pythonhosted.org/packages/0c/f2/3c225e7a69cb27d283b68bff867722bd066bc1858611180197f711815ea5/google_cloud_core-0.29.1-py2.py3-none-any.whl#sha256=9bee63e0991be9801a4baf0b7841cf54f86c6e7fec922f45ea74cd4032ed4ee4
Best match: google-cloud-core 0.29.1
Processing google_cloud_core-0.29.1-py2.py3-none-any.whl
Installing google_cloud_core-0.29.1-py2.py3-none-any.whl to /Users/smacpher/venv/lib/python2.7/site-packages
writing requirements to /Users/smacpher/venv/lib/python2.7/site-packages/google_cloud_core-0.29.1-py2.7.egg/EGG-INFO/requires.txt
Adding google-cloud-core 0.29.1 to easy-install.pth file

Installed /Users/smacpher/venv/lib/python2.7/site-packages/google_cloud_core-0.29.1-py2.7.egg
Searching for google-api-core[grpc]<2.0.0dev,>=1.6.0
Reading https://pypi.org/simple/google-api-core/
Downloading https://files.pythonhosted.org/packages/55/8d/02cd1468659994a39b1aced38fecb06885c988d79aaafd8d456d09571871/google_api_core-1.8.0-py2.py3-none-any.whl#sha256=c6d834143a2bea4de8d1161b5460fd362457db40c55ea9ccbe672e5602e330af
Best match: google-api-core 1.8.0
Processing google_api_core-1.8.0-py2.py3-none-any.whl
Installing google_api_core-1.8.0-py2.py3-none-any.whl to /Users/smacpher/venv/lib/python2.7/site-packages
writing requirements to /Users/smacpher/venv/lib/python2.7/site-packages/google_api_core-1.8.0-py2.7.egg/EGG-INFO/requires.txt
Adding google-api-core 1.8.0 to easy-install.pth file

Installed /Users/smacpher/venv/lib/python2.7/site-packages/google_api_core-1.8.0-py2.7.egg
Searching for googleapis-common-protos[grpc]<2.0.0dev,>=1.5.2
Reading https://pypi.org/simple/googleapis-common-protos/
Downloading https://files.pythonhosted.org/packages/a5/7d/a0c06527f053b7f46c0f745700a0074b573c2bd079f99c6542751938d204/googleapis-common-protos-1.6.0b8.tar.gz#sha256=3fd458e7100c9823f88c8465ea865171f80f052cbe6b19b5bedfb32d23b6fed6
Best match: googleapis-common-protos 1.6.0b8
Processing googleapis-common-protos-1.6.0b8.tar.gz
Writing /var/folders/8z/tgcz3s3d4775nxgfhfcpzjdm0000gn/T/easy_install-n4nIIj/googleapis-common-protos-1.6.0b8/setup.cfg
Running googleapis-common-protos-1.6.0b8/setup.py -q bdist_egg --dist-dir /var/folders/8z/tgcz3s3d4775nxgfhfcpzjdm0000gn/T/easy_install-n4nIIj/googleapis-common-protos-1.6.0b8/egg-dist-tmp-9YaSLv
zip_safe flag not set; analyzing archive contents...
Copying googleapis_common_protos-1.6.0b8-py2.7.egg to /Users/smacpher/venv/lib/python2.7/site-packages
Adding googleapis-common-protos 1.6.0b8 to easy-install.pth file

Installed /Users/smacpher/venv/lib/python2.7/site-packages/googleapis_common_protos-1.6.0b8-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    packages=['foo'],
  File "/Users/smacpher/venv/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/smacpher/venv/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/smacpher/venv/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Users/smacpher/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/smacpher/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/smacpher/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/smacpher/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/smacpher/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 794, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/Users/smacpher/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2708, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: googleapis-common-protos 1.6.0b8 has no such extra feature 'grpc'
```

Let me know if any additional information is needed! Thanks in advance!

**Comment by tseaver** [comment]
Thanks for the report!  The issue here is with `grpc-google-iam-v1`, which has the dependency on the missing `[grpc]` extra in `googleapis-common-protos`.  Running `python setup.py install` selects for the latest version of `googleapis-common-protos`, which does not have the extra.  For now, I'd recommend installing with `pip`, i.e.:

```bash
pip install .
```

Because `pip` won't install beta / prerelease versions by default.  I'm going to raise this issue to the team(s) who maintain `grpc-google-iam-v1` and `googleapis-common-protos`.

**Comment by tseaver** [comment]
See also #5703.  

@lukesneeringer says he will release another beta of `googleapis-common-protos` with the `grpc` extra added back.

**Comment by tseaver** [comment]
And it is released:  https://pypi.org/project/googleapis-common-protos/1.6.0b9/

**Comment by smacpher-myst** [comment]
Ahh I see -- thanks for the explanation and the fix :)!
