### ISSUE TITLE
Docs build is broken

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-python#7611]
https://circleci.com/gh/googleapis/google-cloud-python/11848

```
reading sources... [ 44%] firestore/collection

Traceback (most recent call last):
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/application.py", line 338, in build
    self.builder.build_update()
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 326, in build_update
    len(to_build))
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 339, in build
    updated_docnames = set(self.read())
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 445, in read
    self._read_serial(docnames)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 467, in _read_serial
    self.read_doc(docname)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/io.py", line 323, in read_doc
    pub.publish()
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/io.py", line 116, in read
    self.parse()
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/parsers.py", line 94, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/autodoc/directive.py", line 135, in run
    documenter.generate(more_content=self.content)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 751, in generate
    self.document_members(all_members)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 672, in document_members
    check_module=members_check_module and not isattr)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 1204, in generate
    all_members=all_members)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 751, in generate
    self.document_members(all_members)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 1192, in document_members
    super().document_members(all_members)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 672, in document_members
    check_module=members_check_module and not isattr)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 748, in generate
    self.add_content(more_content)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 486, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 454, in process_doc
    self.options, docstringlines)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/application.py", line 441, in emit
    return self.events.emit(event, self, *args)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/events.py", line 76, in emit
    results.append(callback(*args))
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py", line 381, in _process_docstring
    obj, options)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/napoleon/docstring.py", line 176, in __init__
    self._parse()
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/napoleon/docstring.py", line 578, in _parse
    lines = self._sections[section.lower()](section)
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/napoleon/docstring.py", line 703, in _parse_raises_section
    m = self._name_rgx.match(_type).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'

Exception occurred:
  File "/var/code/gcp/.nox/docs-3-6/lib/python3.6/site-packages/sphinx/ext/napoleon/docstring.py", line 703, in _parse_raises_section
    m = self._name_rgx.match(_type).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
The full traceback has been saved in /tmp/sphinx-err-61wa8uj8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
nox > Command bash ./test_utils/scripts/update_docs.sh failed with exit code 2
nox > Session docs-3.6 failed.
Exited with code 1
```

**Comment by tseaver** [comment]
Sphinx just [released a 2.0 version](https://pypi.org/project/Sphinx/2.0.0/) (see the [release notes](http://www.sphinx-doc.org/en/master/changes.html#release-2-0-0-released-mar-29-2019) for incompatible changes).

We should likely pin `Sphinx < 2.0dev`.
