### ISSUE TITLE
Firestore: Field path keys are not expanded for dicts used as cursors.

### ISSUE THREAD

**Issue by schmidt-sebastian** [googleapis/google-cloud-python#7756]
Copied from @torresalmonte's issue at https://github.com/firebase/firebase-admin-python/issues/281

```
l050ZZ1bAsBddd7hE1GD => {'wordcount': {'page3': 130, 'page2': 120, 'page1': 100}, 'availability_date': DatetimeWithNanoseconds(2019, 3, 4, 6, 0, tzinfo=<UTC>), 'count': 100}
JCn6BxwfEDIvirnkMyOf => {'wordcount': {'page3': 180, 'page2': 120, 'page1': 150}, 'availability_date': DatetimeWithNanoseconds(2019, 3, 4, 6, 0, tzinfo=<UTC>), 'count': 150}
nfW0ybNz4WPGWtikfVK2 => {'count': 200, 'wordcount': {'page3': 50, 'page2': 100, 'page1': 200}}
last value: 200
Traceback (most recent call last):
  File "/home/ctorres/.local/lib/python3.5/site-packages/google/cloud/firestore_v1/query.py", line 642, in _normalize_cursor
    values.append(field_path_module.get_nested_value(order_key, data))
  File "/home/ctorres/.local/lib/python3.5/site-packages/google/cloud/firestore_v1/field_path.py", line 243, in get_nested_value
    raise KeyError(msg)
KeyError: "'wordcount' is not contained in the data"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "firestore_pagination.py", line 28, in <module>
    docs_list = list(docs)
  File "/home/ctorres/.local/lib/python3.5/site-packages/google/cloud/firestore_v1/query.py", line 736, in stream
    self._to_protobuf(),
  File "/home/ctorres/.local/lib/python3.5/site-packages/google/cloud/firestore_v1/query.py", line 675, in _to_protobuf
    start_at = self._normalize_cursor(self._start_at, orders)
  File "/home/ctorres/.local/lib/python3.5/site-packages/google/cloud/firestore_v1/query.py", line 645, in _normalize_cursor
    raise ValueError(msg)
ValueError: The "order by" field path 'wordcount.page1' is not present in the cursor data {'wordcount.page1': 200}. All fields sent to ``order_by()`` must be present in the fields if passed to one of ``start_at()`` / ``start_after()`` / ``end_before()`` / ``end_at()`` to define a cursor.
```

For repo steps, please look at the original GitHub issue.

**Comment by tseaver** [comment]
The issue in the repro script is here:

```python
next_query = pages_ref.order_by(u'wordcount.page1').start_after({u'wordcount.page1': last_value}).limit(3)
```

The dict used as a "cursor" (passed to `start_after`) is supposed to match the document structure:  the "field path" notation is not being expanded.

[This gist](https://gist.github.com/tseaver/f23119dd18f88fe5c06937c687a51282) reproduces the issue using only `google-cloud-firestore` (no `firebase`).

@BenWhitehead Can you please point to the place in the spec for `Query` which defines expected behavior for a `dict` cursor?  If field-path keys are expected to be expanded, then we need a conformance test which asserts that.
