### ISSUE TITLE
TypeError: after updating google-cloud-firestore lib

### ISSUE THREAD

**Issue by sabiv** [googleapis/google-cloud-python#7796]
I have just updated the google-cloud-firestore Python library and my code stopped working. I get the below error right after running the code. I didn't change anything in the implementation, it's certain that the update did something.

```
Traceback (most recent call last):
  File "F:\com\app\update_page.py", line 31, in <module>
    from firebase_admin import firestore
  File "C:\Users\sabiv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\firebase_admin\firestore.py", line 22, in <module>
    from google.cloud import firestore # pylint: disable=import-error,no-name-in-module
  File "C:\Users\sabiv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\google\cloud\firestore.py", line 18, in <module>
    from google.cloud.firestore_v1 import __version__
  File "C:\Users\sabiv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\google\cloud\firestore_v1\__init__.py", line 21, in <module>
    from google.cloud.firestore_v1 import types
  File "C:\Users\sabiv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\google\cloud\firestore_v1\types.py", line 29, in <module>
    from google.cloud.firestore_v1.proto import common_pb2
  File "C:\Users\sabiv\AppData\Local\Programs\Python\Python35-32\lib\site-packages\google\cloud\firestore_v1\proto\common_pb2.py", line 33, in <module>
    google_dot_api_dot_annotations__pb2.DESCRIPTOR,
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
```
I would really appreciate if somebody could tell me if there is anything else should be installed, or if there is any fix for this problem.  Any other help or tips are welcomed. Thanks

**Comment by sabiv** [comment]
After updating to the newest version of protobuf, the error disappeared and the code works fine. Problem solved.
