### ISSUE TITLE
Storage: can't use with frozen project.

### ISSUE THREAD

**Issue by Maxime-Champain** [googleapis/google-cloud-python#7804]
Hello i'm having trouble using cx_freeze with cloud-storage api python

#### Environment details

1. Cloud-Storage
2. win7 64bits
3. Python 3.7.2 with or without venv still the same error (in this case no venv)
4. google-cloud-storage 1.15.0

#### Steps to reproduce

  First froze the code by using cx_freeze

```PYTHON
import sys
from cx_Freeze import setup, Executable

# Dependencies are automatically detected, but it might need fine tuning.
options = {
    'build_exe': {
        'packages': ['os', 'sys', 'time', 'googleapiclient', 'httplib2', 'logging', 'sqlite3', 'configparser', 'oauth2client', 'random', 'colorama', 'json', 'google', 'pkg_resources._vendor', 'pkg_resources.extern', 'idna'],
        'excludes': ['tkinter'],
        'include_files': ['credentials.json', 'client_secret.json', 'log/', 'libcrypto-1_1.dll', 'libssl-1_1.dll', 'migration.sqlite3', 'export.txt', 'exported.txt', 'skipped.txt', 'function/'],
        'include_msvcr': True
    }
}
# GUI applications require a different base on Windows (the default is for a
# console application).
base = None
if sys.platform == "win32":
    base = "Console"

executables = [
    Executable('main.py', base=base, icon='ico.ico')
]

setup(
    name='app',
    version='3.0',
    description='appTools',
    options=options,
    executables=executables
)
```

this is the script where i specify dependencies.

Note that googleapiclient working fine with cx_freeze but not cloud-storage 

#### Code Example

My code is a simple use of upload methods to cloud-storage.

Visibly it happen in this file : 

```PYTHON
import os

from google.cloud import storage

root = os.path.dirname(os.path.realpath(__file__))


def oauth():
    print("Google Cloud Storage Authentication")
    storage_client = storage.client.Client.from_service_account_json(os.path.join(root, 'credential.json'))
    return storage_client


CLOUDSTORAGE = oauth()
```

i use storage.client.Client but first i used storage.Client and the same happens

#### Stack trace
```
Traceback (most recent call last):
  File "D:\Users\maxime.champain\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "D:\Users\maxime.champain\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "main.py", line 18, in <module>
  File "main.py", line 13, in main
  File "F:\_Code\VWT.GTransfer\Gtransfer Modular\VWT.Gtransfer\build\exe.win32-3.7\function\service\userinterface\Console.py", line 8, in <module>
    from function.service.cloudstorage.Google_Cloud_Transfer import start_migration_cloud_storage
  File "F:\_Code\VWT.GTransfer\Gtransfer Modular\VWT.Gtransfer\build\exe.win32-3.7\function\service\cloudstorage\Google_Cloud_Transfer.py", line 3, in <module>
    from function.service.cloudstorage.Google_Cloud_Authentication import CLOUDSTORAGE
  File "F:\_Code\VWT.GTransfer\Gtransfer Modular\VWT.Gtransfer\build\exe.win32-3.7\function\service\cloudstorage\Google_Cloud_Authentication.py", line 3, in <module>
    from google.cloud import storage
  File "D:\Users\maxime.champain\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google\cloud\storage\__init__.py", line 36, in <module>
    __version__ = get_distribution("google-cloud-storage").version
  File "D:\Users\maxime.champain\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "D:\Users\maxime.champain\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "D:\Users\maxime.champain\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "D:\Users\maxime.champain\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
```

Thanks for your time and help!

**Comment by tseaver** [comment]
@Maxime-Champain I'm afraid that this is a bug with how `cx_freeze` is handling valid namespace packages:  e.g. see https://github.com/anthony-tuininga/cx_Freeze/issues/448.  There is nothing we can do in `google-cloud-storage` to address the problem.

**Comment by Maxime-Champain** [comment]
@tseaver Thank you. This helps me alot i just look for response for 2 days but i never thought to look the cx_freeze github. I found the solution. Stupid me :cry: . Thanks alot for your help.

**Comment by tseaver** [comment]
@Maxime-Champain I'm glad I was able to help.

**Comment by MarcelBeining** [comment]
> @tseaver Thank you. This helps me alot i just look for response for 2 days but i never thought to look the cx_freeze github. I found the solution. Stupid me  . Thanks alot for your help.

If you found the solution, please provide it to me, too as my issue anthony-tuininga/cx_Freeze#448 was never answered but simply closed...

**Comment by Maxime-Champain** [comment]
```PYTHON
import sys
import pkg_resources
from os.path import join, basename
from cx_Freeze import setup, Executable

# This part resolve my problem
def collect_dist_info(packages):
    """
    Recursively collects the path to the packages' dist-info.
    """
    if not isinstance(packages, list):
        packages = [packages]
    dirs = []
    for pkg in packages:
        distrib = pkg_resources.get_distribution(pkg)
        for req in distrib.requires():
            dirs.extend(collect_dist_info(req.key))
        print(distrib.egg_info)
        dirs.append((distrib.egg_info, join('Lib', basename(distrib.egg_info))))
    for i in ['credentials.json', 'client_secret.json', 'log/', 'libcrypto-1_1.dll', 'libssl-1_1.dll', 'migration.sqlite3', 'export.txt', 'exported.txt', 'skipped.txt', 'function/']:
        dirs.append(i)
    return dirs

# Dependencies are automatically detected, but it might need fine tuning.
# Here you use the function collect_dist_info() to import libraries like boto or googeapiclient
options = {
    'build_exe': {
        'packages': ['os', 'sys', 'time', 'googleapiclient', 'httplib2', 'html.parser', 'logging', 'sqlite3', 'configparser', 'oauth2client', 'random', 'colorama', 'json', 'google', 'pkg_resources._vendor', 'pkg_resources.extern', 'idna'],
        'excludes': ['tkinter'],
        'include_files': collect_dist_info(["google_cloud_storage", "boto3", "botocore"]),
        'include_msvcr': True
    }
}
```

This is the cx_freeze script that work for me. @MarcelBeining

**Comment by shahanaz873** [comment]
@Maxime-Champain I am trying to download some from google cloud, so I used same code which you used in setup.py for google-cloud-storage. 

[setup.py.txt](https://github.com/googleapis/google-cloud-python/files/3526472/setup.py.txt)


I am getting below error while building exe, can you please help me

cx_Freeze.freezer.ConfigError: path spec must be a list or tuple of length two

**Comment by Maxime-Champain** [comment]
@shahanaz873 This cx_freeze config is made for python 3.7 i don't know which version you use. Also, there are lot of code that you may don't need like 
```Python
for i in ['credentials.json', 'client_secret.json', 'log/', 'libcrypto-1_1.dll', 'libssl-1_1.dll', 'migration.sqlite3', 'export.txt', 'exported.txt', 'skipped.txt', 'function/']:
        dirs.append(i)
```
