### ISSUE TITLE
Storage: ImportError, cannot import name '_helpers'

### ISSUE THREAD

**Issue by dantuluri** [googleapis/google-cloud-python#8014]
#### Steps to reproduce

  1. Run `python`
  2. Enter 'from google.cloud import storage' to shell

#### What happened

Not sure why I'm getting this error. I've tried uninstalling google cloud sdk and reinstalling the pip packages, but it doesn't seem to work out. I've also setup authentication and followed all the steps written here: [https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-python](Google Cloud Storage Client Python).

In essence, I couldn't reproduce all the steps at [https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-python](Google Cloud Storage Client Python)

#### Stack trace
```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import storage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/google/cloud/storage/__init__.py", line 38, in <module>
    from google.cloud.storage.batch import Batch
  File "/anaconda3/lib/python3.6/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
ImportError: cannot import name '_helpers'
```
Thanks!

**Comment by tseaver** [comment]
It looks as though you somehow uninstalled `google-cloud-core`.  Can you please show the output of `python -m pip freeze` in your environment?  You might also try `python -m pip install google-cloud-core` to get it reinstalled.

**Comment by dantuluri** [comment]
#### Output of pip freeze
```
absl-py==0.3.0
alabaster==0.7.10
anaconda-client==1.6.14
anaconda-navigator==1.8.7
anaconda-project==0.8.2
appnope==0.1.0
appscript==1.0.1
asn1crypto==0.24.0
astor==0.7.1
astroid==1.6.3
astropy==3.0.2
atari-py==0.1.6
attrs==18.1.0
autograd==1.2
Babel==2.5.3
backcall==0.1.0
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.1.3
bokeh==0.12.16
boto==2.48.0
Bottleneck==1.2.1
box2d-py==2.3.5
cachetools==3.1.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
cloudpickle==0.5.2
clyent==1.2.2
colorama==0.3.9
conda==4.5.11
conda-build==3.10.5
conda-verify==2.0.0
contextlib2==0.5.5
cryptography==2.2.2
CVXcanon==0.1.1
cvxpy==1.0.6
cycler==0.10.0
Cython==0.28.2
cytoolz==0.9.0.1
dask==0.17.5
datashape==0.5.4
decorator==4.3.0
dill==0.2.8.2
distributed==1.21.8
Django==2.2
dnspython==1.16.0
docopt==0.6.2
docutils==0.14
ecos==2.0.5
entrypoints==0.2.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.4
Flask==1.0.2
Flask-Cors==3.0.4
future==0.16.0
gast==0.2.0
gevent==1.3.0
glfw==1.7.0
glob2==0.6
gmpy2==2.0.8
google-api-core==1.11.0
google-auth==1.6.3
google-cloud==0.34.0
google-cloud-core==1.0.0
google-cloud-datastore==1.7.4
google-cloud-speech==1.0.0
google-cloud-storage==1.15.1
google-resumable-media==0.3.2
googleapis-common-protos==1.6.0b9
greenlet==0.4.13
grip==4.5.2
grpcio==1.14.1
gym==0.10.9
h5py==2.7.1
heapdict==1.0.0
howmanypeoplearearound==0.4.0
html5lib==1.0.1
idna==2.6
imageio==2.3.0
imagesize==1.0.0
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
isort==4.3.4
itsdangerous==0.24
jdcal==1.4
jedi==0.12.0
Jinja2==2.10
joblib==0.13.0
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
llvmlite==0.23.1
lml==0.0.1
locket==0.2.0
lxml==4.2.1
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.2.2
mccabe==0.6.1
mistune==0.8.3
mkl-fft==1.0.0
mkl-random==1.0.1
mock==2.0.0
more-itertools==4.1.0
mpi4py==3.0.0
mpmath==1.0.0
msgpack-python==0.5.6
mujoco-py==1.50.1.56
multipledispatch==0.5.0
multiprocess==0.70.6.1
navigator-updater==0.2.1
nbconvert==5.3.1
nbformat==4.4.0
nbmerge==0.0.4
netifaces==0.10.9
networkx==2.1
nltk==3.3
nose==1.3.7
notebook==5.5.0
numba==0.38.0
numexpr==2.6.5
numpy==1.15.4
numpydoc==0.8.0
odo==0.5.1
olefile==0.45.1
opencv-python==3.4.3.18
openpyxl==2.5.3
osqp==0.4.1
packaging==17.1
pandas==0.23.0
pandocfilters==1.4.2
parso==0.2.0
partd==0.3.8
path-and-address==2.0.1
path.py==11.0.1
pathlib2==2.3.2
patsy==0.5.0
pbr==5.1.2
pep8==1.7.1
pexpect==4.5.0
pick==0.6.4
pickleshare==0.7.4
Pillow==5.1.0
pkginfo==1.4.2
plotly==3.1.1
pluggy==0.6.0
ply==3.11
powerlaw==1.4.6
progressbar2==3.38.0
prompt-toolkit==1.0.15
protobuf==3.6.1
psutil==5.4.5
ptyprocess==0.5.2
py==1.5.3
pyasn1==0.4.5
pyasn1-modules==0.2.5
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.1
pyexcel==0.5.8
pyexcel-io==0.5.8
pyflakes==1.6.0
pyglet==1.2.4
Pygments==2.2.0
pylint==1.8.4
pymongo==3.7.2
pyodbc==4.0.23
PyOpenGL==3.1.0
pyOpenSSL==18.0.0
pyparsing==2.2.0
PySocks==1.6.8
pytest==3.5.1
pytest-arraydiff==0.2
pytest-astropy==0.3.0
pytest-doctestplus==0.1.3
pytest-openfiles==0.3.0
pytest-remotedata==0.2.1
python-dateutil==2.7.3
python-utils==2.3.0
pytz==2018.4
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==17.0.0
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.4.1
requests==2.18.4
retrying==1.3.3
roboschool==1.0.38
rope==0.10.7
rsa==4.0
ruamel-yaml==0.15.35
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.1.0
scs==2.0.2
seaborn==0.8.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcollections==0.6.1
sortedcontainers==1.5.10
Sphinx==1.7.4
sphinxcontrib-websupport==1.0.1
-e git+https://github.com/dantuluri/roar.git@8f7d577b0fda9a59e8acc868994a73a0cfb57906#egg=spinup
spyder==3.2.8
SQLAlchemy==1.2.7
sqlparse==0.3.0
statsmodels==0.9.0
sympy==1.1.1
tables==3.4.3
tblib==1.3.2
tensorboard==1.12.2
tensorboardX==1.4
tensorflow==1.13.0rc0
tensorflow-estimator==1.13.0rc0
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
texttable==1.4.0
toolz==0.9.0
torch==0.4.1
torchvision==0.2.1
tornado==5.0.2
tqdm==4.28.1
traitlets==4.3.2
typing==3.6.4
unicodecsv==0.14.1
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.2.1
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.0.4
xlwings==0.11.8
xlwt==1.2.0
zict==0.1.3
```

#### What I did
I just reinstalled Cloud SDK to see if I accidentally deleted any important files. Even with the reinstallation and refreshing my terminal (sourcing bashrc), I'm still running into the same issue.

I also ran `python -m pip install google-cloud-core`, same issue.

**Comment by tseaver** [comment]
Trying to reproduce in a fresh virtual environment:

```bash
$ python3.6 -m venv /tmp/gcp/8014
$ /tmp/gcp/8014/bin/pip install --upgrade setuptools pip wheel
...
Successfully installed pip-19.1.1 setuptools-41.0.1 wheel-0.33.4
$ /tmp/gcp/8014/bin/pip install google-cloud-storage
...
Successfully installed cachetools-3.1.0 certifi-2019.3.9 chardet-3.0.4 google-api-core-1.11.0 google-auth-1.6.3 google-cloud-core-1.0.0 google-cloud-storage-1.16.0 google-resumable-media-0.3.2 googleapis-common-protos-1.5.10 idna-2.8 protobuf-3.7.1 pyasn1-0.4.5 pyasn1-modules-0.2.5 pytz-2019.1 requests-2.22.0 rsa-4.0 six-1.12.0 urllib3-1.25.2
$ /tmp/gcp/8014/bin/python
Python 3.6.7 (default, Oct 22 2018, 11:30:50) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import storage
>>> print(storage.__version__)
1.15.0
>>> ^D
$ /tmp/gcp/8014/bin/pip freeze | grep ==
cachetools==3.1.0
certifi==2019.3.9
chardet==3.0.4
google-api-core==1.11.0
google-auth==1.6.3
google-cloud-core==1.0.0
google-cloud-storage==1.16.0
google-resumable-media==0.3.2
googleapis-common-protos==1.5.10
idna==2.8
protobuf==3.7.1
pyasn1==0.4.5
pyasn1-modules==0.2.5
pytz==2019.1
requests==2.22.0
rsa==4.0
six==1.12.0
urllib3==1.25.2
```

Thing I note about your set of installed packages:

- The `google-cloud` meta-package is deprecated, not required, and should be removed.  I don't think that it is the cuplrit here:  installing it in my virtual environment didn't reproduce the import error.
- You have `google-cloud-storage==1.15.1`, while I have `google-cloud-storage==1.16.0` (just released this morning).  Downgrading it in my virtual environment didn't reproduce the import error.
- You have `googleapis-common-protos==1.6.0b9`, while I have `googleapis-common-protos==1.5.10`. Upgrading to the beta does not reproduce the import error.

Can you post the output of the following:

```python
>>> import google
>>> for f in google.__path__:
...    print(f)
... 
/tmp/gcp/8014/lib/python3.6/site-packages/google
>>> import google.cloud
>>> for f in google.cloud.__path__:
...    print(f)
... 
/tmp/gcp/8014/lib/python3.6/site-packages/google/cloud
```

**Comment by dantuluri** [comment]
Thanks for the help. Although I should've followed the instructions you have gave me, I decided to reset my machine so that I can fully dockerize all my future projects to prevent silly errors such as this. Once I did so, everything worked flawlessly. I hope to continue using GCP!

**Comment by tseaver** [comment]
@dantuluri I'm glad you got the issue resolved!

**Comment by inforticx** [comment]
Just restart the machine or restart the kernel in Jupyter.

**Comment by Magikzigo** [comment]
Dears, I got a similar issue that I cannot solve using cloud functions.
Here is the setup I am using:
Steps to reproduce

    Open Gcloud cloud functions. Choose Python 3.8
    Input in requirements.txt:
  google-cloud-storage == 1.42.3
  pandas == 1.2.1
  asyncio == 3.4.3
  google-cloud-pubsub == 2.9.0
  numpy==1.19.5
  tensorflow == 2.1.0
  google-cloud-bigquery==2.3.1
  google-cloud-bigquery-storage==2.0.1
  google-api-core==1.23.0
  google-cloud-core==1.4.2
  pyarrow==2.0.0

Go into main and input:
  import tensorflow as tf
  from tensorflow.python.lib.io import file_io
  import pandas as pd
  import asyncio
  from google.cloud import storage
  from google.cloud import bigquery
  from google.api_core import retry
  from google.cloud import pubsub_v1
  import numpy as np

  bqclient = bigquery.Client()
  client = storage.Client()
  def hello_pubsub(event, context):
    """Triggered from a message on a Cloud Pub/Sub topic.
    Args:
         event (dict): Event payload.
         context (google.cloud.functions.Context): Metadata for the event.
    """
    print('whatever, this is not going to work?!')
  

What happened

The cloud function fails to deploy, error is : 
ImportError: cannot import name 'storage' from 'google.cloud' (unknown location)
at .<module> ( [/workspace/main.py:5](https://console.cloud.google.com/debug?referrer=fromlog&file=%2Fworkspace%2Fmain.py&line=5&project=XXX )
at ._call_with_frames_removed ( [<frozen importlib._bootstrap>:219](https://console.cloud.google.com/debug?referrer=fromlog&file=%3Cfrozen%20importlib._bootstrap%3E&line=219&project=XXX) )
at .exec_module ( [<frozen importlib._bootstrap_external>:843](https://console.cloud.google.com/debug?referrer=fromlog&file=%3Cfrozen%20importlib._bootstrap_external%3E&line=843&project=XXX) )
at .create_app ( [/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py:288](https://console.cloud.google.com/debug?referrer=fromlog&file=%2Flayers%2Fgoogle.python.pip%2Fpip%2Flib%2Fpython3.8%2Fsite-packages%2Ffunctions_framework%2F__init__.py&line=288&project=XXX) )
at ._cli ( [/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/_cli.py:37](https://console.cloud.google.com/debug?referrer=fromlog&file=%2Flayers%2Fgoogle.python.pip%2Fpip%2Flib%2Fpython3.8%2Fsite-packages%2Ffunctions_framework%2F_cli.py&line=37&project=XXX) )
at .invoke ( [/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py:754](https://console.cloud.google.com/debug?referrer=fromlog&file=%2Flayers%2Fgoogle.python.pip%2Fpip%2Flib%2Fpython3.8%2Fsite-packages%2Fclick%2Fcore.py&line=754&project=XXX) )
at .invoke ( [/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py:1395](https://console.cloud.google.com/debug?referrer=fromlog&file=%2Flayers%2Fgoogle.python.pip%2Fpip%2Flib%2Fpython3.8%2Fsite-packages%2Fclick%2Fcore.py&line=1395&project=XXX) )
at .main ( [/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py:1053](https://console.cloud.google.com/debug?referrer=fromlog&file=%2Flayers%2Fgoogle.python.pip%2Fpip%2Flib%2Fpython3.8%2Fsite-packages%2Fclick%2Fcore.py&line=1053&project=XXX) )
at .__call__ ( [/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py:1128](https://console.cloud.google.com/debug?referrer=fromlog&file=%2Flayers%2Fgoogle.python.pip%2Fpip%2Flib%2Fpython3.8%2Fsite-packages%2Fclick%2Fcore.py&line=1128&project=XXX) )
at .<module> ( [/layers/google.python.pip/pip/bin/functions-framework:8](https://console.cloud.google.com/debug?referrer=fromlog&file=%2Flayers%2Fgoogle.python.pip%2Fpip%2Fbin%2Ffunctions-framework&line=8&project=XXX) )

Error message: 
ImportError: cannot import name 'storage' from 'google.cloud' (unknown location)

Important note:

When I run the code in Gcloud jupyter notebook, I do not have any error message.

Could anyone give me a hand? Many thanks in advance, I am a bit stuck here !

Let me know if you need additional information. I suspect a package conflict, but couldn't solve it until now...

**Comment by RubensZimbres** [comment]
Same problem with neo4j-graphrag[google] as of Jan 2025

```
google-ai-generativelanguage  0.6.15
google-api-core               2.24.0
google-api-python-client      2.159.0
google-auth                   2.38.0
google-auth-httplib2          0.2.0
google-cloud                  0.34.0
google-cloud-aiplatform       1.71.1
google-cloud-bigquery         3.27.0
google-cloud-core             2.4.1
google-cloud-resource-manager 1.14.0
google-cloud-secret-manager   2.22.1
google-cloud-storage          2.19.0
google-crc32c                 1.6.0
google-genai                  0.6.0
google-generativeai           0.8.4
google-resumable-media        2.7.2
googleapis-common-protos      1.66.0
grpc-google-iam-v1            0.14.0
langchain-google-genai        2.0.9
langchain-google-vertexai     1.0.8
neo4j                         5.27.0
neo4j-graphrag                1.4.2
```

```
ImportError                               Traceback (most recent call last)
Cell In[10], [line 3](vscode-notebook-cell:?execution_count=10&line=3)
      [1](vscode-notebook-cell:?execution_count=10&line=1) from neo4j_graphrag.embeddings.vertexai import VertexAIEmbeddings
      [2](vscode-notebook-cell:?execution_count=10&line=2) from neo4j_graphrag.llm import VertexAILLM
----> [3](vscode-notebook-cell:?execution_count=10&line=3) from vertexai.generative_models import GenerationConfig
      [5](vscode-notebook-cell:?execution_count=10&line=5) generation_config = GenerationConfig(temperature=0.0)
      [6](vscode-notebook-cell:?execution_count=10&line=6) ex_llm = VertexAILLM(
      [7](vscode-notebook-cell:?execution_count=10&line=7)     model_name="gemini-1.5-flash-001", generation_config=generation_config
      [8](vscode-notebook-cell:?execution_count=10&line=8) )

File ~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/vertexai/__init__.py:19
     [15](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/vertexai/__init__.py:15) """The vertexai module."""
     [17](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/vertexai/__init__.py:17) import importlib
---> [19](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/vertexai/__init__.py:19) from google.cloud.aiplatform import version as aiplatform_version
     [21](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/vertexai/__init__.py:21) __version__ = aiplatform_version.__version__
     [23](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/vertexai/__init__.py:23) from google.cloud.aiplatform import init

File ~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py:24
     [19](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py:19) from google.cloud.aiplatform import version as aiplatform_version
     [21](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py:21) __version__ = aiplatform_version.__version__
---> [24](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py:24) from google.cloud.aiplatform import initializer
     [26](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py:26) from google.cloud.aiplatform.datasets import (
     [27](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py:27)     ImageDataset,
     [28](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py:28)     TabularDataset,
   (...)
     [31](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py:31)     VideoDataset,
     [32](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py:32) )
     [33](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py:33) from google.cloud.aiplatform import explain

File ~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/initializer.py:37
     [35](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/initializer.py:35) from google.cloud.aiplatform import compat
     [36](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/initializer.py:36) from google.cloud.aiplatform.constants import base as constants
---> [37](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/initializer.py:37) from google.cloud.aiplatform import utils
     [38](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/initializer.py:38) from google.cloud.aiplatform.metadata import metadata
     [39](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/initializer.py:39) from google.cloud.aiplatform.utils import resource_manager_utils

File ~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/utils/__init__.py:32
     [30](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/utils/__init__.py:30) from google.api_core import gapic_v1
     [31](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/utils/__init__.py:31) from google.auth import credentials as auth_credentials
---> [32](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/utils/__init__.py:32) from google.cloud import storage
     [34](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/utils/__init__.py:34) from google.cloud.aiplatform import compat
     [35](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/aiplatform/utils/__init__.py:35) from google.cloud.aiplatform.constants import base as constants

File ~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/__init__.py:35
     [15](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/__init__.py:15) """Shortcut methods for getting set up with Google Cloud Storage.
     [16](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/__init__.py:16) 
     [17](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/__init__.py:17) You'll typically use these to get started with the API:
   (...)
     [31](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/__init__.py:31)   machine).
     [32](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/__init__.py:32) """
     [34](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/__init__.py:34) from google.cloud.storage.version import __version__
---> [35](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/__init__.py:35) from google.cloud.storage.batch import Batch
     [36](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/__init__.py:36) from google.cloud.storage.blob import Blob
     [37](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/__init__.py:37) from google.cloud.storage.bucket import Bucket

File ~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/batch.py:42
     [38](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/batch.py:38) import json
     [40](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/batch.py:40) import requests
---> [42](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/batch.py:42) from google.cloud import _helpers
     [43](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/batch.py:43) from google.cloud import exceptions
     [44](https://file+.vscode-resource.vscode-cdn.net/home/theone/Downloads/Zendata/neo4j/~/Downloads/Zendata/neo4j/.conda/lib/python3.10/site-packages/google/cloud/storage/batch.py:44) from google.cloud.storage._http import Connection

ImportError: cannot import name '_helpers' from 'google.cloud' (unknown location)
```
