### ISSUE TITLE
Pub/Sub: the emulator is broken

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-python#8290]
The emulator used to work, but it seems broken now. 

#### Environment details

2. MacOS
3. `Python 3.7.3`
4. `google-cloud-pubsub==0.41.0`

#### Steps to reproduce

  1. `git clone https://github.com/GoogleCloudPlatform/python-docs-samples.git`, then create a virtualenv and install the necessary packages from `pip install -r pubsub/cloud-client/requirements.txt`. 
  2. Start a Pub/Sub emulator in one terminal where the virtualenv is activated:`gcloud beta emulator pubsub start`.
  3. In a separate terminal where the virtualenv is also activated, export the appropriate environment variables. `export PUBSUB_PROJECT_ID=my-project-id`, then `$(gcloud beta emulators pubsub env-init)`. The latter ensures that `PUBSUB_EMULATOR_HOST` takes the correct hostname and port number. 
  4. `cd pubsub/cloud-client`, then test out the emulator by creating a topic. `python publisher.py my-project-id topics create my-topic`. 

#### Stack trace
```
(pubsub3) tianzi (tz) cloud-client $ python publisher.py tz-playground-bigdata create us
Traceback (most recent call last):
  File "/Users/tianzi/.virtualenvs/pubsub3/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/tianzi/.virtualenvs/pubsub3/lib/python3.7/site-packages/grpc/_channel.py", line 549, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/tianzi/.virtualenvs/pubsub3/lib/python3.7/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid [topics] name: (name=projects/tz-playground-bigdata/topics/us)"
	debug_error_string = "{"created":"@1560295651.919535000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Invalid [topics] name: (name=projects/tz-playground-bigdata/topics/us)","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "publisher.py", line 269, in <module>
    create_topic(args.project_id, args.topic_name)
  File "publisher.py", line 54, in create_topic
    topic = publisher.create_topic(topic_path)
  File "/Users/tianzi/.virtualenvs/pubsub3/lib/python3.7/site-packages/google/cloud/pubsub_v1/_gapic.py", line 45, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/Users/tianzi/.virtualenvs/pubsub3/lib/python3.7/site-packages/google/cloud/pubsub_v1/gapic/publisher_client.py", line 297, in create_topic
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/Users/tianzi/.virtualenvs/pubsub3/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/tianzi/.virtualenvs/pubsub3/lib/python3.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/Users/tianzi/.virtualenvs/pubsub3/lib/python3.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/Users/tianzi/.virtualenvs/pubsub3/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/tianzi/.virtualenvs/pubsub3/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Invalid [topics] name: (name=projects/tz-playground-bigdata/topics/us)
```

**Comment by anguillanneuf** [comment]
I must have missed something. Closed a bunch of terminals, and it's working now!
