### ISSUE TITLE
Testing:  'get_target_packages_kokoro.py' script recieving bogus output.

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#8668]
From [this Kokoro job today](https://source.cloud.google.com/results/invocations/ef22b02c-8631-4f6d-bd99-33de0d84984c/targets/cloud-devrel%2Fclient-libraries%2Fgoogle-cloud-python%2Fpresubmit%2Fwebsecurityscanner/log):

```python
Traceback (most recent call last):
  File "test_utils/scripts/get_target_packages_kokoro.py", line 98, in <module>
    main()
  File "test_utils/scripts/get_target_packages_kokoro.py", line 85, in main
    changed_files = list(get_changed_files_from_pr(environment.pr))
  File "test_utils/scripts/get_target_packages_kokoro.py", line 60, in get_changed_files_from_pr
    yield info['filename']
TypeError: string indices must be integers
```

**Comment by tseaver** [comment]
Another job 404s out from the `get_target_packages_kokoro.py` script:

```python
    X-RateLimit-Remaining: 59
        X-RateLimit-Limit: 60
        X-RateLimit-Reset: 1562961747
You can avoid being rate limited by storing a GitHub OAuth token in the GITHUB_OAUTH_TOKEN environment variable
Traceback (most recent call last):
  File "test_utils/scripts/get_target_packages_kokoro.py", line 98, in <module>
    main()
  File "test_utils/scripts/get_target_packages_kokoro.py", line 81, in main
    print_environment(environment)
  File "test_utils/scripts/get_target_packages_kokoro.py", line 31, in print_environment
    print('PR Base', environment.base)
  File "/usr/local/lib/python3.6/site-packages/ci_diff_helper/kokoro.py", line 340, in base
    pr_info = self._pr_info
  File "/usr/local/lib/python3.6/site-packages/ci_diff_helper/kokoro.py", line 279, in _pr_info
    self._pr_info_cached = _github.pr_info(self.slug, current_pr)
  File "/usr/local/lib/python3.6/site-packages/ci_diff_helper/_github.py", line 124, in pr_info
    _maybe_fail(response)
  File "/usr/local/lib/python3.6/site-packages/ci_diff_helper/_github.py", line 79, in _maybe_fail
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/googleapis/google-cloud-python/pulls/8667
```

**Comment by busunkim96** [comment]
Looks like we need a token in the Kokoro environment. I'll take this.

**Comment by tseaver** [comment]
@busunkim96 Did you do something which you think actually resolved this issue?

**Comment by busunkim96** [comment]
This is now obsolete given the split repos
