### ISSUE TITLE
Firestore: 504 Deadline Exceeded making single write on Firestore

### ISSUE THREAD

**Issue by amritsub** [googleapis/google-cloud-python#8933]
resurfaced from https://github.com/firebase/firebase-admin-python/issues/308

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version: macOs Mojave 10.14.5
3. Python version and virtual environment information: **Python 3.7.4**
4. google-cloud-<service> version:  `pip show google-<service>` or `pip freeze`
**firebase-admin==2.17.0
google-api-core==1.14.2
google-api-python-client==1.7.10
google-cloud-core==1.0.3
google-cloud-firestore==1.3.0**

#### Steps to reproduce

  1. Initialize GOOGLE_APPLICATION_CREDENTIALS environment variable with the Firebase service account json file path.
2. Set up virtualenv, install firebase-admin and run it.

#### Code example

```python
import firebase_admin
from firebase_admin import firestore, credentials

firebase_admin.initialize_app()
print("initialized firebase successfully")

product_dict={
  'test1': 'test',
  'test2': 'test2'
}
firestore_client = firestore.client()
doc_ref = firestore_client.collection('products').document('test2')
doc_ref.set(product_dict)
```

#### Stack trace
```
Traceback (most recent call last):
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1564801527.004575000","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    doc_ref.set(product_dict)
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/cloud/firestore_v1/document.py", line 234, in set
    write_results = batch.commit()
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/cloud/firestore_v1/batch.py", line 147, in commit
    metadata=self._client._rpc_metadata,
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/cloud/firestore_v1/gapic/firestore_client.py", line 1042, in commit
    request, retry=retry, timeout=timeout, metadata=metadata
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/retry.py", line 273, in retry_wrapped_func
    on_error=on_error,
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/retry.py", line 182, in retry_target
    return target()
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File ".../FirestoreTest/firestoretestenv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
```

**Comment by tseaver** [comment]
The traceback you report is due to the back-end not replying to the `Batch.commit` request within 60 seconds (configured [here](https://github.com/googleapis/google-cloud-python/blob/0ce1ca52fe6fb49a40d65049ada5e000049b681d/firestore/google/cloud/firestore_v1/gapic/firestore_client_config.py#L64-L68)).

Although implicit retries are disabled by default for non-idempotent operations, you can add explicitretry support at the application level, e.g.:

```python
from google.api_core import exceptions
from google.api_core import retry

...

# Could include other retriable exception types
predicate_504 = retry.if_exception_type(exceptions.DeadlineExceeded)

# Could configure deadline, etc.
retry_504 = retry.Retry(predicate_504)

retry_504(doc_ref.set)(product_dict)
```

**Comment by amritsub** [comment]
okay, setting the predicate worked, although I'm not sure why I would need to do that. Using Cloud Datastore, I never ran into this issue and would expect the same performance with Firestore.

also I tried measuring the time in which the 504 gets thrown, which seems to be around 20 seconds rather than 60 seconds. here is how I attempted to time it:
```
from timeit import default_timer as timer
....
start_time = timer()
try:
  doc_ref.set(product_dict)
except:
  print("died")
  print("--- %s seconds ---" % (timer() - start_time))
```

output

```
initialized firebase successfully
died
--- 20.007382607 seconds ---
```

**Comment by tseaver** [comment]
@amritsub Thanks for the follow up.  The timeout for the initial RPC is configured [here](https://github.com/googleapis/google-cloud-python/blob/0ce1ca52fe6fb49a40d65049ada5e000049b681d/firestore/google/cloud/firestore_v1/gapic/firestore_client_config.py#L13) as 20000 ms, which likely explains the timing you are seeing.

**Comment by tseaver** [comment]
@shollyman Any suggestions as to why that initial RPC request would be taking longer?

**Comment by shollyman** [comment]
I'm not familiar with firestore backend.  Tagging @BenWhitehead instead.

**Comment by amritsub** [comment]
any ideas?

**Comment by crwilcox** [comment]
Hi @amritsub . We are going to modify the timeout to default to 60 seconds. We believe that may resolve your issue.

**Comment by AivanF** [comment]
Hi everyone!
I'm facing quite the same issue:

```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/anaconda3/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1568874388.963494000","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/aivanf/MyProject/fs.py", line 41, in <module>
    'born': 1815,
  File "/Users/aivanf/MyProject/fs.py", line 29, in create_doc
    doc_ref.set(data)
  File "/anaconda3/lib/python3.6/site-packages/google/cloud/firestore_v1/document.py", line 234, in set
    write_results = batch.commit()
  File "/anaconda3/lib/python3.6/site-packages/google/cloud/firestore_v1/batch.py", line 147, in commit
    metadata=self._client._rpc_metadata,
  File "/anaconda3/lib/python3.6/site-packages/google/cloud/firestore_v1/gapic/firestore_client.py", line 1042, in commit
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/anaconda3/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/google/api_core/retry.py", line 273, in retry_wrapped_func
    on_error=on_error,
  File "/anaconda3/lib/python3.6/site-packages/google/api_core/retry.py", line 182, in retry_target
    return target()
  File "/anaconda3/lib/python3.6/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
[Finished in 20.4s with exit code 1]
[shell_cmd: python -u "/Users/aivanf/MyProject/fs.py"]
[dir: /Users/aivanf/MyProject]
[path: /anaconda3/bin:/Users/aivanf/Library/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin]
```

I have:  
Anaconda Python 3.6  
google-cloud-firestore==1.4.0
running on macOS Mojave 10.14.6

Some notable details:  
1) Yesterday everything worked just fine.  
2) When I connect through VPN (which is located in the same city) everything works fine.

But that doesn't reassure me because I need to run my code on a server, and I have certainty that such things will not happen there.

**Comment by schnoddelbotz** [comment]
With the hope that it might help someone facing the same issue:
I ran into the same error on Catalina ... but things started working instantly without any problem after turning off my [sshuttle](https://github.com/sshuttle/sshuttle)-based vpn (which uses `sshuttle -l 0.0.0.0 --dns -r ...`).
