### ISSUE TITLE
Datastore: google.api_core.exceptions.InvalidArgument: 400 list_value cannot contain a Value containing another list_value.

### ISSUE THREAD

**Issue by vefae** [googleapis/google-cloud-python#9038]
Hi guys, I am trying to run a Python function in Google Cloud functions to extract Tweets using searchtweets package. And I am experiencing a weird problem. I want to make this function to be triggered everyday, so I use datetime to detect date, then convert this date to a string and input it to the rule of searchtweet package. 

If I use the manul dates strings like below, there is no problem, everything works:

```
    from_date="2019-08-10"
    to_date="2019-08-11"
```
But when I try to get the date string from datetime using below code, I experience the error at the bottom:

```
    today = datetime.datetime.today()
    yesterday = today - datetime.timedelta(days=1)
    from_date=str(yesterday)[:10]
    to_date= str(today)[:10]
```
I tried many different versions of getting the date strings, none has worked so far. 
So basically, if I try to get the dates indirectly from another calculation, it gives an error.

I use below requirements.txt file. 

Requirements:

```

python-dateutil
searchtweets
google-cloud-datastore
```

My function:

```
import os
import re
import base64
import datetime
from searchtweets import ResultStream, gen_rule_payload, load_credentials, collect_results
from google.cloud import datastore

client_gcp = datastore.Client()


def get_twittt(event, context):

    today = datetime.datetime.today()
    yesterday = today - datetime.timedelta(days=1)
    from_date=str(yesterday)[:10]
    to_date= str(today)[:10]
    premium_search_args = load_credentials(filename="twitter_keys",yaml_key="search_tweets")
    market = []
    rule = gen_rule_payload("(text to searc) lang:tr",  from_date=from_date, to_date=to_date, results_per_call=100)
     
    for tweet in collect_results(rule, max_results=20,result_stream_args=premium_search_args):
		key = client_gcp.key('twitter')
		entity = datastore.Entity(key)
		entity.update(tweet)
		client_gcp.put(entity)`
```

Detailed error message from my local environment:

  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "list_value cannot contain a Value containing another list_value."
	debug_error_string = "{"created":"@1565730099.817486697","description":"Error received from peer ipv4:216.58.208.106:443","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"list_value cannot contain a Value containing another list_value.","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gc_data.py", line 41, in <module>
    client_gcp.put(entity)
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/cloud/datastore/client.py", line 447, in put
    self.put_multi(entities=[entity])
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/cloud/datastore/client.py", line 474, in put_multi
    current.commit()
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/cloud/datastore/batch.py", line 274, in commit
    self._commit()
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/cloud/datastore/batch.py", line 250, in _commit
    self.project, mode, self._mutations, transaction=self._id
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/cloud/datastore_v1/gapic/datastore_client.py", line 571, in commit
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/api_core/retry.py", line 273, in retry_wrapped_func
    on_error=on_error,
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/api_core/retry.py", line 182, in retry_target
    return target()
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/vefa/anaconda3/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 list_value cannot contain a Value containing another list_value.

**Comment by vefae** [comment]
Hi guys, I am closing the issue, because it started working randomly. I did not change anything. Same code above works now.
