### ISSUE TITLE
WRITER is not a valid ACL permission for a blob

### ISSUE THREAD

**Issue by diiiego83** [googleapis/google-cloud-python#9099]
#### Environment details

Name: Python
Version: 3.7.4

Name: google-cloud-storage
Version: 1.18.0
Summary: Google Cloud Storage API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: c:\users\..........\python\python37-32\lib\site-packages
Requires: google-auth, google-resumable-media, google-cloud-core

#### Steps to reproduce

WRITER is not a valid permission value for a blob (only owner/reader).

#### Code example

```python
from google.cloud import storage
storage_client = storage.Client()
bucket = storage_client.get_bucket('[BUCKET_NAME]')
blob = bucket.blob('[OBJECT_NAME]')
blob.acl.user('[USER_IDENTITY]').grant_write()
blob.acl.save()
```

#### Stack trace
```
Traceback (most recent call last):
  File "./test.py", line 33, in <module>
    upload_blob(bucket, data, folder + '/' + str(i))
  File "./test.py", line 19, in upload_blob
    blob.acl.save()
  File "C:\Users\.............\Python\Python37-32\lib\site-packages\google\cloud\storage\acl.py", line 504, in save
    self._save(acl, None, client)
  File "C:\Users\.............\Python\Python37-32\lib\site-packages\google\cloud\storage\acl.py", line 476, in _save
    query_params=query_params,
  File "C:\Users\.............\Python\Python37-32\lib\site-packages\google\cloud\_http.py", line 393, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 PATCH https://www.googleapis.com/storage/v1/b/......./o/2019-08-24%2017%3A26%3A31.047946%2F0?projection=full: Invalid value for: WRITER is not a valid value
```

Thanks!

**Comment by IlyaFaer** [comment]
@diiiego83, you're trying to set WRITER permission to a blob, right? Take a look at [docs](https://cloud.google.com/storage/docs/access-control/lists#permissions), please. I think, it's your case: `WRITER ... You cannot apply this permission to objects.`

**Comment by diiiego83** [comment]
yep i know i cannot do it but the library gave me the option to set it from
the acl of a blob object. In theory the ACL object of a blob object should
not have the property for set a write permission.
