### ISSUE TITLE
Storage: 403 Forbidden when downloading blob.

### ISSUE THREAD

**Issue by shahanaz873** [googleapis/google-cloud-python#9158]
I am trying to download a file from cloud bucket storage, I have both read and write access to the bucket but I am not able to download any files, below is my code and error

    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = 'client_secret.json'
    storage_client = storage.Client()
    bucket = storage_client.get_bucket(bucket_name)
    blob = bucket.blob(source_blob_name)
    blob.download_to_filename(destination_file_name)
    print('Blob {} downloaded ")

Error during download
    Traceback (most recent call last):
    File "C:\Users\username\Documents\PycharmProjects\testproj\venv\lib\site-packages\google\cloud\storage\blob.py", line 637, in download_to_file
    self._do_download(transport, file_obj, download_url, headers, start, end)
    File "C:\Users\username\Documents\PycharmProjects\testproj\venv\lib\site-packages\google\cloud\storage\blob.py", line 575, in _do_download
    download.consume(transport)
    File "C:\Users\username\Documents\PycharmProjects\testproj\venv\lib\site-packages\google\resumable_media\requests\download.py", line 171, in consume
    self._process_response(result)
    File "C:\Users\username\Documents\PycharmProjects\testproj\venv\lib\site-packages\google\resumable_media\_download.py", line 170, in _process_response
    response, _ACCEPTABLE_STATUS_CODES, self._get_status_code)
    File "C:\Users\username\Documents\PycharmProjects\testproj\venv\lib\site-packages\google\resumable_media\_helpers.py", line 93, in require_status_code
    status_code, u'Expected one of', *status_codes)
    google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
   File "C:/Users/username/Documents/PycharmProjects/testproj/download.py", line 558, in 
   <module>
    main()
    File "C:/Users/username/Documents/PycharmProjects/testproj/download.py", line 551, in main
    user_profile)
    File "C:/Users/username/Documents/PycharmProjects/testproj/download.py", line 227, in download_blob
    blob.download_to_filename(destination_file_name)
  File "C:\Users\username\Documents\PycharmProjects\testproj\venv\lib\site-packages\google\cloud\storage\blob.py", line 665, in download_to_filename
    self.download_to_file(file_obj, client=client, start=start, end=end)
  File "C:\Users\username\Documents\PycharmProjects\testproj\venv\lib\site-packages\google\cloud\storage\blob.py", line 639, in download_to_file
    _raise_from_invalid_response(exc)
  File "C:\Users\username\Documents\PycharmProjects\testproj\venv\lib\site-packages\google\cloud\storage\blob.py", line 2038, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.Forbidden: 403 GET https://www.googleapis.com/download/storage/v1/b/test/o/files.zip?alt=media: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

Process finished with exit code 1

**Comment by tseaver** [comment]
@shahanaz873 The 403 Forbidden response means that the service account you are using does not have permission to download the blob.  Can you check the roles assigned to that account in the Google Cloud console, and paste them here?

**Comment by tseaver** [comment]
In your particular case, you are trying to use the bucket named `test`.  In Cloud Storage, [all buckets live in a single namespace](https://cloud.google.com/storage/docs/naming#requirements), which likely means that the `test` bucket exists and belongs to another project / user.

Please feel free to follow up if this answer isn't sufficient.

**Comment by shahanaz873** [comment]
Hi @tseaver, As i see the object access is mentioned as "Not Public" is this the reason I am not able to download anything from the bucket?
These are the roles assigned to my account
Storage Admin
Storage Legacy Bucket Reader

**Comment by shahanaz873** [comment]
I have changed the json file with other service account where I have full access and I am able to download the files.
 Thank you @tseaver

**Comment by LiguoMa274** [comment]
Sorry bro
Could you tell me how to change the permission of bucket?
I have the same issue
Best Regards

**Comment by nandakarvapaly** [comment]
> Sorry bro
> Could you tell me how to change the permission of bucket?
> I have the same issue
> Best Regards

Add the `Storage Admin` role in IAM and generate a new key for this SA Email which generates a JSON file. 
Use this key file where you are trying to access.
