### ISSUE TITLE
Storage: cannot instantiate google.cloud.storage.Client during setup.py test

### ISSUE THREAD

**Issue by ZeeD** [googleapis/google-cloud-python#9519]
I'm having problems trying to write an (integration) test that uses the storage.Client.
I'm using my personal account to log to GCP
it seems that the problem is present only when launching the code via setuptools. Calling directly or with the unittest module everything works.

--- EDIT ---
it seems that the problem is that the storage library relies on running gcloud to extract the project id,
AND the fact that setuptools inject a custom PYTHONPATH,
AND the fact that I'm using Crypto.Hash (?)

keep in mind that normally I don't have PYTHONPATH set, and I use my os (ubuntu) gcloud

```
$ gcloud --version
Google Cloud SDK 268.0.0
alpha 2019.10.18
beta 2019.10.18
bq 2.0.49
core 2019.10.18
gsutil 4.45
kubectl 2019.10.18
pubsub-emulator 2019.10.18
```

```
$ PYTHONPATH=/home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages gcloud --version
ERROR: gcloud failed to load: Cannot load native module 'Crypto.Hash._SHA256': Trying '_SHA256.x86_64-linux-gnu.so': /home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/Crypto/Util/../Hash/_SHA256.x86_64-linux-gnu.so: cannot open shared object file: No such file or directory, Trying '_SHA256.so': /home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/Crypto/Util/../Hash/_SHA256.so: cannot open shared object file: No such file or directory, Trying '_SHA256module.so': /home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/Crypto/Util/../Hash/_SHA256module.so: cannot open shared object file: No such file or directory
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.api_lib.iamcredentials import util as iamcred_util
    from googlecloudsdk.core.credentials import http as http_creds
    from googlecloudsdk.core.credentials import creds as core_creds
    from googlecloudsdk.core.credentials import devshell as c_devshell
    from oauth2client import client
    from oauth2client import crypt
    from oauth2client import _pycrypto_crypt
    from Crypto.Hash import SHA256
    """)
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 executable:
    /usr/bin/python2

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.

If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/
```

keep in mind the fact that it's setuptools' setup test that add the PYTHONPATH... but moreover I don't understand how this is related to gcloud... shouldn't it use python2?

--- 

```
$ cat worker_sftp/integration_tests/liftshift/brokengcloud.py
import unittest

from google.cloud import storage


class BrokenGcloud(unittest.TestCase):

    def test_storage_client(self) -> None:
        client = storage.Client()
        for blob in client.list_blobs('skyita-da-daita-dev-integration-tests'):
            print(f'blob={blob}')


if __name__ == '__main__':
    BrokenGcloud().test_storage_client()
```

```
$ python worker_sftp/integration_tests/liftshift/brokengcloud.py            
/home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
/home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
blob=<Blob: skyita-da-daita-dev-integration-tests, cloud-storage-client/, 1568817351812083>
blob=<Blob: skyita-da-daita-dev-integration-tests, cloud-storage-client/large-file-to-upload.json, 1568817540348012>
blob=<Blob: skyita-da-daita-dev-integration-tests, cloud-storage-client/upload.txt, 1568817523707540>
blob=<Blob: skyita-da-daita-dev-integration-tests, ingester/, 1568190689229702>
blob=<Blob: skyita-da-daita-dev-integration-tests, ingester/a_lot_of_pii.csv, 1568191083905722>
blob=<Blob: skyita-da-daita-dev-integration-tests, ingester/a_lot_of_pii1.csv, 1568304779103972>
blob=<Blob: skyita-da-daita-dev-integration-tests, ingester/bi_lead_converter_it.avro, 1571219568318995>
blob=<Blob: skyita-da-daita-dev-integration-tests, ingester/bi_lead_converter_it.csv, 1571154407556237>
blob=<Blob: skyita-da-daita-dev-integration-tests, metamodel-importer/, 1568293786399611>
blob=<Blob: skyita-da-daita-dev-integration-tests, metamodel-importer/schemas/, 1568293894037690>
blob=<Blob: skyita-da-daita-dev-integration-tests, metamodel-importer/schemas/excel_reader_test_file.xlsx, 1568297934892660>
```

```
$ python -munittest worker_sftp/integration_tests/liftshift/brokengcloud.py 
/home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
/home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
blob=<Blob: skyita-da-daita-dev-integration-tests, cloud-storage-client/, 1568817351812083>
blob=<Blob: skyita-da-daita-dev-integration-tests, cloud-storage-client/large-file-to-upload.json, 1568817540348012>
blob=<Blob: skyita-da-daita-dev-integration-tests, cloud-storage-client/upload.txt, 1568817523707540>
blob=<Blob: skyita-da-daita-dev-integration-tests, ingester/, 1568190689229702>
blob=<Blob: skyita-da-daita-dev-integration-tests, ingester/a_lot_of_pii.csv, 1568191083905722>
blob=<Blob: skyita-da-daita-dev-integration-tests, ingester/a_lot_of_pii1.csv, 1568304779103972>
blob=<Blob: skyita-da-daita-dev-integration-tests, ingester/bi_lead_converter_it.avro, 1571219568318995>
blob=<Blob: skyita-da-daita-dev-integration-tests, ingester/bi_lead_converter_it.csv, 1571154407556237>
blob=<Blob: skyita-da-daita-dev-integration-tests, metamodel-importer/, 1568293786399611>
blob=<Blob: skyita-da-daita-dev-integration-tests, metamodel-importer/schemas/, 1568293894037690>
blob=<Blob: skyita-da-daita-dev-integration-tests, metamodel-importer/schemas/excel_reader_test_file.xlsx, 1568297934892660>
.
----------------------------------------------------------------------
Ran 1 test in 0.824s

OK
```

```
$ python -msetup test -s worker_sftp.integration_tests.liftshift.brokengcloud
running test
running egg_info
writing skytv_worker_sftp.egg-info/PKG-INFO
writing dependency_links to skytv_worker_sftp.egg-info/dependency_links.txt
writing requirements to skytv_worker_sftp.egg-info/requires.txt
writing top-level names to skytv_worker_sftp.egg-info/top_level.txt
reading manifest file 'skytv_worker_sftp.egg-info/SOURCES.txt'
writing manifest file 'skytv_worker_sftp.egg-info/SOURCES.txt'
running build_ext
test_storage_client (worker_sftp.integration_tests.liftshift.brokengcloud.BrokenGcloud) ... /home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
ERROR

======================================================================
ERROR: test_storage_client (worker_sftp.integration_tests.liftshift.brokengcloud.BrokenGcloud)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/component/connectors/worker-sftp/src/worker_sftp/worker_sftp/integration_tests/liftshift/brokengcloud.py", line 9, in test_storage_client
    client = storage.Client()
  File "/home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/google/cloud/storage/client.py", line 82, in __init__
    project=project, credentials=credentials, _http=_http
  File "/home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/google/cloud/client.py", line 226, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/home/vito.detullio/Scrivania/ideaworkspace/ita-data-analytics/venv/lib/python3.7/site-packages/google/cloud/client.py", line 181, in __init__
    "Project was not passed and could not be "
OSError: Project was not passed and could not be determined from the environment.

----------------------------------------------------------------------
Ran 1 test in 0.248s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
(venv) vito.detullio@FGVIL021718L:~/Scrivania/ideaworkspace/ita-data-analytics/component/connectors/worker-sftp/src/worker_sftp$ 
```

**Comment by tseaver** [comment]
The first error (running `gcloud` and getting an error, `Cannot load native module 'Crypto.Hash._SHA256'`) is not related to this repository.  Please report it using one of the [Cloud SDK support resources](https://cloud.google.com/sdk/docs/getting-support).

The error when running `setup.py test` indicates that the environment variable (`GOOGLE_APPLICATION_CREDENTIALS`) needed to instantiate the `Client` is not set in the environment:  maybe it isn't exported, but just set, in the environment you are running it from?

**Comment by ZeeD** [comment]
the idea is that I'm not using GOOGLE_APPLICATION_CREDENTIALS; the application should onorate the gcloud configuration.
from what I understood from the library, the "problem" is that the Client constructor, in my case, open a subprocess and invoke the gcloud application.
but gcloud is a (wrapper of a) python application itself, so the PYTHONPATH env (set by setup.py) "broke" it.
maybe the call to the application should be made in a way to clear the PYTHONPATH before calling gcloud?

**Comment by tseaver** [comment]
I can't see anything we should be doing in this repository to fix your issue.  Please follow up / reopen if you can suggest such a change.
