### ISSUE TITLE
Translate: trying to translate the empty string should not raise an error.

### ISSUE THREAD

**Issue by verhovsky** [googleapis/google-cloud-python#9591]
The empty string translated to any human language (and probably any alien languages, if they exist) is just the empty string, but

```python
from pathlib import Path

from google.cloud.translate import TranslationServiceClient
from google.oauth2 import service_account


CREDENTIALS_FILE = "creds.json"

_credentials = service_account.Credentials.from_service_account_file(CREDENTIALS_FILE)
PROJECT_ID = "projects/" + _credentials.project_id

TranslationServiceClient(credentials=_credentials).translate_text(
    [""],
    target_language_code="ru",
    source_language_code="en",
    mime_type="text/plain",
    parent=PROJECT_ID,
)
```

will raise the following error

```
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/translate_v3/gapic/translation_service_client.py", line 356, in translate_text
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/retry.py", line 277, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/retry.py", line 182, in retry_target
    return target()
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Empty request.
```

because it can't send a request with no value. It probably shouldn't even send a request for any empty strings in the input. 

Right now I wrote 3 lines of code to convert `""` to `"empty string"` and then strip out those translations from the result but it would be nice if the API wrapper just did the right thing.

**Comment by nnegrey** [comment]
I think that is a valid error message to provide. If the user kept trying to do this and the client library silently did nothing it could cause confusion and make them assume the client library is at fault rather than their request itself.

**Comment by verhovsky** [comment]
It'll error if the empty string appears *anywhere* in the input.

```python
TranslationServiceClient(credentials=_credentials).translate_text(
    ["thousands or maybe", "even millions of strings", "could be here", "but it will raise an error", "because the last string is", "empty", ""],
    target_language_code="ru",
    source_language_code="en",
    mime_type="text/plain",
    parent=PROJECT_ID,
)
```

Doesn't have to be the last string.

**Comment by verhovsky** [comment]
@nnegrey please reopen this issue. At a minimum you should document this gotcha, but ideally you should make it not happen. Trying to translate an empty string is completely legitimate, especially when you are dealing with user input.

**Comment by gpkc** [comment]
I agree it's very unexpected to get an undocumented exception due to an empty string, considering user input.
