### ISSUE TITLE
SSL certificate error when using gsutil on machine in a private subnet

### ISSUE THREAD

**Issue by swvjeff** [googleapis/google-cloud-python#9886]
OS: Amazon Linux 2018.03
Python: 2.7.16
gsutil: 4.46

I'm receiving an `ssl.CertificateError` any time I try to run the `gsutil` command on our database server, which resides inside of a private subnet. This error only cropped up after I created a wildcard CNAME pointing everything to `web.mydomain.com` in Cloudflare and enabled Cloudflare's wildcard SSL. The hostname of the machine is `db.mydomain.com`. When I use `gsutil` from our `web.mydomain.com`, which is in a public subnet, everything works as expected. Here's the error I'm receiving from gsutil:

```% gsutil
Traceback (most recent call last):
  File "/opt/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 123, in <module>
    exceptions.HandleError(e, 'gsutil')
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/calliope/exceptions.py", line 527, in HandleError
    core_exceptions.reraise(exc)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 146, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/opt/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 121, in <module>
    main()
  File "/opt/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 35, in main
    project, account = bootstrapping.GetActiveProjectAndAccount()
  File "/opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 292, in GetActiveProjectAndAccount
    project_name = properties.VALUES.core.project.Get(validate=False)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 2039, in Get
    required)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 2338, in _GetProperty
    value = _GetPropertyWithoutDefault(prop, properties_file)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 2376, in _GetPropertyWithoutDefault
    value = callback()
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 260, in GetProject
    return c_gce.Metadata().Project()
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 281, in Metadata
    _metadata = _GCEMetadata()
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 94, in __init__
    self.connected = gce_cache.GetOnGCE()
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce_cache.py", line 155, in GetOnGCE
    return _SINGLETON_ON_GCE_CACHE.GetOnGCE(check_age)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce_cache.py", line 88, in GetOnGCE
    return self.CheckServerRefreshAllCaches()
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce_cache.py", line 91, in CheckServerRefreshAllCaches
    on_gce = self._CheckServer()
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce_cache.py", line 140, in _CheckServer
    gce_read.GOOGLE_GCE_METADATA_NUMERIC_PROJECT_URI)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce_read.py", line 66, in ReadNoProxy
    request, timeout=timeout_property).read()
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1243, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1197, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1058, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1098, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1054, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1279, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 836, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 292, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'metadata.google.internal' doesn't match '*.mydomain.com'
```

I'm assuming this isn't a bug, but instead a misconfiguration or DNS/SSL error on my end caused by the wildcard CNAME and the fact that `db.mydomain.com` doesn't actually point to this machine (which isn't accessible from the internet)? Any help would be appreciated.

**Comment by lizardslair** [comment]
I work with @swvjeff  and just wanted to share our findings in the unique issue in case anyone else happens to have this same issue in the future.

I found that there are different distros of _gsutil_ - one seems to be "standalone" and one shipped with the "google-cloud-sdk".

When the cloud version is invoked, it appears that it attempts to lookup "metadata.google.internal" to determine if the machine that is running the command is a part of Google's cloud infrastructure and on the network  (hense the .intenral TLD would resolve to Google's internal IPs).

As a feature of DNS resolution, you can set a set of "search" domains that will be suffixed to any entry in the case the entry doesn't exist alone. For example, if your device is configured to search "testing.com".. and you try to lookup simply "db"... it will fall-back to looking up "db.testing.com" if the initial lookup failed. Similar if you try to look up "server1.db" ... it will finally try "server1.db.testing.com".

So in our case... we set up a wildcard cname for *.mydomain.com.  Similarly, our "db" server has "mydomain.com" as a search domain by default. 

Therefore, when the SDK version of _gsutil_ was invoked, it attempted to resolve "metadata.google.internal" to see if it was on Google's internal network. Then the fall-back domain search was used in the lookup, which essentially became "metadata.google.internal.mydomain.com", and because of the wildcard "*.mydomain.com" it resolved to our primary website IP.

So, now the _gsutils_ tried connecting to the IP, which was our webserver that had an SSL certificate for "*.mydomain.com", which does not match the expected target of "metadata.google.internal" and threw a SSL connection exception.

So, we came up with two solutions:

1) Use the standalone version of _gsutil_ that does not query for the ".internal" domain name to resolve.

2) Update our machines' /etc/resolv.conf line for "search" domains to **not** include our primary domain name that now will answer to anything because of the wildcard entry (such as "a.b.c.d" would translate to "a.b.c.d.mydomain.com" which would resolve our website target IP)
